---Resource Data Module

local ResourceData = {}

ResourceData.Resources = {
	["resource_0000000001"] = {
		Name = "Yen",
		Icon = "rbxassetid://110751007066288",
		Type = "Resource",
		Description = "Cash",
		Rarity = "Common",
		Stackable = true,
		MaxStack = math.huge,	
	}
	,
	["resource_0000000002"] = {
		Name = "Fracta",
		Icon = "rbxassetid://114060338374650",
		Type = "Resource",
		Description = "Crystallized remnants of collapsed realities. Fragments where laws of space, time, or power broke and hardened.",
		Rarity = "Epic",
		Stackable = true,
		MaxStack = math.huge,	
	}
	,
	["resource_0000000003"] = {
		Name = "EXP",
		Icon = "rbxassetid://113574776208342",
		Type = "Resource",
		Description = "Glowy",
		Rarity = "Legendary",
		Stackable = true,
		MaxStack = math.huge,	
	}
	,
	
}


return ResourceData
