local Francium = {
    Name = "Francium",
    Symbol = "Fr",
    AtomicNumber = 87,
    AtomicMass = -223,
    RepresentativeMassNumber = 223,
    Protons = 87,
    Electrons = 87,
    NeutronsApprox = 136,
    Category = "Alkali",
    Group = "1",
    Period = 7,
    Block = "s",
    StateAt293K = "Solid",
    Density = 1.87,
    Appearance = {
        "An intensely radioactive metal.",
    },
    Uses = {
        "Francium has no uses, having a half life of only 22 minutes.",
    },
    ElectronConfiguration = "[Rn] 7s1",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        8,
        1,
    },
    AtomicRadius = 3.48,
    CovalentRadius = 2.42,
    ElectronAffinity = 44.38,
    Electronegativity = 0.7,
    IonizationEnergies = {
        392.96,
    },
    MeltingPointK = 294,
    BoilingPointK = 923,
    KeyIsotopes = {
        {
            Name = "223Fr",
            HalfLife = {
                "22.0 m",
            },
            Mass = 223.02,
            MassNumber = 223,
            ModeOfDecay = {
                "beta-",
                "alpha",
            },
        },
    },
    Isotopes = {
        {
            Name = "223Fr",
            HalfLife = {
                "22.0 m",
            },
            Mass = 223.02,
            MassNumber = 223,
            ModeOfDecay = {
                "beta-",
                "alpha",
            },
        },
    },
}

return Francium
