local Livermorium = {
    Name = "Livermorium",
    Symbol = "Lv",
    AtomicNumber = 116,
    AtomicMass = -293,
    RepresentativeMassNumber = 293,
    Protons = 116,
    Electrons = 116,
    NeutronsApprox = 177,
    Category = "Other",
    Group = "16",
    Period = 7,
    Block = "p",
    StateAt293K = "Solid",
    Density = 12.9,
    Appearance = {
        "A highly radioactive metal, of which only a few atoms have ever been made.",
    },
    Uses = {
        "At present, it is only used in research.",
    },
    ElectronConfiguration = "[Rn] 5f146d107s27p4",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        18,
        6,
    },
    CovalentRadius = 1.75,
    IonizationEnergies = {},
    KeyIsotopes = {
        {
            Name = "293Lv",
            HalfLife = {
                "0.06 s",
            },
            Mass = 293,
            MassNumber = 293,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
    Isotopes = {
        {
            Name = "293Lv",
            HalfLife = {
                "0.06 s",
            },
            Mass = 293,
            MassNumber = 293,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
}

return Livermorium
