local Rutherfordium = {
    Name = "Rutherfordium",
    Symbol = "Rf",
    AtomicNumber = 104,
    AtomicMass = -267,
    RepresentativeMassNumber = 265,
    Protons = 104,
    Electrons = 104,
    NeutronsApprox = 161,
    Category = "Transition",
    Group = "4",
    Period = 7,
    Block = "d",
    StateAt293K = "Solid",
    Density = 23.2,
    Appearance = {
        "A radioactive metal that does not occur naturally. Relatively few atoms have ever been made.",
    },
    Uses = {
        "At present, it is only used in research.",
    },
    ElectronConfiguration = "[Rn] 5f146d27s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        10,
        2,
    },
    CovalentRadius = 1.57,
    IonizationEnergies = {
        579,
    },
    KeyIsotopes = {
        {
            Name = "265Rf",
            HalfLife = {
                "~ 2 m",
            },
            Mass = 265.117,
            MassNumber = 265,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
    Isotopes = {
        {
            Name = "265Rf",
            HalfLife = {
                "~ 2 m",
            },
            Mass = 265.117,
            MassNumber = 265,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
}

return Rutherfordium
