local Tungsten = {
    Name = "Tungsten",
    Symbol = "W",
    AtomicNumber = 74,
    AtomicMass = 183.84,
    RepresentativeMassNumber = 182,
    Protons = 74,
    Electrons = 74,
    NeutronsApprox = 108,
    Category = "Transition",
    Group = "6",
    Period = 6,
    Block = "d",
    StateAt293K = "Solid",
    Density = 19.25,
    Appearance = {
        "A shiny, silvery-white metal.",
    },
    Uses = {
        "Tungsten was used extensively for the filaments of old-style incandescent light bulbs, but these have been phased out in many countries. This is because they are not very energy efficient; they produce much more heat than light.",
        "Tungsten has the highest melting point of all metals and is alloyed with other metals to strengthen them. Tungsten and its alloys are used in many high-temperature applications, such as arc-welding electrodes and heating elements in high-temperature furnaces.",
        "Tungsten carbide is immensely hard and is very important to the metal-working, mining and petroleum industries. It is made by mixing tungsten powder and carbon powder and heating to 2200C. It makes excellent cutting and drilling tools, including a new 'painless' dental drill which spins at ultra-high speeds.",
        "Calcium and magnesium tungstates are widely used in fluorescent lighting.",
    },
    ElectronConfiguration = "[Xe] 4f145d46s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        12,
        2,
    },
    AtomicRadius = 2.18,
    CovalentRadius = 1.5,
    ElectronAffinity = 78.757,
    Electronegativity = 1.7,
    IonizationEnergies = {
        758.764,
        1553.4,
    },
    MeltingPointK = 3687,
    BoilingPointK = 5828,
    KeyIsotopes = {
        {
            Name = "182W",
            HalfLife = {
                "> 7.7 x 1021 y",
            },
            Mass = 181.948,
            MassNumber = 182,
            ModeOfDecay = {
                "alpha",
            },
            NaturalAbundance = 26.5,
        },
        {
            Name = "184W",
            HalfLife = {
                "> 8.9 x 1021 y",
            },
            Mass = 183.951,
            MassNumber = 184,
            ModeOfDecay = {
                "alpha",
            },
            NaturalAbundance = 30.64,
        },
        {
            Name = "186W",
            HalfLife = {
                "> 8.2 x 1021 y",
            },
            Mass = 185.954,
            MassNumber = 186,
            ModeOfDecay = {
                "alpha",
            },
            NaturalAbundance = 28.43,
        },
    },
    Isotopes = {
        {
            Name = "180W",
            HalfLife = {
                "1.8 x 1018 y",
            },
            Mass = 179.947,
            MassNumber = 180,
            ModeOfDecay = {
                "alpha",
            },
            NaturalAbundance = 0.12,
        },
        {
            Name = "182W",
            HalfLife = {
                "> 7.7 x 1021 y",
            },
            Mass = 181.948,
            MassNumber = 182,
            ModeOfDecay = {
                "alpha",
            },
            NaturalAbundance = 26.5,
        },
        {
            Name = "183W",
            HalfLife = {
                "> 4.1 x 1021 y",
            },
            Mass = 182.95,
            MassNumber = 183,
            ModeOfDecay = {
                "alpha",
            },
            NaturalAbundance = 14.31,
        },
        {
            Name = "184W",
            HalfLife = {
                "> 8.9 x 1021 y",
            },
            Mass = 183.951,
            MassNumber = 184,
            ModeOfDecay = {
                "alpha",
            },
            NaturalAbundance = 30.64,
        },
        {
            Name = "186W",
            HalfLife = {
                "> 8.2 x 1021 y",
            },
            Mass = 185.954,
            MassNumber = 186,
            ModeOfDecay = {
                "alpha",
            },
            NaturalAbundance = 28.43,
        },
    },
}

return Tungsten
