local Copernicium = {
    Name = "Copernicium",
    Symbol = "Cn",
    AtomicNumber = 112,
    AtomicMass = -285,
    RepresentativeMassNumber = 285,
    Protons = 112,
    Electrons = 112,
    NeutronsApprox = 173,
    Category = "Transition",
    Group = "12",
    Period = 7,
    Block = "d",
    StateAt293K = "Solid",
    Density = 14.0,
    Appearance = {
        "A highly radioactive metal, of which only a few atoms have ever been made. It is thought to be unreactive and more like a noble gas than a metal.",
    },
    Uses = {
        "At present, it is only used in research.",
    },
    ElectronConfiguration = "[Rn] 5f146d107s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        18,
        2,
    },
    CovalentRadius = 1.22,
    IonizationEnergies = {},
    KeyIsotopes = {
        {
            Name = "285Cn",
            HalfLife = {
                "~ 29 s",
            },
            Mass = 285.177,
            MassNumber = 285,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
    Isotopes = {
        {
            Name = "285Cn",
            HalfLife = {
                "~ 29 s",
            },
            Mass = 285.177,
            MassNumber = 285,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
}

return Copernicium
