local Helium = {
    Name = "Helium",
    Symbol = "He",
    AtomicNumber = 2,
    AtomicMass = 4.0026,
    RepresentativeMassNumber = 4,
    Protons = 2,
    Electrons = 2,
    NeutronsApprox = 2,
    Category = "Noble",
    Group = "18",
    Period = 1,
    Block = "s",
    StateAt293K = "Gas",
    Density = 0.1786,
    Appearance = {
        "A colourless, odourless gas that is totally unreactive.",
    },
    Uses = {
        "Helium is used as a cooling medium for the Large Hadron Collider (LHC), and the superconducting magnets in MRI scanners and NMR spectrometers. It is also used to keep satellite instruments cool and was used to cool the liquid oxygen and hydrogen that powered the Apollo space vehicles.",
        "Because of its low density helium is often used to fill decorative balloons, weather balloons and airships. Hydrogen was once used to fill balloons but it is dangerously reactive.",
        "Because it is very unreactive, helium is used to provide an inert protective atmosphere for making fibre optics and semiconductors, and for arc welding. Helium is also used to detect leaks, such as in car air-conditioning systems, and because it diffuses quickly it is used to inflate car airbags after impact.",
        "A mixture of 80% helium and 20% oxygen is used as an artificial atmosphere for deep-sea divers and others working under pressurised conditions.",
        "Helium-neon gas lasers are used to scan barcodes in supermarket checkouts. A new use for helium is a helium-ion microscope that gives better image resolution than a scanning electron microscope.",
    },
    ElectronConfiguration = "1s2",
    EnergyLevels = {
        2,
    },
    AtomicRadius = 1.4,
    CovalentRadius = 0.37,
    IonizationEnergies = {
        2372.322,
        5250.516,
    },
    BoilingPointK = 4.222,
    KeyIsotopes = {
        {
            Name = "4He",
            HalfLife = {},
            Mass = 4.003,
            MassNumber = 4,
            ModeOfDecay = {},
            NaturalAbundance = 99.9999,
        },
    },
    Isotopes = {
        {
            Name = "3He",
            HalfLife = {},
            Mass = 3.016,
            MassNumber = 3,
            ModeOfDecay = {},
            NaturalAbundance = 0.000134,
        },
        {
            Name = "4He",
            HalfLife = {},
            Mass = 4.003,
            MassNumber = 4,
            ModeOfDecay = {},
            NaturalAbundance = 99.9999,
        },
    },
}

return Helium
