local Meitnerium = {
    Name = "Meitnerium",
    Symbol = "Mt",
    AtomicNumber = 109,
    AtomicMass = -278,
    RepresentativeMassNumber = 276,
    Protons = 109,
    Electrons = 109,
    NeutronsApprox = 167,
    Category = "Other",
    Group = "9",
    Period = 7,
    Block = "d",
    StateAt293K = "Solid",
    Density = 37.4,
    Appearance = {
        "A highly radioactive metal, of which only a few atoms have ever been made.",
    },
    Uses = {
        "At present it is only used in research.",
    },
    ElectronConfiguration = "[Rn] 5f146d77s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        15,
        2,
    },
    CovalentRadius = 1.29,
    IonizationEnergies = {},
    KeyIsotopes = {
        {
            Name = "276Mt",
            HalfLife = {
                "~ 0.7 s",
            },
            Mass = 276.152,
            MassNumber = 276,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
    Isotopes = {
        {
            Name = "276Mt",
            HalfLife = {
                "~ 0.7 s",
            },
            Mass = 276.152,
            MassNumber = 276,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
}

return Meitnerium
