local Polonium = {
    Name = "Polonium",
    Symbol = "Po",
    AtomicNumber = 84,
    AtomicMass = -209,
    RepresentativeMassNumber = 209,
    Protons = 84,
    Electrons = 84,
    NeutronsApprox = 125,
    Category = "Poor",
    Group = "16",
    Period = 6,
    Block = "p",
    StateAt293K = "Solid",
    Density = 9.196,
    Appearance = {
        "A silvery-grey, radioactive semi-metal.",
    },
    Uses = {
        "Polonium is an alpha-emitter, and is used as an alpha-particle source in the form of a thin film on a stainless steel disc. These are used in antistatic devices and for research purposes.",
        "A single gram of polonium will reach a temperature of 500C as a result of the alpha radiation emitted. This makes it useful as a source of heat for space equipment.",
        "It can be mixed or alloyed with beryllium to provide a source of neutrons.",
    },
    ElectronConfiguration = "[Xe] 4f145d106s26p4",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        6,
    },
    AtomicRadius = 1.97,
    CovalentRadius = 1.42,
    ElectronAffinity = 183.3,
    Electronegativity = 2,
    IonizationEnergies = {
        811.828,
    },
    MeltingPointK = 527,
    BoilingPointK = 1235,
    KeyIsotopes = {
        {
            Name = "209Po",
            HalfLife = {
                "128 y",
            },
            Mass = 208.982,
            MassNumber = 209,
            ModeOfDecay = {
                "alpha",
            },
        },
        {
            Name = "210Po",
            HalfLife = {
                "138.4 d",
            },
            Mass = 209.983,
            MassNumber = 210,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
    Isotopes = {
        {
            Name = "209Po",
            HalfLife = {
                "128 y",
            },
            Mass = 208.982,
            MassNumber = 209,
            ModeOfDecay = {
                "alpha",
            },
        },
        {
            Name = "210Po",
            HalfLife = {
                "138.4 d",
            },
            Mass = 209.983,
            MassNumber = 210,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
}

return Polonium
