---Material Data Module

local MaterialData = {}

MaterialData.Materials = {
	["material_0000000001"] = {
		Name = "Blue Crystal",
		Icon = "rbxassetid://140395062939287",
		Type = "Material",
		Description = "Crystals Found In The Deepest Of Rivens",
		Rarity = "Epic",
		Stackable = true,
		MaxStack = 99,	
	}
	,
	["material_0000000002"] = {
		Name = "Golden Hatchling",
		Icon = "rbxassetid://109330438455713",
		Type = "Material",
		Description = "Egg",
		Rarity = "Mythical",
		Stackable = false,
		MaxStack = 1,	
	}
	,
	["material_0000000003"] = {
		Name = "Moonlit Yolk",
		Icon = "rbxassetid://118919507831030",
		Type = "Material",
		Description = "Egg",
		Rarity = "Mythical",
		Stackable = false,
		MaxStack = 1,	
	}
	,
	["material_0000000004"] = {
		Name = "Bunny’s Secret",
		Icon = "rbxassetid://137506193400457",
		Type = "Material",
		Description = "Egg",
		Rarity = "Mythical",
		Stackable = false,
		MaxStack = 1,	
	}
	,
	["material_0000000005"] = {
		Name = "Mystic Shell",
		Icon = "rbxassetid://99294662748583",
		Type = "Material",
		Description = "Egg",
		Rarity = "Mythical",
		Stackable = false,
		MaxStack = 1,	
	}
	,
	["material_0000000006"] = {
		Name = "Choco Blossom",
		Icon = "rbxassetid://130960761046423",
		Type = "Material",
		Description = "Egg",
		Rarity = "Mythical",
		Stackable = false,
		MaxStack = 1,	
	}
}


return MaterialData
