local Actinium = {
    Appearance = "Actinium is a soft, silvery-white radioactive metal. It glows blue in the dark because its intense radioactivity excites the air around it.",
    AtomicMass = -227,
    AtomicNumber = 89,
    AtomicRadius = 2.47,
    Block = "d",
    BoilingPointK = 3473,
    Category = "Actinoid",
    CovalentRadius = 2.01,
    ElectronAffinity = 33.77,
    ElectronConfiguration = "[Rn] 6d17s2",
    Electronegativity = 1.1,
    Density = 10,
    Electrons = 89,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        9,
        2,
    },
    Group = "Actinides",
    IonizationEnergies = {
        498.83,
        1133.7,
    },
    Isotopes = {
        {
            HalfLife = {
                "21.77 y",
            },
            Mass = 227.028,
            MassNumber = 227,
            ModeOfDecay = {
                "beta-",
                "alpha",
            },
            Name = "227Ac",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "21.77 y",
            },
            Mass = 227.028,
            MassNumber = 227,
            ModeOfDecay = {
                "beta-",
                "alpha",
            },
            Name = "227Ac",
        },
    },
    MeltingPointK = 1323,
    Name = "Actinium",
    NeutronsApprox = 138,
    Period = 7,
    Protons = 89,
    RepresentativeMassNumber = 227,
    StateAt293K = "Solid",
    Symbol = "Ac",
    Uses = "Actinium is a very powerful source of alpha rays, but is rarely used outside research.",
}

return Actinium
