local Aluminium = {
    Appearance = "Aluminium is a silvery-white, lightweight metal. It is soft and malleable.",
    AtomicMass = 26.982,
    AtomicNumber = 13,
    AtomicRadius = 1.84,
    Block = "p",
    BoilingPointK = 2792,
    Category = "Poor",
    CovalentRadius = 1.24,
    ElectronAffinity = 41.762,
    ElectronConfiguration = "[Ne] 3s23p1",
    Electronegativity = 1.61,
    Density = 2.7,
    Electrons = 13,
    EnergyLevels = {
        2,
        8,
        3,
    },
    Group = "13",
    IonizationEnergies = {
        577.539,
        1816.679,
        2744.781,
        11577.469,
        14841.857,
        18379.49,
        23326.3,
        27465.52,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 26.982,
            MassNumber = 27,
            ModeOfDecay = {},
            Name = "27Al",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 26.982,
            MassNumber = 27,
            ModeOfDecay = {},
            Name = "27Al",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 933.473,
    Name = "Aluminium",
    NeutronsApprox = 14,
    Period = 3,
    Protons = 13,
    RepresentativeMassNumber = 27,
    StateAt293K = "Solid",
    Symbol = "Al",
    Uses = "Aluminium is used in a huge variety of products including cans, foils, kitchen utensils, window frames, beer kegs and aeroplane parts. This is because of its particular properties. It has low density, is non-toxic, has a high thermal conductivity, has excellent corrosion resistance and can be easily cast, machined and formed. It is also non-magnetic and non-sparking. It is the second most malleable metal and the sixth most ductile.\
\
It is often used as an alloy because aluminium itself is not particularly strong. Alloys with copper, manganese, magnesium and silicon are lightweight but strong. They are very important in the construction of aeroplanes and other forms of transport.\
\
Aluminium is a good electrical conductor and is often used in electrical transmission lines. It is cheaper than copper and weight for weight is almost twice as good a conductor.\
\
When evaporated in a vacuum, aluminium forms a highly reflective coating for both light and heat. It does not deteriorate, like a silver coating would. These aluminium coatings have many uses, including telescope mirrors, decorative paper, packages and toys.",
}

return Aluminium
