local Americium = {
    Name = "Americium",
    Symbol = "Am",
    AtomicNumber = 95,
    AtomicMass = -243,
    RepresentativeMassNumber = 241,
    Protons = 95,
    Electrons = 95,
    NeutronsApprox = 146,
    Category = "Actinoid",
    Group = "Actinides",
    Period = 7,
    Block = "f",
    StateAt293K = "Solid",
    Density = 12,
    Appearance = {
        "Americium is a silvery, shiny radioactive metal.",
    },
    Uses = {
        "Americium is commonly used in smoke alarms, but has few other uses.",
        "It has the potential to be used in spacecraft batteries in the future. Currently plutonium is used but availability is poor so alternatives are being considered.",
        "It is of interest as part of the decay sequence that occurs in nuclear power production.",
    },
    ElectronConfiguration = "[Rn] 5f77s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        25,
        8,
        2,
    },
    AtomicRadius = 2.44,
    CovalentRadius = 1.73,
    IonizationEnergies = {
        576.384,
    },
    MeltingPointK = 1449,
    BoilingPointK = 2284,
    KeyIsotopes = {
        {
            Name = "241Am",
            HalfLife = {
                "432.7 y",
                "1.2 x 1014 y",
            },
            Mass = 241.057,
            MassNumber = 241,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
        {
            Name = "243Am",
            HalfLife = {
                "7.37 x 103 y",
                "2 x 1014 y",
            },
            Mass = 243.061,
            MassNumber = 243,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
    },
    Isotopes = {
        {
            Name = "241Am",
            HalfLife = {
                "432.7 y",
                "1.2 x 1014 y",
            },
            Mass = 241.057,
            MassNumber = 241,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
        {
            Name = "243Am",
            HalfLife = {
                "7.37 x 103 y",
                "2 x 1014 y",
            },
            Mass = 243.061,
            MassNumber = 243,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
    },
}

return Americium
