local Americium = {
    Appearance = "Americium is a silvery, shiny radioactive metal.",
    AtomicMass = -243,
    AtomicNumber = 95,
    AtomicRadius = 2.44,
    Block = "f",
    BoilingPointK = 2284,
    Category = "Actinoid",
    CovalentRadius = 1.73,
    ElectronConfiguration = "[Rn] 5f77s2",
    Density = 12,
    Electrons = 95,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        25,
        8,
        2,
    },
    Group = "Actinides",
    IonizationEnergies = {
        576.384,
    },
    Isotopes = {
        {
            HalfLife = {
                "432.7 y",
                "1.2 x 1014 y",
            },
            Mass = 241.057,
            MassNumber = 241,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "241Am",
        },
        {
            HalfLife = {
                "7.37 x 103 y",
                "2 x 1014 y",
            },
            Mass = 243.061,
            MassNumber = 243,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "243Am",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "432.7 y",
                "1.2 x 1014 y",
            },
            Mass = 241.057,
            MassNumber = 241,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "241Am",
        },
        {
            HalfLife = {
                "7.37 x 103 y",
                "2 x 1014 y",
            },
            Mass = 243.061,
            MassNumber = 243,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "243Am",
        },
    },
    MeltingPointK = 1449,
    Name = "Americium",
    NeutronsApprox = 146,
    Period = 7,
    Protons = 95,
    RepresentativeMassNumber = 241,
    StateAt293K = "Solid",
    Symbol = "Am",
    Uses = "Americium is commonly used in smoke alarms, but has few other uses. \
\
It has the potential to be used in spacecraft batteries in the future. Currently plutonium is used but availability is poor so alternatives are being considered.\
\
It is of interest as part of the decay sequence that occurs in nuclear power production.",
}

return Americium
