local Antimony = {
    Appearance = "Antimony is a semi-metal. In its metallic form it is silvery, hard and brittle.",
    AtomicMass = 121.76,
    AtomicNumber = 51,
    AtomicRadius = 2.06,
    Block = "p",
    BoilingPointK = 1860,
    Category = "Metalloid",
    CovalentRadius = 1.4,
    ElectronAffinity = 100.924,
    ElectronConfiguration = "[Kr] 4d105s25p3",
    Electronegativity = 2.05,
    Density = 6.697,
    Electrons = 51,
    EnergyLevels = {
        2,
        8,
        18,
        18,
        5,
    },
    Group = "15",
    IonizationEnergies = {
        830.583,
        1604.55,
        2441.1,
        4264.7,
        5403,
        10420,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 120.904,
            MassNumber = 121,
            ModeOfDecay = {},
            Name = "121Sb",
            NaturalAbundance = 57.21,
        },
        {
            HalfLife = {},
            Mass = 122.904,
            MassNumber = 123,
            ModeOfDecay = {},
            Name = "123Sb",
            NaturalAbundance = 42.79,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 120.904,
            MassNumber = 121,
            ModeOfDecay = {},
            Name = "121Sb",
            NaturalAbundance = 57.21,
        },
    },
    MeltingPointK = 903.778,
    Name = "Antimony",
    NeutronsApprox = 70,
    Period = 5,
    Protons = 51,
    RepresentativeMassNumber = 121,
    StateAt293K = "Solid",
    Symbol = "Sb",
    Uses = "Antimony is used in the electronics industry to make some semiconductor devices, such as infrared detectors and diodes. \
\
It is alloyed with lead or other metals to improve their hardness and strength. A lead-antimony alloy is used in batteries. Other uses of antimony alloys include type metal (in printing presses), bullets and cable sheathing. \
\
Antimony compounds are used to make flame-retardant materials, paints, enamels, glass and pottery.",
}

return Antimony
