local Argon = {
    Appearance = "Argon is a colourless, odourless gas that is totally inert to other substances.",
    AtomicMass = 39.948,
    AtomicNumber = 18,
    AtomicRadius = 1.88,
    Block = "p",
    BoilingPointK = 87.302,
    Category = "Noble",
    CovalentRadius = 1.01,
    ElectronConfiguration = "[Ne] 3s23p6",
    Density = 1.784,
    Electrons = 18,
    EnergyLevels = {
        2,
        8,
        8,
    },
    Group = "18",
    IonizationEnergies = {
        1520.571,
        2665.857,
        3930.81,
        5770.79,
        7238.33,
        8781.034,
        11995.347,
        13841.79,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 35.968,
            MassNumber = 36,
            ModeOfDecay = {},
            Name = "36Ar",
            NaturalAbundance = 0.3336,
        },
        {
            HalfLife = {},
            Mass = 37.963,
            MassNumber = 38,
            ModeOfDecay = {},
            Name = "38Ar",
            NaturalAbundance = 0.0629,
        },
        {
            HalfLife = {},
            Mass = 39.962,
            MassNumber = 40,
            ModeOfDecay = {},
            Name = "40Ar",
            NaturalAbundance = 99.6035,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 39.962,
            MassNumber = 40,
            ModeOfDecay = {},
            Name = "40Ar",
            NaturalAbundance = 99.6035,
        },
    },
    MeltingPointK = 83.81,
    Name = "Argon",
    NeutronsApprox = 22,
    Period = 3,
    Protons = 18,
    RepresentativeMassNumber = 40,
    StateAt293K = "Gas",
    Symbol = "Ar",
    Uses = "Argon is often used when an inert atmosphere is needed. It is used in this way for the production of titanium and other reactive elements. It is also used by welders to protect the weld area and in incandescent light bulbs to stop oxygen from corroding the filament. \
\
Argon is used in fluorescent tubes and low-energy light bulbs. A low-energy light bulb often contains argon gas and mercury. When it is switched on an electric discharge passes through the gas, generating UV light. The coating on the inside surface of the bulb is activated by the UV light and it glows brightly. \
\
Double-glazed windows use argon to fill the space between the panes. The tyres of luxury cars can contain argon to protect the rubber and reduce road noise.",
}

return Argon
