local Arsenic = {
    Appearance = "Arsenic is a semi-metal. In its metallic form it is bright, silver-grey and brittle.",
    AtomicMass = 74.922,
    AtomicNumber = 33,
    AtomicRadius = 1.85,
    Block = "p",
    Category = "Metalloid",
    CovalentRadius = 1.2,
    ElectronAffinity = 77.574,
    ElectronConfiguration = "[Ar] 3d104s24p3",
    Electronegativity = 2.18,
    Density = 5.727,
    Electrons = 33,
    EnergyLevels = {
        2,
        8,
        18,
        5,
    },
    Group = "15",
    IonizationEnergies = {
        944.456,
        1793.585,
        2735.456,
        4836.81,
        6042.88,
        12311.5,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 74.922,
            MassNumber = 75,
            ModeOfDecay = {},
            Name = "75As",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 74.922,
            MassNumber = 75,
            ModeOfDecay = {},
            Name = "75As",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 889,
    Name = "Arsenic",
    NeutronsApprox = 42,
    Period = 4,
    Protons = 33,
    RepresentativeMassNumber = 75,
    StateAt293K = "Solid",
    Symbol = "As",
    Uses = "Arsenic is a well-known poison. Arsenic compounds are sometimes used as rat poisons and insecticides but their use is strictly controlled. \
\
Surprisingly, arsenic can also have medicinal applications. In Victorian times, Dr Fowler's Solution (potassium arsenate dissolved in water) was a popular cure-all tonic that was even used by Charles Dickens. Today, organoarsenic compounds are added to poultry feed to prevent disease and improve weight gain.\
\
Arsenic is used as a doping agent in semiconductors (gallium arsenide) for solid-state devices. It is also used in bronzing, pyrotechnics and for hardening shot. \
\
Arsenic compounds can be used to make special glass and preserve wood.",
}

return Arsenic
