local Astatine = {
    Appearance = "Astatine is a dangerously radioactive element.",
    AtomicMass = -210,
    AtomicNumber = 85,
    AtomicRadius = 2.02,
    Block = "p",
    BoilingPointK = 623,
    Category = "Metalloid",
    CovalentRadius = 1.48,
    ElectronAffinity = 270.2,
    ElectronConfiguration = "[Xe] 4f145d106s26p5",
    Electronegativity = 2.2,
    Density = 6.35,
    Electrons = 85,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        7,
    },
    Group = "17",
    IonizationEnergies = {},
    Isotopes = {
        {
            HalfLife = {
                "8.1 h",
            },
            Mass = 209.987,
            MassNumber = 210,
            ModeOfDecay = {
                "EC",
                "alpha",
            },
            Name = "210At",
        },
        {
            HalfLife = {
                "7.21 h",
            },
            Mass = 210.987,
            MassNumber = 211,
            ModeOfDecay = {
                "EC",
                "alpha",
            },
            Name = "211At",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "8.1 h",
            },
            Mass = 209.987,
            MassNumber = 210,
            ModeOfDecay = {
                "EC",
                "alpha",
            },
            Name = "210At",
        },
        {
            HalfLife = {
                "7.21 h",
            },
            Mass = 210.987,
            MassNumber = 211,
            ModeOfDecay = {
                "EC",
                "alpha",
            },
            Name = "211At",
        },
    },
    MeltingPointK = 573,
    Name = "Astatine",
    NeutronsApprox = 125,
    Period = 6,
    Protons = 85,
    RepresentativeMassNumber = 210,
    StateAt293K = "Solid",
    Symbol = "At",
    Uses = "There are currently no uses for astatine outside of research. The half-life of the most stable isotope is only 8 hours, and only tiny amounts have ever been produced. \
\
A mass spectrometer has been used to confirm that astatine behaves chemically like other halogens, particularly iodine.",
}

return Astatine
