local Astatine = {
    Name = "Astatine",
    Symbol = "At",
    AtomicNumber = 85,
    AtomicMass = -210,
    RepresentativeMassNumber = 210,
    Protons = 85,
    Electrons = 85,
    NeutronsApprox = 125,
    Category = "Metalloid",
    Group = "17",
    Period = 6,
    Block = "p",
    StateAt293K = "Solid",
    Density = 6.35,
    Appearance = "Astatine is a dangerously radioactive element.",
    Uses = {
        "There are currently no uses for astatine outside of research. The half-life of the most stable isotope is only 8 hours, and only tiny amounts have ever been produced.",
        "A mass spectrometer has been used to confirm that astatine behaves chemically like other halogens, particularly iodine.",
    },
    ElectronConfiguration = "[Xe] 4f145d106s26p5",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        7,
    },
    AtomicRadius = 2.02,
    CovalentRadius = 1.48,
    ElectronAffinity = 270.2,
    Electronegativity = 2.2,
    IonizationEnergies = {},
    MeltingPointK = 573,
    BoilingPointK = 623,
    KeyIsotopes = {
        {
            Name = "210At",
            HalfLife = {
                "8.1 h",
            },
            Mass = 209.987,
            MassNumber = 210,
            ModeOfDecay = {
                "EC",
                "alpha",
            },
        },
        {
            Name = "211At",
            HalfLife = {
                "7.21 h",
            },
            Mass = 210.987,
            MassNumber = 211,
            ModeOfDecay = {
                "EC",
                "alpha",
            },
        },
    },
    Isotopes = {
        {
            Name = "210At",
            HalfLife = {
                "8.1 h",
            },
            Mass = 209.987,
            MassNumber = 210,
            ModeOfDecay = {
                "EC",
                "alpha",
            },
        },
        {
            Name = "211At",
            HalfLife = {
                "7.21 h",
            },
            Mass = 210.987,
            MassNumber = 211,
            ModeOfDecay = {
                "EC",
                "alpha",
            },
        },
    },
}

return Astatine
