local Barium = {
    Appearance = "Barium is a soft, silvery metal that rapidly tarnishes in air and reacts with water.",
    AtomicMass = 137.33,
    AtomicNumber = 56,
    AtomicRadius = 2.68,
    Block = "s",
    BoilingPointK = 2118,
    Category = "Alkaline",
    CovalentRadius = 2.06,
    ElectronAffinity = 13.954,
    ElectronConfiguration = "[Xe] 6s2",
    Electronegativity = 0.89,
    Density = 3.51,
    Electrons = 56,
    EnergyLevels = {
        2,
        8,
        18,
        18,
        8,
        2,
    },
    Group = "2",
    IonizationEnergies = {
        502.849,
        965.223,
    },
    Isotopes = {
        {
            HalfLife = {
                "2.2 x 1021 y",
            },
            Mass = 129.906,
            MassNumber = 130,
            ModeOfDecay = {
                "beta+beta+",
            },
            Name = "130Ba",
            NaturalAbundance = 0.106,
        },
        {
            HalfLife = {
                "1.3 x 1021 y",
            },
            Mass = 131.905,
            MassNumber = 132,
            ModeOfDecay = {
                "EC EC",
            },
            Name = "132Ba",
            NaturalAbundance = 0.101,
        },
        {
            HalfLife = {},
            Mass = 133.905,
            MassNumber = 134,
            ModeOfDecay = {},
            Name = "134Ba",
            NaturalAbundance = 2.417,
        },
        {
            HalfLife = {},
            Mass = 134.906,
            MassNumber = 135,
            ModeOfDecay = {},
            Name = "135Ba",
            NaturalAbundance = 6.592,
        },
        {
            HalfLife = {},
            Mass = 135.905,
            MassNumber = 136,
            ModeOfDecay = {},
            Name = "136Ba",
            NaturalAbundance = 7.854,
        },
        {
            HalfLife = {},
            Mass = 136.906,
            MassNumber = 137,
            ModeOfDecay = {},
            Name = "137Ba",
            NaturalAbundance = 11.232,
        },
        {
            HalfLife = {},
            Mass = 137.905,
            MassNumber = 138,
            ModeOfDecay = {},
            Name = "138Ba",
            NaturalAbundance = 71.698,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 137.905,
            MassNumber = 138,
            ModeOfDecay = {},
            Name = "138Ba",
            NaturalAbundance = 71.698,
        },
    },
    MeltingPointK = 1000,
    Name = "Barium",
    NeutronsApprox = 82,
    Period = 6,
    Protons = 56,
    RepresentativeMassNumber = 138,
    StateAt293K = "Solid",
    Symbol = "Ba",
    Uses = "Barium is not an extensively used element. Most is used in drilling fluids for oil and gas wells. It is also used in paint and in glassmaking.\
\
All barium compounds are toxic; however, barium sulfate is insoluble and so can be safely swallowed. A suspension of barium sulfate is sometimes given to patients suffering from digestive disorders. This is a  'barium meal' or 'barium enema'. Barium is a heavy element and scatters X-rays, so as it passes through the body the stomach and intestines can be distinguished on an X-ray. \
\
Barium carbonate has been used in the past as a rat poison. Barium nitrate gives fireworks a green colour.",
}

return Barium
