local Berkelium = {
    Appearance = "Berkelium is a radioactive, silvery metal.",
    AtomicMass = -247,
    AtomicNumber = 97,
    AtomicRadius = 2.44,
    Block = "f",
    Category = "Actinoid",
    CovalentRadius = 1.68,
    ElectronConfiguration = "[Rn] 5f97s2",
    Density = 14.78,
    Electrons = 97,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        27,
        8,
        2,
    },
    Group = "Actinides",
    IonizationEnergies = {
        598.007,
    },
    Isotopes = {
        {
            HalfLife = {
                "1.43 x 103 y",
            },
            Mass = 247.07,
            MassNumber = 247,
            ModeOfDecay = {
                "alpha",
            },
            Name = "247Bk",
        },
        {
            HalfLife = {
                "320 d",
                nil,
                "1.8 x 109 y",
            },
            Mass = 249.075,
            MassNumber = 249,
            ModeOfDecay = {
                "beta",
                "alpha",
                "sf",
            },
            Name = "249Bk",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "1.43 x 103 y",
            },
            Mass = 247.07,
            MassNumber = 247,
            ModeOfDecay = {
                "alpha",
            },
            Name = "247Bk",
        },
        {
            HalfLife = {
                "320 d",
                nil,
                "1.8 x 109 y",
            },
            Mass = 249.075,
            MassNumber = 249,
            ModeOfDecay = {
                "beta",
                "alpha",
                "sf",
            },
            Name = "249Bk",
        },
    },
    MeltingPointK = 1259,
    Name = "Berkelium",
    NeutronsApprox = 150,
    Period = 7,
    Protons = 97,
    RepresentativeMassNumber = 247,
    StateAt293K = "Solid",
    Symbol = "Bk",
    Uses = "Because it is so rare, berkelium has no commercial or technological use at present.",
}

return Berkelium
