local Beryllium = {
    Appearance = "Beryllium is a silvery-white metal. It is relatively soft and has a low density.",
    AtomicMass = 9.0122,
    AtomicNumber = 4,
    AtomicRadius = 1.53,
    Block = "s",
    BoilingPointK = 2741,
    Category = "Alkaline",
    CovalentRadius = 0.99,
    ElectronConfiguration = "[He] 2s2",
    Electronegativity = 1.57,
    Density = 1.85,
    Electrons = 4,
    EnergyLevels = {
        2,
        2,
    },
    Group = "2",
    IonizationEnergies = {
        899.504,
        1757.108,
        14848.767,
        21006.658,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 9.012,
            MassNumber = 9,
            ModeOfDecay = {},
            Name = "9Be",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 9.012,
            MassNumber = 9,
            ModeOfDecay = {},
            Name = "9Be",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 1560,
    Name = "Beryllium",
    NeutronsApprox = 5,
    Period = 2,
    Protons = 4,
    RepresentativeMassNumber = 9,
    StateAt293K = "Solid",
    Symbol = "Be",
    Uses = "Beryllium is used in alloys with copper or nickel to make gyroscopes, springs, electrical contacts, spot-welding electrodes and non-sparking tools. Mixing beryllium with these metals increases their electrical and thermal conductivity.  \
\
Other beryllium alloys are used as structural materials for high-speed aircraft, missiles, spacecraft and communication satellites. \
\
Beryllium is relatively transparent to X-rays so ultra-thin beryllium foil is finding use in X-ray lithography. Beryllium is also used in nuclear reactors as a reflector or moderator of neutrons. \
\
The oxide has a very high melting point making it useful in nuclear work as well as having ceramic applications.",
}

return Beryllium
