local Bismuth = {
    Appearance = "Bismuth is a high-density, silvery, pink-tinged metal.",
    AtomicMass = 208.98,
    AtomicNumber = 83,
    AtomicRadius = 2.07,
    Block = "p",
    BoilingPointK = 1837,
    Category = "Poor",
    CovalentRadius = 1.5,
    ElectronAffinity = 90.924,
    ElectronConfiguration = "[Xe] 4f145d106s26p3",
    Electronegativity = 1.9,
    Density = 9.78,
    Electrons = 83,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        5,
    },
    Group = "15",
    IonizationEnergies = {
        702.944,
        1611.595,
        2466.17,
        4370.8,
        5403,
        8519.7,
    },
    Isotopes = {
        {
            HalfLife = {
                "1.9 x 1019 y",
            },
            Mass = 208.98,
            MassNumber = 209,
            ModeOfDecay = {
                "alpha",
            },
            Name = "209Bi",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "1.9 x 1019 y",
            },
            Mass = 208.98,
            MassNumber = 209,
            ModeOfDecay = {
                "alpha",
            },
            Name = "209Bi",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 544.556,
    Name = "Bismuth",
    NeutronsApprox = 126,
    Period = 6,
    Protons = 83,
    RepresentativeMassNumber = 209,
    StateAt293K = "Solid",
    Symbol = "Bi",
    Uses = "Bismuth metal is brittle and so it is usually mixed with other metals to make it useful. Its alloys with tin or cadmium have low melting points and are used in fire detectors and extinguishers, electric fuses and solders.\
\
Bismuth oxide is used as a yellow pigment for cosmetics and paints, while bismuth(III) chloride oxide (BiClO) gives a pearly effect to cosmetics. Basic bismuth carbonate is taken in tablet or liquid form for indigestion as 'bismuth mixture'.",
}

return Bismuth
