local Bohrium = {
    Appearance = "Bohrium is a highly radioactive metal.",
    AtomicMass = -270,
    AtomicNumber = 107,
    Block = "d",
    Category = "Transition",
    CovalentRadius = 1.41,
    ElectronConfiguration = "[Rn] 5f146d57s2",
    Density = 37.1,
    Electrons = 107,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        13,
        2,
    },
    Group = "7",
    IonizationEnergies = {},
    Isotopes = {
        {
            HalfLife = {
                "~ 10 s",
            },
            Mass = 272.138,
            MassNumber = 272,
            ModeOfDecay = {
                "alpha",
            },
            Name = "272Bh",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "~ 10 s",
            },
            Mass = 272.138,
            MassNumber = 272,
            ModeOfDecay = {
                "alpha",
            },
            Name = "272Bh",
        },
    },
    Name = "Bohrium",
    NeutronsApprox = 165,
    Period = 7,
    Protons = 107,
    RepresentativeMassNumber = 272,
    StateAt293K = "Solid",
    Symbol = "Bh",
    Uses = "At present, bohrium is of research interest only.",
}

return Bohrium
