local Bohrium = {
    Name = "Bohrium",
    Symbol = "Bh",
    AtomicNumber = 107,
    AtomicMass = -270,
    RepresentativeMassNumber = 272,
    Protons = 107,
    Electrons = 107,
    NeutronsApprox = 165,
    Category = "Transition",
    Group = "7",
    Period = 7,
    Block = "d",
    StateAt293K = "Solid",
    Density = 37.1,
    Appearance = "Bohrium is a highly radioactive metal.",
    Uses = {
        "At present, bohrium is of research interest only.",
    },
    ElectronConfiguration = "[Rn] 5f146d57s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        13,
        2,
    },
    CovalentRadius = 1.41,
    IonizationEnergies = {},
    KeyIsotopes = {
        {
            Name = "272Bh",
            HalfLife = {
                "~ 10 s",
            },
            Mass = 272.138,
            MassNumber = 272,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
    Isotopes = {
        {
            Name = "272Bh",
            HalfLife = {
                "~ 10 s",
            },
            Mass = 272.138,
            MassNumber = 272,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
}

return Bohrium
