local Boron = {
    Appearance = "Pure boron is a dark amorphous powder.",
    AtomicMass = 10.81,
    AtomicNumber = 5,
    AtomicRadius = 1.92,
    Block = "p",
    BoilingPointK = 4273,
    Category = "Metalloid",
    CovalentRadius = 0.84,
    ElectronAffinity = 26.989,
    ElectronConfiguration = "[He] 2s22p1",
    Electronegativity = 2.04,
    Density = 2.08,
    Electrons = 5,
    EnergyLevels = {
        2,
        3,
    },
    Group = "13",
    IonizationEnergies = {
        800.637,
        2427.069,
        3659.751,
        25025.905,
        32826.802,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 10.013,
            MassNumber = 10,
            ModeOfDecay = {},
            Name = "10B",
            NaturalAbundance = 19.9,
        },
        {
            HalfLife = {},
            Mass = 11.009,
            MassNumber = 11,
            ModeOfDecay = {},
            Name = "11B",
            NaturalAbundance = 80.1,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 11.009,
            MassNumber = 11,
            ModeOfDecay = {},
            Name = "11B",
            NaturalAbundance = 80.1,
        },
    },
    MeltingPointK = 2350,
    Name = "Boron",
    NeutronsApprox = 6,
    Period = 2,
    Protons = 5,
    RepresentativeMassNumber = 11,
    StateAt293K = "Solid",
    Symbol = "B",
    Uses = "Amorphous boron is used as a rocket fuel igniter and in pyrotechnic flares. It gives the flares a distinctive green colour.\
\
The most important compounds of boron are boric (or boracic) acid, borax (sodium borate) and boric oxide. These can be found in eye drops, mild antiseptics, washing powders and tile glazes. Borax used to be used to make bleach and as a food preservative.\
\
Boric oxide is also commonly used in the manufacture of borosilicate glass (Pyrex). It makes the glass tough and heat resistant. Fibreglass textiles and insulation are made from borosilcate glass. \
\
Sodium octaborate is a flame retardant.\
\
The isotope boron-10 is good at absorbing neutrons. This means it can be used to regulate nuclear reactors. It also has a role in instruments used to detect neutrons.",
}

return Boron
