local Cadmium = {
    Appearance = "Cadmium is a silvery metal with a bluish tinge to its surface.",
    AtomicMass = 112.41,
    AtomicNumber = 48,
    AtomicRadius = 2.18,
    Block = "d",
    BoilingPointK = 1040,
    Category = "Transition",
    CovalentRadius = 1.4,
    ElectronConfiguration = "[Kr] 4d105s2",
    Electronegativity = 1.69,
    Density = 8.65,
    Electrons = 48,
    EnergyLevels = {
        2,
        8,
        18,
        18,
        2,
    },
    Group = "12",
    IonizationEnergies = {
        867.772,
        1631.404,
        3616.27,
    },
    Isotopes = {
        {
            HalfLife = {
                "> 1.9 x 1019 y",
            },
            Mass = 105.906,
            MassNumber = 106,
            ModeOfDecay = {
                "EC, EC",
            },
            Name = "106Cd",
            NaturalAbundance = 1.25,
        },
        {
            HalfLife = {
                "> 4.1 x 1017 y",
            },
            Mass = 107.904,
            MassNumber = 108,
            ModeOfDecay = {
                "EC EC",
            },
            Name = "108Cd",
            NaturalAbundance = 0.89,
        },
        {
            HalfLife = {},
            Mass = 109.903,
            MassNumber = 110,
            ModeOfDecay = {},
            Name = "110Cd",
            NaturalAbundance = 12.49,
        },
        {
            HalfLife = {},
            Mass = 110.904,
            MassNumber = 111,
            ModeOfDecay = {},
            Name = "111Cd",
            NaturalAbundance = 12.8,
        },
        {
            HalfLife = {},
            Mass = 111.903,
            MassNumber = 112,
            ModeOfDecay = {},
            Name = "112Cd",
            NaturalAbundance = 24.13,
        },
        {
            HalfLife = {
                "8.04 x 1015 y",
            },
            Mass = 112.904,
            MassNumber = 113,
            ModeOfDecay = {
                "beta-beta-",
            },
            Name = "113Cd",
            NaturalAbundance = 12.22,
        },
        {
            HalfLife = {
                "> 1.3 x 1018 y",
            },
            Mass = 113.903,
            MassNumber = 114,
            ModeOfDecay = {
                "beta-beta-",
            },
            Name = "114Cd",
            NaturalAbundance = 28.73,
        },
        {
            HalfLife = {
                "3.8 x 1019 y",
            },
            Mass = 115.905,
            MassNumber = 116,
            ModeOfDecay = {
                "beta-beta-",
            },
            Name = "116Cd",
            NaturalAbundance = 7.49,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "> 1.3 x 1018 y",
            },
            Mass = 113.903,
            MassNumber = 114,
            ModeOfDecay = {
                "beta-beta-",
            },
            Name = "114Cd",
            NaturalAbundance = 28.73,
        },
    },
    MeltingPointK = 594.219,
    Name = "Cadmium",
    NeutronsApprox = 66,
    Period = 5,
    Protons = 48,
    RepresentativeMassNumber = 114,
    StateAt293K = "Solid",
    Symbol = "Cd",
    Uses = "Cadmium is a poison and is known to cause birth defects and cancer. As a result, there are moves to limit its use. \
\
80% of cadmium currently produced is used in rechargeable nickel-cadmium batteries. However, they are gradually being phased out and replaced with nickel metal hydride batteries. \
\
Cadmium was often used to electroplate steel and protect it from corrosion. It is still used today to protect critical components of aeroplanes and oil platforms.\
\
Other past uses of cadmium included phosphors in cathode ray tube colour TV sets, and yellow, orange and red pigments. \
\
Cadmium absorbs neutrons and so is used in rods in nuclear reactors to control atomic fission.",
}

return Cadmium
