local Caesium = {
    Appearance = "Caesium is a soft, gold-coloured metal that is quickly attacked by air and reacts explosively in water.",
    AtomicMass = 132.91,
    AtomicNumber = 55,
    AtomicRadius = 3.43,
    Block = "s",
    BoilingPointK = 944,
    Category = "Alkali",
    CovalentRadius = 2.38,
    ElectronAffinity = 45.505,
    ElectronConfiguration = "[Xe] 6s1",
    Electronegativity = 0.79,
    Density = 1.93,
    Electrons = 55,
    EnergyLevels = {
        2,
        8,
        18,
        18,
        8,
        1,
    },
    Group = "1",
    IonizationEnergies = {
        375.705,
        2234.353,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 132.905,
            MassNumber = 133,
            ModeOfDecay = {},
            Name = "133Cs",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 132.905,
            MassNumber = 133,
            ModeOfDecay = {},
            Name = "133Cs",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 301.7,
    Name = "Caesium",
    NeutronsApprox = 78,
    Period = 6,
    Protons = 55,
    RepresentativeMassNumber = 133,
    StateAt293K = "Solid",
    Symbol = "Cs",
    Uses = "The most common use for caesium compounds is as a drilling fluid. They are also used to make special optical glass, as a catalyst promoter, in vacuum tubes and in radiation monitoring equipment.\
\
One of its most important uses is in the 'caesium clock' (atomic clock). These clocks are a vital part of the internetand mobile phone networks, as well as Global Positioning System (GPS) satellites. They give the standard measure of time: the electron resonance frequency of the caesium atom is 9,192,631,770 cycles per second. Some caesium clocks are accurate to 1 second in 15 million years.",
}

return Caesium
