local Californium = {
    Appearance = "Californium is a radioactive metal.",
    AtomicMass = -251,
    AtomicNumber = 98,
    AtomicRadius = 2.45,
    Block = "f",
    Category = "Actinoid",
    CovalentRadius = 1.68,
    ElectronConfiguration = "[Rn] 5f107s2",
    Density = 15.1,
    Electrons = 98,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        28,
        8,
        2,
    },
    Group = "Actinides",
    IonizationEnergies = {
        606.092,
        1138.5,
    },
    Isotopes = {
        {
            HalfLife = {
                "351 y",
                "8 x 1010 y",
            },
            Mass = 249.075,
            MassNumber = 249,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "249Cf",
        },
        {
            HalfLife = {
                "13.1 y",
                "1.7 x 104 y",
            },
            Mass = 250.076,
            MassNumber = 250,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "250Cf",
        },
        {
            HalfLife = {
                "9 x 102 y",
            },
            Mass = 251.08,
            MassNumber = 251,
            ModeOfDecay = {
                "alpha",
            },
            Name = "251Cf",
        },
        {
            HalfLife = {
                "2.65 y",
                "86 y",
            },
            Mass = 252.082,
            MassNumber = 252,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "252Cf",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "351 y",
                "8 x 1010 y",
            },
            Mass = 249.075,
            MassNumber = 249,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "249Cf",
        },
        {
            HalfLife = {
                "2.65 y",
                "86 y",
            },
            Mass = 252.082,
            MassNumber = 252,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "252Cf",
        },
    },
    MeltingPointK = 1173,
    Name = "Californium",
    NeutronsApprox = 151,
    Period = 7,
    Protons = 98,
    RepresentativeMassNumber = 249,
    StateAt293K = "Solid",
    Symbol = "Cf",
    Uses = "Californium is a very strong neutron emitter. It is used in portable metal detectors, for identifying gold and silver ores, to identify water and oil layers in oil wells and to detect metal fatigue and stress in aeroplanes.",
}

return Californium
