local Carbon = {
    Appearance = "There are a number of pure forms of this element including graphite, diamond, fullerenes and graphene. \
\
Diamond is a colourless, transparent, crystalline solid and the hardest known material. Graphite is black and shiny but soft. The nano-forms, fullerenes and graphene, appear as black or dark brown, soot-like powders.",
    AtomicMass = 12.011,
    AtomicNumber = 6,
    AtomicRadius = 1.7,
    Block = "p",
    Category = "Nonmetal",
    CovalentRadius = 0.75,
    ElectronAffinity = 121.776,
    ElectronConfiguration = "[He] 2s22p2",
    Electronegativity = 2.55,
    Density = 1.821,
    Electrons = 6,
    EnergyLevels = {
        2,
        4,
    },
    Group = "14",
    IonizationEnergies = {
        1086.454,
        2352.631,
        4620.471,
        6222.716,
        37830.648,
        47277.174,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 12,
            MassNumber = 12,
            ModeOfDecay = {},
            Name = "12C",
            NaturalAbundance = 98.93,
        },
        {
            HalfLife = {},
            Mass = 13.003,
            MassNumber = 13,
            ModeOfDecay = {},
            Name = "13C",
            NaturalAbundance = 1.07,
        },
        {
            HalfLife = {
                "5715 y",
            },
            Mass = 14.003,
            MassNumber = 14,
            ModeOfDecay = {
                "beta-",
            },
            Name = "14C",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 12,
            MassNumber = 12,
            ModeOfDecay = {},
            Name = "12C",
            NaturalAbundance = 98.93,
        },
        {
            HalfLife = {},
            Mass = 13.003,
            MassNumber = 13,
            ModeOfDecay = {},
            Name = "13C",
            NaturalAbundance = 1.07,
        },
        {
            HalfLife = {
                "5715 y",
            },
            Mass = 14.003,
            MassNumber = 14,
            ModeOfDecay = {
                "beta-",
            },
            Name = "14C",
        },
    },
    MeltingPointK = 4098,
    Name = "Carbon",
    NeutronsApprox = 6,
    Period = 2,
    Protons = 6,
    RepresentativeMassNumber = 12,
    StateAt293K = "Solid",
    Symbol = "C",
    Uses = "Carbon is unique among the elements in its ability to form strongly bonded chains, sealed off by hydrogen atoms. These hydrocarbons, extracted naturally as fossil fuels (coal, oil and natural gas), are mostly used as fuels. A small but important fraction is used as a feedstock for the petrochemical industries producing polymers, fibres, paints, solvents and plastics etc. \
\
Impure carbon in the form of charcoal (from wood) and coke (from coal) is used in metal smelting. It is particularly important in the iron and steel industries. \
\
Graphite is used in pencils, to make brushes in electric motors and in furnace linings. Activated charcoal is used for purification and filtration. It is found in respirators and kitchen extractor hoods. \
\
Carbon fibre is finding many uses as a very strong, yet lightweight, material. It is currently used in tennis rackets, skis, fishing rods, rockets and aeroplanes.\
\
Industrial diamonds are used for cutting rocks and drilling. Diamond films are used to protect surfaces such as razor blades.\
\
The more recent discovery of carbon nanotubes, other fullerenes and atom-thin sheets of graphene has revolutionised hardware developments in the electronics industry and in nanotechnology generally.\
\
150 years ago the natural concentration of carbon dioxide in the Earth's atmosphere was 280 ppm. In 2013, as a result of combusting fossil fuels with oxygen, there was 390 ppm. Atmospheric carbon dioxide allows visible light in but prevents some infrared escaping (the natural greenhouse effect). This keeps the Earth warm enough to sustain life. However, an enhanced greenhouse effect is underway, due to a human-induced rise in atmospheric carbon dioxide. This is affecting living things as our climate changes.",
}

return Carbon
