local Chromium = {
    Appearance = "A hard, silvery metal with a blue tinge.",
    AtomicMass = 51.996,
    AtomicNumber = 24,
    AtomicRadius = 2.06,
    Block = "d",
    BoilingPointK = 2944,
    Category = "Transition",
    CovalentRadius = 1.3,
    ElectronAffinity = 64.259,
    ElectronConfiguration = "[Ar] 3d54s1",
    Electronegativity = 1.66,
    Density = 7.19,
    Electrons = 24,
    EnergyLevels = {
        2,
        8,
        13,
        1,
    },
    Group = "6",
    IonizationEnergies = {
        652.869,
        1590.628,
        2987.19,
        4743.22,
        6701.87,
        8744.939,
        15455.02,
        17820.8,
    },
    Isotopes = {
        {
            HalfLife = {
                "> 1.3 x 1018 y",
            },
            Mass = 49.946,
            MassNumber = 50,
            ModeOfDecay = {
                "beta+EC",
            },
            Name = "50Cr",
            NaturalAbundance = 4.345,
        },
        {
            HalfLife = {},
            Mass = 51.941,
            MassNumber = 52,
            ModeOfDecay = {},
            Name = "52Cr",
            NaturalAbundance = 83.789,
        },
        {
            HalfLife = {},
            Mass = 52.941,
            MassNumber = 53,
            ModeOfDecay = {},
            Name = "53Cr",
            NaturalAbundance = 9.501,
        },
        {
            HalfLife = {},
            Mass = 53.939,
            MassNumber = 54,
            ModeOfDecay = {},
            Name = "54Cr",
            NaturalAbundance = 2.365,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 51.941,
            MassNumber = 52,
            ModeOfDecay = {},
            Name = "52Cr",
            NaturalAbundance = 83.789,
        },
    },
    MeltingPointK = 2180,
    Name = "Chromium",
    NeutronsApprox = 28,
    Period = 4,
    Protons = 24,
    RepresentativeMassNumber = 52,
    StateAt293K = "Solid",
    Symbol = "Cr",
    Uses = "Chromium is used to harden steel, to manufacture stainless steel (named as it won't rust) and to produce several alloys. \
\
Chromium plating can be used to give a polished mirror finish to steel. Chromium-plated car and lorry parts, such as bumpers, were once very common. It is also possible to chromium plate plastics, which are often used in bathroom fittings.\
\
About 90% of all leather is tanned using chrome. However, the waste effluent is toxic so alternatives are being investigated.\
\
Chromium compounds are used as industrial catalysts and pigments (in bright green, yellow, red and orange colours). Rubies get their red colour from chromium, and glass treated with chromium has an emerald green colour.",
}

return Chromium
