local Cobalt = {
    Appearance = "A lustrous, silvery-blue metal. It is magnetic.",
    AtomicMass = 58.933,
    AtomicNumber = 27,
    AtomicRadius = 2,
    Block = "d",
    BoilingPointK = 3200,
    Category = "Transition",
    CovalentRadius = 1.18,
    ElectronAffinity = 63.873,
    ElectronConfiguration = "[Ar] 3d74s2",
    Electronegativity = 1.88,
    Density = 8.9,
    Electrons = 27,
    EnergyLevels = {
        2,
        8,
        15,
        2,
    },
    Group = "9",
    IonizationEnergies = {
        760.402,
        1648.356,
        3232.3,
        4949.7,
        7670.6,
        9842,
        12437,
        15225.4,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 58.933,
            MassNumber = 59,
            ModeOfDecay = {},
            Name = "59Co",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 58.933,
            MassNumber = 59,
            ModeOfDecay = {},
            Name = "59Co",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 1768,
    Name = "Cobalt",
    NeutronsApprox = 32,
    Period = 4,
    Protons = 27,
    RepresentativeMassNumber = 59,
    StateAt293K = "Solid",
    Symbol = "Co",
    Uses = "Cobalt, like iron, can be magnetised and so is used to make magnets. It is alloyed with aluminium and nickel to make particularly powerful magnets.\
\
Other alloys of cobalt are used in jet turbines and gas turbine generators, where high-temperature strength is important.\
\
Cobalt metal is sometimes used in electroplating because of its attractive appearance, hardness and resistance to corrosion. \
\
Cobalt salts have been used for centuries to produce brilliant blue colours in paint, porcelain, glass, pottery and enamels. \
\
Radioactive cobalt-60 is used to treat cancer and, in some countries, to irradiate food to preserve it.",
}

return Cobalt
