local Copernicium = {
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made. It is thought to be unreactive and more like a noble gas than a metal.",
    AtomicMass = -285,
    AtomicNumber = 112,
    Block = "d",
    Category = "Transition",
    CovalentRadius = 1.22,
    ElectronConfiguration = "[Rn] 5f146d107s2",
    Density = 14.0,
    Electrons = 112,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        18,
        2,
    },
    Group = "12",
    IonizationEnergies = {},
    Isotopes = {
        {
            HalfLife = {
                "~ 29 s",
            },
            Mass = 285.177,
            MassNumber = 285,
            ModeOfDecay = {
                "alpha",
            },
            Name = "285Cn",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "~ 29 s",
            },
            Mass = 285.177,
            MassNumber = 285,
            ModeOfDecay = {
                "alpha",
            },
            Name = "285Cn",
        },
    },
    Name = "Copernicium",
    NeutronsApprox = 173,
    Period = 7,
    Protons = 112,
    RepresentativeMassNumber = 285,
    StateAt293K = "Solid",
    Symbol = "Cn",
    Uses = "At present, it is only used in research.",
}

return Copernicium
