local Copper = {
    Appearance = "A reddish-gold metal that is easily worked and drawn into wires.",
    AtomicMass = 63.546,
    AtomicNumber = 29,
    AtomicRadius = 1.96,
    Block = "d",
    BoilingPointK = 2833,
    Category = "Transition",
    CovalentRadius = 1.22,
    ElectronAffinity = 119.159,
    ElectronConfiguration = "[Ar] 3d104s1",
    Electronegativity = 1.9,
    Density = 8.96,
    Electrons = 29,
    EnergyLevels = {
        2,
        8,
        18,
        1,
    },
    Group = "11",
    IonizationEnergies = {
        745.482,
        1957.919,
        3554.616,
        5536.33,
        7699.5,
        9938,
        13411,
        16017,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 62.93,
            MassNumber = 63,
            ModeOfDecay = {},
            Name = "63Cu",
            NaturalAbundance = 69.15,
        },
        {
            HalfLife = {},
            Mass = 64.928,
            MassNumber = 65,
            ModeOfDecay = {},
            Name = "65Cu",
            NaturalAbundance = 30.85,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 62.93,
            MassNumber = 63,
            ModeOfDecay = {},
            Name = "63Cu",
            NaturalAbundance = 69.15,
        },
    },
    MeltingPointK = 1357.77,
    Name = "Copper",
    NeutronsApprox = 34,
    Period = 4,
    Protons = 29,
    RepresentativeMassNumber = 63,
    StateAt293K = "Solid",
    Symbol = "Cu",
    Uses = "Historically, copper was the first metal to be worked by people. The discovery that it could be hardened with a little tin to form the alloy bronze gave the name to the Bronze Age. \
\
Traditionally it has been one of the metals used to make coins, along with silver and gold. However, it is the most common of the three and therefore the least valued. All US coins are now copper alloys, and gun metals also contain copper. \
\
Most copper is used in electrical equipment such as wiring and motors. This is because it conducts both heat and electricity very well, and can be drawn into wires. It also has uses in construction (for example roofing and plumbing), and industrial machinery (such as heat exchangers).\
\
Copper sulfate is used widely as an agricultural poison and as an algicide in water purification. \
\
Copper compounds, such as Fehling's solution, are used in chemical tests for sugar detection.",
}

return Copper
