local Curium = {
    Appearance = "A radioactive metal that is silver in colour. It tarnishes rapidly in air.",
    AtomicMass = -247,
    AtomicNumber = 96,
    AtomicRadius = 2.45,
    Block = "f",
    Category = "Actinoid",
    CovalentRadius = 1.68,
    ElectronConfiguration = "[Rn] 5f76d17s2",
    Density = 13.51,
    Electrons = 96,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        25,
        9,
        2,
    },
    Group = "Actinides",
    IonizationEnergies = {
        578.082,
    },
    Isotopes = {
        {
            HalfLife = {
                "29.1 y",
                "5.5 x 1011 y",
            },
            Mass = 243.061,
            MassNumber = 243,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "243Cm",
        },
        {
            HalfLife = {
                "18.1 y",
                "1.32 x 107 y",
            },
            Mass = 244.063,
            MassNumber = 244,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "244Cm",
        },
        {
            HalfLife = {
                "8.48 x 103 y",
                "1.4 x 1012 y",
            },
            Mass = 245.065,
            MassNumber = 245,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "245Cm",
        },
        {
            HalfLife = {
                "4.76 x 103 y",
                "1.8 x 107 y",
            },
            Mass = 246.067,
            MassNumber = 246,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "246Cm",
        },
        {
            HalfLife = {
                "1.56 x 107 y",
            },
            Mass = 247.07,
            MassNumber = 247,
            ModeOfDecay = {
                "alpha",
            },
            Name = "247Cm",
        },
        {
            HalfLife = {
                "3.48 x 105 y",
            },
            Mass = 248.072,
            MassNumber = 248,
            ModeOfDecay = {
                "alpha",
            },
            Name = "248Cm",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "29.1 y",
                "5.5 x 1011 y",
            },
            Mass = 243.061,
            MassNumber = 243,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "243Cm",
        },
        {
            HalfLife = {
                "3.48 x 105 y",
            },
            Mass = 248.072,
            MassNumber = 248,
            ModeOfDecay = {
                "alpha",
            },
            Name = "248Cm",
        },
    },
    MeltingPointK = 1618,
    Name = "Curium",
    NeutronsApprox = 147,
    Period = 7,
    Protons = 96,
    RepresentativeMassNumber = 243,
    StateAt293K = "Solid",
    Symbol = "Cm",
    Uses = "Curium has been used to provide power to electrical equipment used on space missions.",
}

return Curium
