local Darmstadtium = {
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made.",
    AtomicMass = -281,
    AtomicNumber = 110,
    Block = "d",
    Category = "Other",
    CovalentRadius = 1.28,
    ElectronConfiguration = "[Rn] 5f146d97s1",
    Density = 34.8,
    Electrons = 110,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        17,
        1,
    },
    Group = "10",
    IonizationEnergies = {},
    Isotopes = {
        {
            HalfLife = {
                "13 s",
            },
            Mass = 281.165,
            MassNumber = 281,
            ModeOfDecay = {
                "sf",
            },
            Name = "281Ds",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "13 s",
            },
            Mass = 281.165,
            MassNumber = 281,
            ModeOfDecay = {
                "sf",
            },
            Name = "281Ds",
        },
    },
    Name = "Darmstadtium",
    NeutronsApprox = 171,
    Period = 7,
    Protons = 110,
    RepresentativeMassNumber = 281,
    StateAt293K = "Solid",
    Symbol = "Ds",
    Uses = "At present, it is only used in research.",
}

return Darmstadtium
