local Darmstadtium = {
    Name = "Darmstadtium",
    Symbol = "Ds",
    AtomicNumber = 110,
    AtomicMass = -281,
    RepresentativeMassNumber = 281,
    Protons = 110,
    Electrons = 110,
    NeutronsApprox = 171,
    Category = "Other",
    Group = "10",
    Period = 7,
    Block = "d",
    StateAt293K = "Solid",
    Density = 34.8,
    Appearance = {
        "A highly radioactive metal, of which only a few atoms have ever been made.",
    },
    Uses = {
        "At present, it is only used in research.",
    },
    ElectronConfiguration = "[Rn] 5f146d97s1",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        17,
        1,
    },
    CovalentRadius = 1.28,
    IonizationEnergies = {},
    KeyIsotopes = {
        {
            Name = "281Ds",
            HalfLife = {
                "13 s",
            },
            Mass = 281.165,
            MassNumber = 281,
            ModeOfDecay = {
                "sf",
            },
        },
    },
    Isotopes = {
        {
            Name = "281Ds",
            HalfLife = {
                "13 s",
            },
            Mass = 281.165,
            MassNumber = 281,
            ModeOfDecay = {
                "sf",
            },
        },
    },
}

return Darmstadtium
