local Dubnium = {
    Name = "Dubnium",
    Symbol = "Db",
    AtomicNumber = 105,
    AtomicMass = -268,
    RepresentativeMassNumber = 268,
    Protons = 105,
    Electrons = 105,
    NeutronsApprox = 163,
    Category = "Transition",
    Group = "5",
    Period = 7,
    Block = "d",
    StateAt293K = "Solid",
    Density = 29.3,
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made.",
    Uses = {
        "At present, it is only used in research.",
    },
    ElectronConfiguration = "[Rn] 5f146d37s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        11,
        2,
    },
    CovalentRadius = 1.49,
    IonizationEnergies = {},
    KeyIsotopes = {
        {
            Name = "268Db",
            HalfLife = {
                "1.2 d",
            },
            Mass = 268.126,
            MassNumber = 268,
            ModeOfDecay = {
                "fs, EC",
            },
        },
    },
    Isotopes = {
        {
            Name = "268Db",
            HalfLife = {
                "1.2 d",
            },
            Mass = 268.126,
            MassNumber = 268,
            ModeOfDecay = {
                "fs, EC",
            },
        },
    },
}

return Dubnium
