local Dubnium = {
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made.",
    AtomicMass = -268,
    AtomicNumber = 105,
    Block = "d",
    Category = "Transition",
    CovalentRadius = 1.49,
    ElectronConfiguration = "[Rn] 5f146d37s2",
    Density = 29.3,
    Electrons = 105,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        11,
        2,
    },
    Group = "5",
    IonizationEnergies = {},
    Isotopes = {
        {
            HalfLife = {
                "1.2 d",
            },
            Mass = 268.126,
            MassNumber = 268,
            ModeOfDecay = {
                "fs, EC",
            },
            Name = "268Db",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "1.2 d",
            },
            Mass = 268.126,
            MassNumber = 268,
            ModeOfDecay = {
                "fs, EC",
            },
            Name = "268Db",
        },
    },
    Name = "Dubnium",
    NeutronsApprox = 163,
    Period = 7,
    Protons = 105,
    RepresentativeMassNumber = 268,
    StateAt293K = "Solid",
    Symbol = "Db",
    Uses = "At present, it is only used in research.",
}

return Dubnium
