local Einsteinium = {
    Appearance = "A radioactive metal, only a few milligrams of which are made each year.",
    AtomicMass = -252,
    AtomicNumber = 99,
    AtomicRadius = 2.45,
    Block = "f",
    Category = "Actinoid",
    CovalentRadius = 1.65,
    ElectronConfiguration = "[Rn] 5f117s2",
    Density = 8.84,
    Electrons = 99,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        29,
        8,
        2,
    },
    Group = "Actinides",
    IonizationEnergies = {
        619.44,
        1158,
    },
    Isotopes = {
        {
            HalfLife = {
                "1.29 y",
            },
            Mass = 252.083,
            MassNumber = 252,
            ModeOfDecay = {
                "alpha",
                "EC",
            },
            Name = "252Es",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "1.29 y",
            },
            Mass = 252.083,
            MassNumber = 252,
            ModeOfDecay = {
                "alpha",
                "EC",
            },
            Name = "252Es",
        },
    },
    MeltingPointK = 1133,
    Name = "Einsteinium",
    NeutronsApprox = 153,
    Period = 7,
    Protons = 99,
    RepresentativeMassNumber = 252,
    StateAt293K = "Solid",
    Symbol = "Es",
    Uses = "Einsteinium has no uses outside research.",
}

return Einsteinium
