local Einsteinium = {
    Name = "Einsteinium",
    Symbol = "Es",
    AtomicNumber = 99,
    AtomicMass = -252,
    RepresentativeMassNumber = 252,
    Protons = 99,
    Electrons = 99,
    NeutronsApprox = 153,
    Category = "Actinoid",
    Group = "Actinides",
    Period = 7,
    Block = "f",
    StateAt293K = "Solid",
    Density = 8.84,
    Appearance = {
        "A radioactive metal, only a few milligrams of which are made each year.",
    },
    Uses = {
        "Einsteinium has no uses outside research.",
    },
    ElectronConfiguration = "[Rn] 5f117s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        29,
        8,
        2,
    },
    AtomicRadius = 2.45,
    CovalentRadius = 1.65,
    IonizationEnergies = {
        619.44,
        1158,
    },
    MeltingPointK = 1133,
    KeyIsotopes = {
        {
            Name = "252Es",
            HalfLife = {
                "1.29 y",
            },
            Mass = 252.083,
            MassNumber = 252,
            ModeOfDecay = {
                "alpha",
                "EC",
            },
        },
    },
    Isotopes = {
        {
            Name = "252Es",
            HalfLife = {
                "1.29 y",
            },
            Mass = 252.083,
            MassNumber = 252,
            ModeOfDecay = {
                "alpha",
                "EC",
            },
        },
    },
}

return Einsteinium
