local Erbium = {
    Appearance = "A soft, silvery metallic element.",
    AtomicMass = 167.26,
    AtomicNumber = 68,
    AtomicRadius = 2.29,
    Block = "f",
    BoilingPointK = 3141,
    Category = "Lanthanoid",
    CovalentRadius = 1.77,
    ElectronConfiguration = "[Xe] 4f126s2",
    Electronegativity = 1.24,
    Density = 9.066,
    Electrons = 68,
    EnergyLevels = {
        2,
        8,
        18,
        30,
        8,
        2,
    },
    Group = "Lanthanides",
    IonizationEnergies = {
        589.304,
        1151.07,
        2194.08,
        4119.9,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 161.929,
            MassNumber = 162,
            ModeOfDecay = {},
            Name = "162Er",
            NaturalAbundance = 0.139,
        },
        {
            HalfLife = {},
            Mass = 163.929,
            MassNumber = 164,
            ModeOfDecay = {},
            Name = "164Er",
            NaturalAbundance = 1.601,
        },
        {
            HalfLife = {},
            Mass = 165.93,
            MassNumber = 166,
            ModeOfDecay = {},
            Name = "166Er",
            NaturalAbundance = 33.503,
        },
        {
            HalfLife = {},
            Mass = 166.932,
            MassNumber = 167,
            ModeOfDecay = {},
            Name = "167Er",
            NaturalAbundance = 22.869,
        },
        {
            HalfLife = {},
            Mass = 167.932,
            MassNumber = 168,
            ModeOfDecay = {},
            Name = "168Er",
            NaturalAbundance = 26.978,
        },
        {
            HalfLife = {},
            Mass = 169.935,
            MassNumber = 170,
            ModeOfDecay = {},
            Name = "170Er",
            NaturalAbundance = 14.91,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 165.93,
            MassNumber = 166,
            ModeOfDecay = {},
            Name = "166Er",
            NaturalAbundance = 33.503,
        },
    },
    MeltingPointK = 1802,
    Name = "Erbium",
    NeutronsApprox = 98,
    Period = 6,
    Protons = 68,
    RepresentativeMassNumber = 166,
    StateAt293K = "Solid",
    Symbol = "Er",
    Uses = "Erbium finds little use as a metal because it slowly tarnishes in air and is attacked by water. \
\
When alloyed with metals such as vanadium, erbium lowers their hardness and improves their workability.\
\
Erbium oxide is occasionally used in infrared absorbing glass, for example safety glasses for welders and metal workers. When erbium is added to glass it gives the glass a pink tinge. It is used to give colour to some sunglasses and imitation gems.\
\
Broadband signals, carried by fibre optic cables, are amplified by including erbium in the glass fibre.",
}

return Erbium
