local Europium = {
    Appearance = "A soft, silvery metal that tarnishes quickly and reacts with water.",
    AtomicMass = 151.96,
    AtomicNumber = 63,
    AtomicRadius = 2.35,
    Block = "f",
    BoilingPointK = 1802,
    Category = "Lanthanoid",
    CovalentRadius = 1.83,
    ElectronAffinity = 83.363,
    ElectronConfiguration = "[Xe] 4f76s2",
    Density = 5.264,
    Electrons = 63,
    EnergyLevels = {
        2,
        8,
        18,
        25,
        8,
        2,
    },
    Group = "Lanthanides",
    IonizationEnergies = {
        547.109,
        1085.46,
        2404.41,
        4119.9,
    },
    Isotopes = {
        {
            HalfLife = {
                "> 1.7x1018 y",
            },
            Mass = 150.92,
            MassNumber = 151,
            ModeOfDecay = {},
            Name = "151Eu",
            NaturalAbundance = 47.81,
        },
        {
            HalfLife = {},
            Mass = 152.921,
            MassNumber = 153,
            ModeOfDecay = {},
            Name = "153Eu",
            NaturalAbundance = 52.19,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 152.921,
            MassNumber = 153,
            ModeOfDecay = {},
            Name = "153Eu",
            NaturalAbundance = 52.19,
        },
    },
    MeltingPointK = 1095,
    Name = "Europium",
    NeutronsApprox = 90,
    Period = 6,
    Protons = 63,
    RepresentativeMassNumber = 153,
    StateAt293K = "Solid",
    Symbol = "Eu",
    Uses = "Europium is used in the printing of euro banknotes. It glows red under UV light, and forgeries can be detected by the lack of this red glow.\
\
Low-energy light bulbs contain a little europium to give a more natural light, by balancing the blue (cold) light with a little red (warm) light.\
\
Europium is excellent at absorbing neutrons, making it valuable in control rods for nuclear reactors. \
\
Europium-doped plastic has been used as a laser material. It is also used in making thin super-conducting alloys.",
}

return Europium
