local Fermium = {
    Name = "Fermium",
    Symbol = "Fm",
    AtomicNumber = 100,
    AtomicMass = -257,
    RepresentativeMassNumber = 257,
    Protons = 100,
    Electrons = 100,
    NeutronsApprox = 157,
    Category = "Actinoid",
    Group = "Actinides",
    Period = 7,
    Block = "f",
    StateAt293K = "Solid",
    Appearance = "A radioactive metal obtained only in microgram quantities.",
    Uses = {
        "Fermium has no uses outside research.",
    },
    ElectronConfiguration = "[Rn] 5f127s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        30,
        8,
        2,
    },
    AtomicRadius = 2.45,
    CovalentRadius = 1.67,
    IonizationEnergies = {
        627.2,
    },
    MeltingPointK = 1800,
    KeyIsotopes = {
        {
            Name = "257Fm",
            HalfLife = {
                "100.5 d",
            },
            Mass = 257.095,
            MassNumber = 257,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
    },
    Isotopes = {
        {
            Name = "257Fm",
            HalfLife = {
                "100.5 d",
            },
            Mass = 257.095,
            MassNumber = 257,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
    },
}

return Fermium
