local Fermium = {
    Appearance = "A radioactive metal obtained only in microgram quantities.",
    AtomicMass = -257,
    AtomicNumber = 100,
    AtomicRadius = 2.45,
    Block = "f",
    Category = "Actinoid",
    CovalentRadius = 1.67,
    ElectronConfiguration = "[Rn] 5f127s2",
    Density = nil,
    Electrons = 100,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        30,
        8,
        2,
    },
    Group = "Actinides",
    IonizationEnergies = {
        627.2,
    },
    Isotopes = {
        {
            HalfLife = {
                "100.5 d",
            },
            Mass = 257.095,
            MassNumber = 257,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "257Fm",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "100.5 d",
            },
            Mass = 257.095,
            MassNumber = 257,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "257Fm",
        },
    },
    MeltingPointK = 1800,
    Name = "Fermium",
    NeutronsApprox = 157,
    Period = 7,
    Protons = 100,
    RepresentativeMassNumber = 257,
    StateAt293K = "Solid",
    Symbol = "Fm",
    Uses = "Fermium has no uses outside research.",
}

return Fermium
