local Flerovium = {
    Name = "Flerovium",
    Symbol = "Fl",
    AtomicNumber = 114,
    AtomicMass = -289,
    RepresentativeMassNumber = 289,
    Protons = 114,
    Electrons = 114,
    NeutronsApprox = 175,
    Category = "Poor",
    Group = "14",
    Period = 7,
    Block = "p",
    StateAt293K = "Solid",
    Density = 14,
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made.",
    Uses = {
        "At present, it is only used in research.",
    },
    ElectronConfiguration = "[Rn] 5f146d107s27p2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        18,
        4,
    },
    CovalentRadius = 1.43,
    IonizationEnergies = {},
    KeyIsotopes = {
        {
            Name = "289Fl",
            HalfLife = {
                "~ 2.1 s",
            },
            Mass = 289.19,
            MassNumber = 289,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
    Isotopes = {
        {
            Name = "289Fl",
            HalfLife = {
                "~ 2.1 s",
            },
            Mass = 289.19,
            MassNumber = 289,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
}

return Flerovium
