local Flerovium = {
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made.",
    AtomicMass = -289,
    AtomicNumber = 114,
    Block = "p",
    Category = "Poor",
    CovalentRadius = 1.43,
    ElectronConfiguration = "[Rn] 5f146d107s27p2",
    Density = 14,
    Electrons = 114,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        18,
        4,
    },
    Group = "14",
    IonizationEnergies = {},
    Isotopes = {
        {
            HalfLife = {
                "~ 2.1 s",
            },
            Mass = 289.19,
            MassNumber = 289,
            ModeOfDecay = {
                "alpha",
            },
            Name = "289Fl",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "~ 2.1 s",
            },
            Mass = 289.19,
            MassNumber = 289,
            ModeOfDecay = {
                "alpha",
            },
            Name = "289Fl",
        },
    },
    Name = "Flerovium",
    NeutronsApprox = 175,
    Period = 7,
    Protons = 114,
    RepresentativeMassNumber = 289,
    StateAt293K = "Solid",
    Symbol = "Fl",
    Uses = "At present, it is only used in research.",
}

return Flerovium
