local Fluorine = {
    Appearance = "A very pale yellow-green, dangerously reactive gas. It is the most reactive of all the elements and quickly attacks all metals. Steel wool bursts into flames when exposed to fluorine.",
    AtomicMass = 18.998,
    AtomicNumber = 9,
    AtomicRadius = 1.47,
    Block = "p",
    BoilingPointK = 85.04,
    Category = "Nonmetal",
    CovalentRadius = 0.6,
    ElectronAffinity = 328.165,
    ElectronConfiguration = "[He] 2s22p5",
    Electronegativity = 3.98,
    Density = 1.696,
    Electrons = 9,
    EnergyLevels = {
        2,
        7,
    },
    Group = "17",
    IonizationEnergies = {
        1681.045,
        3374.17,
        6050.441,
        8407.713,
        11022.755,
        15164.128,
        17867.734,
        92038.447,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 18.998,
            MassNumber = 19,
            ModeOfDecay = {},
            Name = "19F",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 18.998,
            MassNumber = 19,
            ModeOfDecay = {},
            Name = "19F",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 53.48,
    Name = "Fluorine",
    NeutronsApprox = 10,
    Period = 2,
    Protons = 9,
    RepresentativeMassNumber = 19,
    StateAt293K = "Gas",
    Symbol = "F",
    Uses = "There was no commercial production of fluorine until the Second World War, when the development of the atom bomb, and other nuclear energy projects, made it necessary to produce large quantities. Before this, fluorine salts, known as fluorides, were for a long time used in welding and for frosting glass. \
\
The element is used to make uranium hexafluoride, needed by the nuclear power industry to separate uranium isotopes. It is also used to make sulfur hexafluoride, the insulating gas for high-power electricity transformers. \
\
In fact, fluorine is used in many fluorochemicals, including solvents and high-temperature plastics, such as Teflon (poly(tetrafluoroethene), PTFE). Teflon is well known for its non-stick properties and is used in frying pans. It is also used for cable insulation, for plumber's tape and as the basis of Gore-Tex (used in waterproof shoes and clothing). \
\
Hydrofluoric acid is used for etching the glass of light bulbs and in similar applications. \
\
CFCs (chloro-fluoro-carbons) were once used as aerosol propellants, refrigerants and for 'blowing' expanded polystyrene. However, their inertness meant that, once in the atmosphere, they diffused into the stratosphere and destroyed the Earth's ozone layer. They are now banned.",
}

return Fluorine
