local Francium = {
    Appearance = "An intensely radioactive metal.",
    AtomicMass = -223,
    AtomicNumber = 87,
    AtomicRadius = 3.48,
    Block = "s",
    BoilingPointK = 923,
    Category = "Alkali",
    CovalentRadius = 2.42,
    ElectronAffinity = 44.38,
    ElectronConfiguration = "[Rn] 7s1",
    Electronegativity = 0.7,
    Density = 1.87,
    Electrons = 87,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        8,
        1,
    },
    Group = "1",
    IonizationEnergies = {
        392.96,
    },
    Isotopes = {
        {
            HalfLife = {
                "22.0 m",
            },
            Mass = 223.02,
            MassNumber = 223,
            ModeOfDecay = {
                "beta-",
                "alpha",
            },
            Name = "223Fr",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "22.0 m",
            },
            Mass = 223.02,
            MassNumber = 223,
            ModeOfDecay = {
                "beta-",
                "alpha",
            },
            Name = "223Fr",
        },
    },
    MeltingPointK = 294,
    Name = "Francium",
    NeutronsApprox = 136,
    Period = 7,
    Protons = 87,
    RepresentativeMassNumber = 223,
    StateAt293K = "Solid",
    Symbol = "Fr",
    Uses = "Francium has no uses, having a half life of only 22 minutes.",
}

return Francium
