local Gallium = {
    Appearance = "Gallium is a soft, silvery-white metal, similar to aluminium.",
    AtomicMass = 69.723,
    AtomicNumber = 31,
    AtomicRadius = 1.87,
    Block = "p",
    BoilingPointK = 2502,
    Category = "Poor",
    CovalentRadius = 1.23,
    ElectronAffinity = 41.49,
    ElectronConfiguration = "[Ar] 3d104s24p1",
    Electronegativity = 1.81,
    Density = 5.91,
    Electrons = 31,
    EnergyLevels = {
        2,
        8,
        18,
        3,
    },
    Group = "13",
    IonizationEnergies = {
        578.845,
        1979.411,
        2964.589,
        6101.829,
        8298.7,
        10873.9,
        13594.8,
        16392.9,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 68.926,
            MassNumber = 69,
            ModeOfDecay = {},
            Name = "69Ga",
            NaturalAbundance = 60.108,
        },
        {
            HalfLife = {
                "> 2.4 x 1026 y",
            },
            Mass = 70.925,
            MassNumber = 71,
            ModeOfDecay = {
                "beta-",
            },
            Name = "71Ga",
            NaturalAbundance = 39.892,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 68.926,
            MassNumber = 69,
            ModeOfDecay = {},
            Name = "69Ga",
            NaturalAbundance = 60.108,
        },
    },
    MeltingPointK = 302.9146,
    Name = "Gallium",
    NeutronsApprox = 38,
    Period = 4,
    Protons = 31,
    RepresentativeMassNumber = 69,
    StateAt293K = "Solid",
    Symbol = "Ga",
    Uses = "Gallium arsenide has a similar structure to silicon and is a useful silicon substitute for the electronics industry. It is an important component of many semiconductors. It is also used in red LEDs (light emitting diodes) because of its ability to convert electricity to light. Solar panels on the Mars Exploration Rover contained gallium arsenide.\
\
Gallium nitride is also a semiconductor. It has particular properties that make it very versatile. It has important uses in Blu-ray technology, mobile phones, blue and green LEDs and pressure sensors for touch switches.\
\
Gallium readily alloys with most metals. It is particularly used in low-melting alloys. \
\
It has a high boiling point, which makes it ideal for recording temperatures that would vaporise a thermometer.",
}

return Gallium
