local Germanium = {
    Name = "Germanium",
    Symbol = "Ge",
    AtomicNumber = 32,
    AtomicMass = 72.63,
    RepresentativeMassNumber = 73,
    Protons = 32,
    Electrons = 32,
    NeutronsApprox = 41,
    Category = "Metalloid",
    Group = "14",
    Period = 4,
    Block = "p",
    StateAt293K = "Solid",
    Density = 5.323,
    Appearance = {
        "A silvery-white semi-metal. It is brittle.",
    },
    Uses = {
        "Germanium is a semiconductor. The pure element was commonly doped with arsenic, gallium or other elements and used as a transistor in thousands of electronic applications. Today, however, other semiconductors have replaced it.",
        "Germanium oxide has a high index of refraction and dispersion. This makes it suitable for use in wide-angle camera lenses and objective lenses for microscopes. This is now the major use for this element.",
        "Germanium is also used as an alloying agent (adding 1% germanium to silver stops it from tarnishing), in fluorescent lamps and as a catalyst.",
        "Both germanium and germanium oxide are transparent to infrared radiation and so are used in infrared spectroscopes.",
    },
    ElectronConfiguration = "[Ar] 3d104s24p2",
    EnergyLevels = {
        2,
        8,
        18,
        4,
    },
    AtomicRadius = 2.11,
    CovalentRadius = 1.2,
    ElectronAffinity = 118.939,
    Electronegativity = 2.01,
    IonizationEnergies = {
        762.179,
        1537.456,
        3302.124,
        4410.644,
        9021.4,
    },
    MeltingPointK = 1211.4,
    BoilingPointK = 3106,
    KeyIsotopes = {
        {
            Name = "73Ge",
            HalfLife = {
                "> 1.8 x 1023 y",
            },
            Mass = 72.923,
            MassNumber = 73,
            ModeOfDecay = {
                "beta-",
            },
            NaturalAbundance = 7.75,
        },
        {
            Name = "74Ge",
            HalfLife = {},
            Mass = 73.921,
            MassNumber = 74,
            ModeOfDecay = {},
            NaturalAbundance = 36.5,
        },
    },
    Isotopes = {
        {
            Name = "70Ge",
            HalfLife = {},
            Mass = 69.924,
            MassNumber = 70,
            ModeOfDecay = {},
            NaturalAbundance = 20.57,
        },
        {
            Name = "72Ge",
            HalfLife = {},
            Mass = 71.922,
            MassNumber = 72,
            ModeOfDecay = {},
            NaturalAbundance = 27.45,
        },
        {
            Name = "73Ge",
            HalfLife = {
                "> 1.8 x 1023 y",
            },
            Mass = 72.923,
            MassNumber = 73,
            ModeOfDecay = {
                "beta-",
            },
            NaturalAbundance = 7.75,
        },
        {
            Name = "74Ge",
            HalfLife = {},
            Mass = 73.921,
            MassNumber = 74,
            ModeOfDecay = {},
            NaturalAbundance = 36.5,
        },
        {
            Name = "76Ge",
            HalfLife = {
                "1.6 X 1021 y",
            },
            Mass = 75.921,
            MassNumber = 76,
            ModeOfDecay = {
                "beta-beta-",
            },
            NaturalAbundance = 7.73,
        },
    },
}

return Germanium
