local Gold = {
    Appearance = "A soft metal with a characteristic yellow colour. It is chemically unreactive, although it will dissolve in aqua regia (a mixture of nitric and hydrochloric acids).",
    AtomicMass = 196.97,
    AtomicNumber = 79,
    AtomicRadius = 2.14,
    Block = "d",
    BoilingPointK = 3109,
    Category = "Transition",
    CovalentRadius = 1.3,
    ElectronAffinity = 222.749,
    ElectronConfiguration = "[Xe] 4f145d106s1",
    Electronegativity = 2.4,
    Density = 19.3,
    Electrons = 79,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        1,
    },
    Group = "11",
    IonizationEnergies = {
        890.128,
        1949,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 196.967,
            MassNumber = 197,
            ModeOfDecay = {},
            Name = "197Au",
            NaturalAbundance = 100,
        },
        {
            HalfLife = {
                "2.695 d",
            },
            Mass = 197.968,
            MassNumber = 198,
            ModeOfDecay = {
                "beta-",
            },
            Name = "198Au",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 196.967,
            MassNumber = 197,
            ModeOfDecay = {},
            Name = "197Au",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 1337.33,
    Name = "Gold",
    NeutronsApprox = 118,
    Period = 6,
    Protons = 79,
    RepresentativeMassNumber = 197,
    StateAt293K = "Solid",
    Symbol = "Au",
    Uses = "Most mined gold is stored as bullion. It is also, however, used extensively in jewellery, either in its pure form or as an alloy. The term 'carat' indicates the amount of gold present in an alloy. 24-carat is pure gold, but it is very soft. 18- and 9-carat gold alloys are commonly used because they are more durable. \
\
The metal is also used for coinage, and has been used as standard for monetary systems in some countries. \
\
Gold can be beaten into very thin sheets (gold leaf) to be used in art, for decoration and as architectural ornament. Electroplating can be used to cover another metal with a very thin layer of gold. This is used in gears for watches, artificial limb joints, cheap jewellery and electrical connectors. It is ideal for protecting electrical copper components because it conducts electricity well and does not corrode (which would break the contact). Thin gold wires are used inside computer chips to produce circuits. \
\
Dentists sometimes use gold alloys in fillings, and a gold compound is used to treat some cases of arthritis. \
\
Gold nanoparticles are increasingly being used as industrial catalysts. Vinyl acetate, which is used to make PVA (for glue, paint and resin), is made using a gold catalyst.",
}

return Gold
