local Hassium = {
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made.",
    AtomicMass = -277,
    AtomicNumber = 108,
    Block = "d",
    Category = "Transition",
    CovalentRadius = 1.34,
    ElectronConfiguration = "[Rn] 5f146d67s2",
    Density = 40.7,
    Electrons = 108,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        14,
        2,
    },
    Group = "8",
    IonizationEnergies = {},
    Isotopes = {
        {
            HalfLife = {
                "0.3 m",
            },
            Mass = 270.134,
            MassNumber = 270,
            ModeOfDecay = {
                "alpha",
            },
            Name = "270Hs",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "0.3 m",
            },
            Mass = 270.134,
            MassNumber = 270,
            ModeOfDecay = {
                "alpha",
            },
            Name = "270Hs",
        },
    },
    Name = "Hassium",
    NeutronsApprox = 162,
    Period = 7,
    Protons = 108,
    RepresentativeMassNumber = 270,
    StateAt293K = "Solid",
    Symbol = "Hs",
    Uses = "At present it is only used in research.",
}

return Hassium
