local Hassium = {
    Name = "Hassium",
    Symbol = "Hs",
    AtomicNumber = 108,
    AtomicMass = -277,
    RepresentativeMassNumber = 270,
    Protons = 108,
    Electrons = 108,
    NeutronsApprox = 162,
    Category = "Transition",
    Group = "8",
    Period = 7,
    Block = "d",
    StateAt293K = "Solid",
    Density = 40.7,
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made.",
    Uses = {
        "At present it is only used in research.",
    },
    ElectronConfiguration = "[Rn] 5f146d67s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        14,
        2,
    },
    CovalentRadius = 1.34,
    IonizationEnergies = {},
    KeyIsotopes = {
        {
            Name = "270Hs",
            HalfLife = {
                "0.3 m",
            },
            Mass = 270.134,
            MassNumber = 270,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
    Isotopes = {
        {
            Name = "270Hs",
            HalfLife = {
                "0.3 m",
            },
            Mass = 270.134,
            MassNumber = 270,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
}

return Hassium
