local Hydrogen = {
    Appearance = "A colourless, odourless gas. It has the lowest density of all gases.",
    AtomicMass = 1.008,
    AtomicNumber = 1,
    AtomicRadius = 1.1,
    Block = "s",
    BoilingPointK = 20.271,
    Category = "Nonmetal",
    CovalentRadius = 0.32,
    ElectronAffinity = 72.769,
    ElectronConfiguration = "1s1",
    Electronegativity = 2.2,
    Density = 0.08988,
    Electrons = 1,
    EnergyLevels = {
        1,
    },
    Group = "1",
    IonizationEnergies = {
        1312.05,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 1.008,
            MassNumber = 1,
            ModeOfDecay = {},
            Name = "1H",
            NaturalAbundance = 99.9885,
        },
        {
            HalfLife = {},
            Mass = 2.014,
            MassNumber = 2,
            ModeOfDecay = {},
            Name = "2H",
            NaturalAbundance = 0.0115,
        },
        {
            HalfLife = {
                "12.31 y",
            },
            Mass = 3.016,
            MassNumber = 3,
            ModeOfDecay = {
                "beta-",
            },
            Name = "3H",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 1.008,
            MassNumber = 1,
            ModeOfDecay = {},
            Name = "1H",
            NaturalAbundance = 99.9885,
        },
        {
            HalfLife = {},
            Mass = 2.014,
            MassNumber = 2,
            ModeOfDecay = {},
            Name = "2H",
            NaturalAbundance = 0.0115,
        },
    },
    MeltingPointK = 13.99,
    Name = "Hydrogen",
    NeutronsApprox = 0,
    Period = 1,
    Protons = 1,
    RepresentativeMassNumber = 1,
    StateAt293K = "Gas",
    Symbol = "H",
    Uses = "Some see hydrogen gas as the clean fuel of the future - generated from water and returning to water when it is oxidised. Hydrogen-powered fuel cells are increasingly being seen as 'pollution-free' sources of energy and are now being used in some buses and cars.\
\
Hydrogen also has many other uses. In the chemical industry it is used to make ammonia for agricultural fertiliser (the Haber process) and cyclohexane and methanol, which are intermediates in the production of plastics and pharmaceuticals. It is also used to remove sulfur from fuels during the oil-refining process. Large quantities of hydrogen are used to hydrogenate oils to form fats, for example to make margarine. \
\
In the glass industry hydrogen is used as a protective atmosphere for making flat glass sheets. In the electronics industry it is used as a flushing gas during the manufacture of silicon chips. \
\
The low density of hydrogen made it a natural choice for one of its first practical uses - filling balloons and airships. However, it reacts vigorously with oxygen (to form water) and its future in filling airships ended when the Hindenburg airship caught fire.",
}

return Hydrogen
