local Indium = {
    Name = "Indium",
    Symbol = "In",
    AtomicNumber = 49,
    AtomicMass = 114.82,
    RepresentativeMassNumber = 115,
    Protons = 49,
    Electrons = 49,
    NeutronsApprox = 66,
    Category = "Poor",
    Group = "13",
    Period = 5,
    Block = "p",
    StateAt293K = "Solid",
    Density = 7.31,
    Appearance = "A soft, silvery metal that is stable in air and water.",
    Uses = {
        "Most indium is used to make indium tin oxide (ITO), which is an important part of touch screens, flatscreen TVs and solar panels. This is because it conducts electricity, bonds strongly to glass and is transparent.",
        "Indium nitride, phosphide and antimonide are semiconductors used in transistors and microchips.",
        "Indium metal sticks to glass and can be used to give a mirror finish to windows of tall buildings, and as a protective film on welders' goggles. It has also been used to coat ball bearings in Formula 1 racing cars because of its low friction.",
        "An indium alloy has been used for fire-sprinkler systems in shops and warehouses because of its low melting point.",
    },
    ElectronConfiguration = "[Kr] 4d105s25p1",
    EnergyLevels = {
        2,
        8,
        18,
        18,
        3,
    },
    AtomicRadius = 1.93,
    CovalentRadius = 1.42,
    ElectronAffinity = 28.9,
    Electronegativity = 1.78,
    IonizationEnergies = {
        558.299,
        1820.707,
        2704.48,
        5210,
    },
    MeltingPointK = 429.75,
    BoilingPointK = 2300,
    KeyIsotopes = {
        {
            Name = "115In",
            HalfLife = {
                "4.4 x 1014 y",
            },
            Mass = 114.904,
            MassNumber = 115,
            ModeOfDecay = {
                "beta-",
            },
            NaturalAbundance = 95.71,
        },
    },
    Isotopes = {
        {
            Name = "115In",
            HalfLife = {
                "4.4 x 1014 y",
            },
            Mass = 114.904,
            MassNumber = 115,
            ModeOfDecay = {
                "beta-",
            },
            NaturalAbundance = 95.71,
        },
    },
}

return Indium
