local Iodine = {
    Appearance = "A black, shiny, crystalline solid. When heated, iodine sublimes to form a purple vapour.",
    AtomicMass = 126.9,
    AtomicNumber = 53,
    AtomicRadius = 1.98,
    Block = "p",
    BoilingPointK = 457.6,
    Category = "Nonmetal",
    CovalentRadius = 1.36,
    ElectronAffinity = 295.152,
    ElectronConfiguration = "[Kr] 4d105s25p5",
    Electronegativity = 2.66,
    Density = 4.933,
    Electrons = 53,
    EnergyLevels = {
        2,
        8,
        18,
        18,
        7,
    },
    Group = "17",
    IonizationEnergies = {
        1008.393,
        1845.89,
        3184,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 126.904,
            MassNumber = 127,
            ModeOfDecay = {},
            Name = "127I",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 126.904,
            MassNumber = 127,
            ModeOfDecay = {},
            Name = "127I",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 386.9,
    Name = "Iodine",
    NeutronsApprox = 74,
    Period = 5,
    Protons = 53,
    RepresentativeMassNumber = 127,
    StateAt293K = "Solid",
    Symbol = "I",
    Uses = "Photography was the first commercial use for iodine after Louis Daguerre, in 1839, invented a technique for producing images on a piece of metal. These images were called daguerreotypes.\
\
Today, iodine has many commercial uses. Iodide salts are used in pharmaceuticals and disinfectants, printing inks and dyes, catalysts, animal feed supplements and photographic chemicals. Iodine is also used to make polarising filters for LCD displays.\
\
Iodide is added in small amounts to table salt, in order to avoid iodine deficiency affecting the thyroid gland. The radioactive isotope iodine-131 is sometimes used to treat cancerous thyroid glands.",
}

return Iodine
