local Iron = {
    Appearance = "A shiny, greyish metal that rusts in damp air.",
    AtomicMass = 55.845,
    AtomicNumber = 26,
    AtomicRadius = 2.04,
    Block = "d",
    BoilingPointK = 3134,
    Category = "Transition",
    CovalentRadius = 1.24,
    ElectronAffinity = 14.569,
    ElectronConfiguration = "[Ar] 3d64s2",
    Electronegativity = 1.83,
    Density = 7.874,
    Electrons = 26,
    EnergyLevels = {
        2,
        8,
        14,
        2,
    },
    Group = "8",
    IonizationEnergies = {
        762.466,
        1561.876,
        2957.469,
        5287.4,
        7236,
        9561.7,
        12058.74,
        14575.08,
    },
    Isotopes = {
        {
            HalfLife = {
                "> 3.1 x 1022 y",
            },
            Mass = 53.94,
            MassNumber = 54,
            ModeOfDecay = {
                "EC-EC",
            },
            Name = "54Fe",
            NaturalAbundance = 5.845,
        },
        {
            HalfLife = {},
            Mass = 55.935,
            MassNumber = 56,
            ModeOfDecay = {},
            Name = "56Fe",
            NaturalAbundance = 91.754,
        },
        {
            HalfLife = {},
            Mass = 56.935,
            MassNumber = 57,
            ModeOfDecay = {},
            Name = "57Fe",
            NaturalAbundance = 2.119,
        },
        {
            HalfLife = {},
            Mass = 57.933,
            MassNumber = 58,
            ModeOfDecay = {},
            Name = "58Fe",
            NaturalAbundance = 0.282,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 55.935,
            MassNumber = 56,
            ModeOfDecay = {},
            Name = "56Fe",
            NaturalAbundance = 91.754,
        },
    },
    MeltingPointK = 1811,
    Name = "Iron",
    NeutronsApprox = 30,
    Period = 4,
    Protons = 26,
    RepresentativeMassNumber = 56,
    StateAt293K = "Solid",
    Symbol = "Fe",
    Uses = "Iron is an enigma - it rusts easily, yet it is the most important of all metals. 90% of all metal that is refined today is iron. \
\
Most is used to manufacture steel, used in civil engineering (reinforced concrete, girders etc) and in manufacturing. \
\
There are many different types of steel with different properties and uses. Ordinary carbon steel is an alloy of iron with carbon (from 0.1% for mild steel up to 2% for high carbon steels), with small amounts of other elements. \
\
Alloy steels are carbon steels with other additives such as nickel, chromium, vanadium, tungsten and manganese. These are stronger and tougher than carbon steels and have a huge variety of applications including bridges, electricity pylons, bicycle chains, cutting tools and rifle barrels.\
\
Stainless steel is very resistant to corrosion. It contains at least 10.5% chromium. Other metals such as nickel, molybdenum, titanium and copper are added to enhance its strength and workability. It is used in architecture, bearings, cutlery, surgical instruments and jewellery.\
\
Cast iron contains 3-5% carbon. It is used for pipes, valves and pumps. It is not as tough as steel but it is cheaper. Magnets can be made of iron and its alloys and compounds.\
\
Iron catalysts are used in the Haber process for producing ammonia, and in the Fischer-Tropsch process for converting syngas (hydrogen and carbon monoxide) into liquid fuels.",
}

return Iron
