local Krypton = {
    Appearance = "Krypton is a gas with no colour or smell. It does not react with anything except fluorine gas.",
    AtomicMass = 83.798,
    AtomicNumber = 36,
    AtomicRadius = 2.02,
    Block = "p",
    BoilingPointK = 119.735,
    Category = "Noble",
    CovalentRadius = 1.16,
    ElectronConfiguration = "[Ar] 3d104s24p6",
    Density = 3.749,
    Electrons = 36,
    EnergyLevels = {
        2,
        8,
        18,
        8,
    },
    Group = "18",
    IonizationEnergies = {
        1350.757,
        2350.367,
        3565.13,
        5065.5,
        6242.6,
        7574.1,
        10710,
        12138.049,
    },
    Isotopes = {
        {
            HalfLife = {
                "> 1.5 x 1021 y",
            },
            Mass = 77.92,
            MassNumber = 78,
            ModeOfDecay = {
                "EC-EC",
            },
            Name = "78Kr",
            NaturalAbundance = 0.355,
        },
        {
            HalfLife = {},
            Mass = 79.916,
            MassNumber = 80,
            ModeOfDecay = {},
            Name = "80Kr",
            NaturalAbundance = 2.286,
        },
        {
            HalfLife = {},
            Mass = 81.913,
            MassNumber = 82,
            ModeOfDecay = {},
            Name = "82Kr",
            NaturalAbundance = 11.593,
        },
        {
            HalfLife = {},
            Mass = 82.914,
            MassNumber = 83,
            ModeOfDecay = {},
            Name = "83Kr",
            NaturalAbundance = 11.5,
        },
        {
            HalfLife = {},
            Mass = 83.911,
            MassNumber = 84,
            ModeOfDecay = {},
            Name = "84Kr",
            NaturalAbundance = 56.987,
        },
        {
            HalfLife = {},
            Mass = 85.911,
            MassNumber = 86,
            ModeOfDecay = {},
            Name = "86Kr",
            NaturalAbundance = 17.279,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 83.911,
            MassNumber = 84,
            ModeOfDecay = {},
            Name = "84Kr",
            NaturalAbundance = 56.987,
        },
    },
    MeltingPointK = 115.78,
    Name = "Krypton",
    NeutronsApprox = 48,
    Period = 4,
    Protons = 36,
    RepresentativeMassNumber = 84,
    StateAt293K = "Gas",
    Symbol = "Kr",
    Uses = "Krypton is used commercially as a filling gas for energy-saving fluorescent lights. It is also used in some flash lamps used for high-speed photography. \
\
Unlike the lighter gases in its group, it is reactive enough to form some chemical compounds. For example, krypton will react with fluorine to form krypton fluoride. Krypton fluoride is used in some lasers.\
\
Radioactive krypton was used during the Cold War to estimate Soviet nuclear production. The gas is a product of all nuclear reactors, so the Russian share was found by subtracting the amount that came from Western reactors from the total in the air. \
\
From 1960 to 1983 the isotope krypton-86 was used to define the standard measure of length. One metre was defined as exactly 1,650,763.73 wavelengths of a line in the atomic spectrum of the isotope.",
}

return Krypton
