local Lanthanum = {
    Appearance = "A soft, silvery-white metal. It rapidly tarnishes in air and burns easily when ignited.",
    AtomicMass = 138.91,
    AtomicNumber = 57,
    AtomicRadius = 2.43,
    Block = "d",
    BoilingPointK = 3737,
    Category = "Lanthanoid",
    CovalentRadius = 1.94,
    ElectronAffinity = 45.35,
    ElectronConfiguration = "[Xe] 5d16s2",
    Electronegativity = 1.1,
    Density = 6.162,
    Electrons = 57,
    EnergyLevels = {
        2,
        8,
        18,
        18,
        9,
        2,
    },
    Group = "Lanthanides",
    IonizationEnergies = {
        538.089,
        1067.031,
        1850.328,
        4819.44,
        5943.5,
    },
    Isotopes = {
        {
            HalfLife = {
                "1.06 x 1011 y",
            },
            Mass = 137.907,
            MassNumber = 138,
            ModeOfDecay = {},
            Name = "138La",
            NaturalAbundance = 0.09,
        },
        {
            HalfLife = {},
            Mass = 138.906,
            MassNumber = 139,
            ModeOfDecay = {},
            Name = "139La",
            NaturalAbundance = 99.91,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 138.906,
            MassNumber = 139,
            ModeOfDecay = {},
            Name = "139La",
            NaturalAbundance = 99.91,
        },
    },
    MeltingPointK = 1193,
    Name = "Lanthanum",
    NeutronsApprox = 82,
    Period = 6,
    Protons = 57,
    RepresentativeMassNumber = 139,
    StateAt293K = "Solid",
    Symbol = "La",
    Uses = "Lanthanum metal has no commercial uses. However, its alloys have a variety of uses. A lanthanum-nickel alloy is used to store hydrogen gas for use in hydrogen-powered vehicles. Lanthanum is also found in the anode of nickel metal hydride batteries used in hybrid cars. \
\
Lanthanum is an important component of mischmetal alloy (about 20%). The best-known use for this alloy is in 'flints' for cigarette lighters. \
\
'Rare earth' compounds containing lanthanum are used extensively in carbon lighting applications, such as studio lighting and cinema projection. They increase the brightness and give an emission spectrum similar to sunlight.\
\
Lanthanum(III) oxide is used in making special optical glasses, as it improves the optical properties and alkali resistance of the glass. Lanthanum salts are used in catalysts for petroleum refining. \
\
The ion La3+ is used as a biological tracer for Ca2+, and radioactive lanthanum has been tested for use in treating cancer.",
}

return Lanthanum
