local Lawrencium = {
    Appearance = "A radioactive metal of which only a few atoms have ever been created.",
    AtomicMass = -266,
    AtomicNumber = 103,
    AtomicRadius = 2.46,
    Block = "f",
    Category = "Actinoid",
    CovalentRadius = 1.61,
    ElectronConfiguration = "[Rn] 5f147s27p1",
    Density = nil,
    Electrons = 103,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        8,
        3,
    },
    Group = "Actinides",
    IonizationEnergies = {
        472.8,
    },
    Isotopes = {
        {
            HalfLife = {
                "3.6 h",
            },
            Mass = 262.11,
            MassNumber = 262,
            ModeOfDecay = {
                "EC",
                "sf",
            },
            Name = "262Lr",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "3.6 h",
            },
            Mass = 262.11,
            MassNumber = 262,
            ModeOfDecay = {
                "EC",
                "sf",
            },
            Name = "262Lr",
        },
    },
    MeltingPointK = 1900,
    Name = "Lawrencium",
    NeutronsApprox = 159,
    Period = 7,
    Protons = 103,
    RepresentativeMassNumber = 262,
    StateAt293K = "Solid",
    Symbol = "Lr",
    Uses = "Lawrencium has no uses outside research.",
}

return Lawrencium
