local Lead = {
    Appearance = "A dull, silvery-grey metal. It is soft and easily worked into sheets.",
    AtomicMass = 207.2,
    AtomicNumber = 82,
    AtomicRadius = 2.02,
    Block = "p",
    BoilingPointK = 2022,
    Category = "Poor",
    CovalentRadius = 1.45,
    ElectronAffinity = 35.121,
    ElectronConfiguration = "[Xe] 4f145d106s26p2",
    Electronegativity = 1.8,
    Density = 11.34,
    Electrons = 82,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        4,
    },
    Group = "14",
    IonizationEnergies = {
        715.596,
        1450.414,
        3081.481,
        4083.26,
        6638.2,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 203.973,
            MassNumber = 204,
            ModeOfDecay = {},
            Name = "204Pb",
            NaturalAbundance = 1.4,
        },
        {
            HalfLife = {},
            Mass = 205.974,
            MassNumber = 206,
            ModeOfDecay = {},
            Name = "206Pb",
            NaturalAbundance = 24.1,
        },
        {
            HalfLife = {},
            Mass = 206.976,
            MassNumber = 207,
            ModeOfDecay = {},
            Name = "207Pb",
            NaturalAbundance = 22.1,
        },
        {
            HalfLife = {
                "> 2 x 1019 y",
            },
            Mass = 207.977,
            MassNumber = 208,
            ModeOfDecay = {
                "sf",
            },
            Name = "208Pb",
            NaturalAbundance = 52.4,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "> 2 x 1019 y",
            },
            Mass = 207.977,
            MassNumber = 208,
            ModeOfDecay = {
                "sf",
            },
            Name = "208Pb",
            NaturalAbundance = 52.4,
        },
    },
    MeltingPointK = 600.612,
    Name = "Lead",
    NeutronsApprox = 126,
    Period = 6,
    Protons = 82,
    RepresentativeMassNumber = 208,
    StateAt293K = "Solid",
    Symbol = "Pb",
    Uses = "This easily worked and corrosion-resistant metal has been used for pipes, pewter and paint since Roman times. It has also been used in lead glazes for pottery and, in this century, insecticides, hair dyes and as an anti-knocking additive for petrol. All these uses have now been banned, replaced or discouraged as lead is known to be detrimental to health, particularly that of children. \
\
Lead is still widely used for car batteries, pigments, ammunition, cable sheathing, weights for lifting, weight belts for diving, lead crystal glass, radiation protection and in some solders. \
\
It is often used to store corrosive liquids. It is also sometimes used in architecture, for roofing and in stained glass windows.",
}

return Lead
