local Lithium = {
    Appearance = "A soft, silvery metal. It has the lowest density of all metals. It reacts vigorously with water.",
    AtomicMass = 6.94,
    AtomicNumber = 3,
    AtomicRadius = 1.82,
    Block = "s",
    BoilingPointK = 1615,
    Category = "Alkali",
    CovalentRadius = 1.3,
    ElectronAffinity = 59.633,
    ElectronConfiguration = "[He] 2s1",
    Electronegativity = 0.98,
    Density = 0.534,
    Electrons = 3,
    EnergyLevels = {
        2,
        1,
    },
    Group = "1",
    IonizationEnergies = {
        520.222,
        7298.15,
        11815.044,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 6.015,
            MassNumber = 6,
            ModeOfDecay = {},
            Name = "6Li",
            NaturalAbundance = 7.59,
        },
        {
            HalfLife = {},
            Mass = 7.016,
            MassNumber = 7,
            ModeOfDecay = {},
            Name = "7Li",
            NaturalAbundance = 92.41,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 7.016,
            MassNumber = 7,
            ModeOfDecay = {},
            Name = "7Li",
            NaturalAbundance = 92.41,
        },
    },
    MeltingPointK = 453.65,
    Name = "Lithium",
    NeutronsApprox = 4,
    Period = 2,
    Protons = 3,
    RepresentativeMassNumber = 7,
    StateAt293K = "Solid",
    Symbol = "Li",
    Uses = "The most important use of lithium is in rechargeable batteries for mobile phones, laptops, digital cameras and electric vehicles. Lithium is also used in some non-rechargeable batteries for things like heart pacemakers, toys and clocks.\
\
Lithium metal is made into alloys with aluminium and magnesium, improving their strength and making them lighter. A magnesium-lithium alloy is used for armour plating. Aluminium-lithium alloys are used in aircraft, bicycle frames and high-speed trains.\
\
Lithium oxide is used in special glasses and glass ceramics. Lithium chloride is one of the most hygroscopic materials known, and is used in air conditioning and industrial drying systems (as is lithium bromide). Lithium stearate is used as an all-purpose and high-temperature lubricant. Lithium carbonate is used in drugs to treat manic depression, although its action on the brain is still not fully understood. Lithium hydride is used as a means of storing hydrogen for use as a fuel.",
}

return Lithium
