local Livermorium = {
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made.",
    AtomicMass = -293,
    AtomicNumber = 116,
    Block = "p",
    Category = "Other",
    CovalentRadius = 1.75,
    ElectronConfiguration = "[Rn] 5f146d107s27p4",
    Density = 12.9,
    Electrons = 116,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        18,
        6,
    },
    Group = "16",
    IonizationEnergies = {},
    Isotopes = {
        {
            HalfLife = {
                "0.06 s",
            },
            Mass = 293,
            MassNumber = 293,
            ModeOfDecay = {
                "alpha",
            },
            Name = "293Lv",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "0.06 s",
            },
            Mass = 293,
            MassNumber = 293,
            ModeOfDecay = {
                "alpha",
            },
            Name = "293Lv",
        },
    },
    Name = "Livermorium",
    NeutronsApprox = 177,
    Period = 7,
    Protons = 116,
    RepresentativeMassNumber = 293,
    StateAt293K = "Solid",
    Symbol = "Lv",
    Uses = "At present, it is only used in research.",
}

return Livermorium
