local Magnesium = {
    Appearance = "A silvery-white metal that ignites easily in air and burns with a bright light.",
    AtomicMass = 24.305,
    AtomicNumber = 12,
    AtomicRadius = 1.73,
    Block = "s",
    BoilingPointK = 1363,
    Category = "Alkaline",
    CovalentRadius = 1.4,
    ElectronConfiguration = "[Ne] 3s2",
    Electronegativity = 1.31,
    Density = 1.738,
    Electrons = 12,
    EnergyLevels = {
        2,
        8,
        2,
    },
    Group = "2",
    IonizationEnergies = {
        737.75,
        1450.683,
        7732.692,
        10542.519,
        13630.48,
        18019.6,
        21711.13,
        25661.24,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 23.985,
            MassNumber = 24,
            ModeOfDecay = {},
            Name = "24Mg",
            NaturalAbundance = 78.99,
        },
        {
            HalfLife = {},
            Mass = 24.986,
            MassNumber = 25,
            ModeOfDecay = {},
            Name = "25Mg",
            NaturalAbundance = 10,
        },
        {
            HalfLife = {},
            Mass = 25.983,
            MassNumber = 26,
            ModeOfDecay = {},
            Name = "26Mg",
            NaturalAbundance = 11.01,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 23.985,
            MassNumber = 24,
            ModeOfDecay = {},
            Name = "24Mg",
            NaturalAbundance = 78.99,
        },
    },
    MeltingPointK = 923,
    Name = "Magnesium",
    NeutronsApprox = 12,
    Period = 3,
    Protons = 12,
    RepresentativeMassNumber = 24,
    StateAt293K = "Solid",
    Symbol = "Mg",
    Uses = "Magnesium is one-third less dense than aluminium. It improves the mechanical, fabrication and welding characteristics of aluminium when used as an alloying agent. These alloys are useful in aeroplane and car construction.\
\
Magnesium is used in products that benefit from being lightweight, such as car seats, luggage, laptops, cameras and power tools. It is also added to molten iron and steel to remove sulfur. \
\
As magnesium ignites easily in air and burns with a bright light, it's used in flares, fireworks and sparklers.\
\
Magnesium sulfate is sometimes used as a mordant for dyes. Magnesium hydroxide is added to plastics to make them fire retardant. Magnesium oxide is used to make heat-resistant bricks for fireplaces and furnaces. It is also added to cattle feed and fertilisers. Magnesium hydroxide (milk of magnesia), sulfate (Epsom salts), chloride and citrate are all used in medicine.\
\
Grignard reagents are organic magnesium compounds that are important for the chemical industry.",
}

return Magnesium
