local Manganese = {
    Appearance = "A hard, brittle, silvery metal.",
    AtomicMass = 54.938,
    AtomicNumber = 25,
    AtomicRadius = 2.05,
    Block = "d",
    BoilingPointK = 2334,
    Category = "Transition",
    CovalentRadius = 1.29,
    ElectronConfiguration = "[Ar] 3d54s2",
    Electronegativity = 1.55,
    Density = 7.21,
    Electrons = 25,
    EnergyLevels = {
        2,
        8,
        13,
        2,
    },
    Group = "7",
    IonizationEnergies = {
        717.274,
        1509.03,
        3248.468,
        4940,
        6985.5,
        9224,
        11501.342,
        18766.4,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 54.938,
            MassNumber = 55,
            ModeOfDecay = {},
            Name = "55Mn",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 54.938,
            MassNumber = 55,
            ModeOfDecay = {},
            Name = "55Mn",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 1519,
    Name = "Manganese",
    NeutronsApprox = 30,
    Period = 4,
    Protons = 25,
    RepresentativeMassNumber = 55,
    StateAt293K = "Solid",
    Symbol = "Mn",
    Uses = "Manganese is too brittle to be of much use as a pure metal. It is mainly used in alloys, such as steel. \
\
Steel contains about 1% manganese, to increase the strength and also improve workability and resistance to wear. \
\
Manganese steel contains about 13% manganese. This is extremely strong and is used for railway tracks, safes, rifle barrels and prison bars.\
\
Drinks cans are made of an alloy of aluminium with 1.5% manganese, to improve resistance to corrosion. With aluminium, antimony and copper it forms highly magnetic alloys. \
\
Manganese(IV) oxide is used as a catalyst, a rubber additive and to decolourise glass that is coloured green by iron impurities. Manganese sulfate is used to make a fungicide. Manganese(II) oxide is a powerful oxidising agent and is used in quantitative analysis. It is also used to make fertilisers and ceramics.",
}

return Manganese
