local Meitnerium = {
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made.",
    AtomicMass = -278,
    AtomicNumber = 109,
    Block = "d",
    Category = "Other",
    CovalentRadius = 1.29,
    ElectronConfiguration = "[Rn] 5f146d77s2",
    Density = 37.4,
    Electrons = 109,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        15,
        2,
    },
    Group = "9",
    IonizationEnergies = {},
    Isotopes = {
        {
            HalfLife = {
                "~ 0.7 s",
            },
            Mass = 276.152,
            MassNumber = 276,
            ModeOfDecay = {
                "alpha",
            },
            Name = "276Mt",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "~ 0.7 s",
            },
            Mass = 276.152,
            MassNumber = 276,
            ModeOfDecay = {
                "alpha",
            },
            Name = "276Mt",
        },
    },
    Name = "Meitnerium",
    NeutronsApprox = 167,
    Period = 7,
    Protons = 109,
    RepresentativeMassNumber = 276,
    StateAt293K = "Solid",
    Symbol = "Mt",
    Uses = "At present it is only used in research.",
}

return Meitnerium
