local Mendelevium = {
    Appearance = "A radioactive metal, of which only a few atoms have ever been created.",
    AtomicMass = -258,
    AtomicNumber = 101,
    AtomicRadius = 2.46,
    Block = "f",
    Category = "Actinoid",
    CovalentRadius = 1.73,
    ElectronConfiguration = "[Rn] 5f137s2",
    Density = nil,
    Electrons = 101,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        31,
        8,
        2,
    },
    Group = "Actinides",
    IonizationEnergies = {
        634.87,
    },
    Isotopes = {
        {
            HalfLife = {
                "51.5 d",
            },
            Mass = 258.098,
            MassNumber = 258,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "258Md",
        },
        {
            HalfLife = {
                "~ 27.8 d",
            },
            Mass = 260.104,
            MassNumber = 260,
            ModeOfDecay = {
                "sf",
            },
            Name = "260Md",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "51.5 d",
            },
            Mass = 258.098,
            MassNumber = 258,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "258Md",
        },
        {
            HalfLife = {
                "~ 27.8 d",
            },
            Mass = 260.104,
            MassNumber = 260,
            ModeOfDecay = {
                "sf",
            },
            Name = "260Md",
        },
    },
    MeltingPointK = 1100,
    Name = "Mendelevium",
    NeutronsApprox = 157,
    Period = 7,
    Protons = 101,
    RepresentativeMassNumber = 258,
    StateAt293K = "Solid",
    Symbol = "Md",
    Uses = "Mendelevium is used only for research.",
}

return Mendelevium
