local Mercury = {
    Appearance = "A liquid, silvery metal.",
    AtomicMass = 200.59,
    AtomicNumber = 80,
    AtomicRadius = 2.23,
    Block = "d",
    BoilingPointK = 629.769,
    Category = "Transition",
    CovalentRadius = 1.32,
    ElectronConfiguration = "[Xe] 4f145d106s2",
    Electronegativity = 1.9,
    Density = 13.534,
    Electrons = 80,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        2,
    },
    Group = "12",
    IonizationEnergies = {
        1007.066,
        1809.756,
        3299.8,
    },
    Isotopes = {
        {
            HalfLife = {
                "> 2.5 x 1018 y",
            },
            Mass = 195.966,
            MassNumber = 196,
            ModeOfDecay = {
                "alpha",
            },
            Name = "196Hg",
            NaturalAbundance = 0.15,
        },
        {
            HalfLife = {},
            Mass = 197.967,
            MassNumber = 198,
            ModeOfDecay = {},
            Name = "198Hg",
            NaturalAbundance = 9.97,
        },
        {
            HalfLife = {},
            Mass = 198.968,
            MassNumber = 199,
            ModeOfDecay = {},
            Name = "199Hg",
            NaturalAbundance = 16.87,
        },
        {
            HalfLife = {},
            Mass = 199.968,
            MassNumber = 200,
            ModeOfDecay = {},
            Name = "200Hg",
            NaturalAbundance = 23.1,
        },
        {
            HalfLife = {},
            Mass = 200.97,
            MassNumber = 201,
            ModeOfDecay = {},
            Name = "201Hg",
            NaturalAbundance = 13.18,
        },
        {
            HalfLife = {},
            Mass = 201.971,
            MassNumber = 202,
            ModeOfDecay = {},
            Name = "202Hg",
            NaturalAbundance = 29.86,
        },
        {
            HalfLife = {},
            Mass = 203.973,
            MassNumber = 204,
            ModeOfDecay = {},
            Name = "204Hg",
            NaturalAbundance = 6.87,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 201.971,
            MassNumber = 202,
            ModeOfDecay = {},
            Name = "202Hg",
            NaturalAbundance = 29.86,
        },
    },
    MeltingPointK = 234.321,
    Name = "Mercury",
    NeutronsApprox = 122,
    Period = 6,
    Protons = 80,
    RepresentativeMassNumber = 202,
    StateAt293K = "Liquid",
    Symbol = "Hg",
    Uses = "Mercury has fascinated people for millennia, as a heavy liquid metal. However, because of its toxicity, many uses of mercury are being phased out or are under review.\
\
It is now mainly used in the chemical industry as catalysts. It is also used in some electrical switches and rectifiers.\
\
Previously its major use was in the manufacture of sodium hydroxide and chlorine by electrolysis of brine. These plants will all be phased out by 2020. It was also commonly used in batteries, fluorescent lights, felt production, thermometers and barometers. Again, these uses have been phased out.\
\
Mercury easily forms alloys, called amalgams, with other metals such as gold, silver and tin. The ease with which it amalgamates with gold made it useful in recovering gold from its ores. Mercury amalgams were also used in dental fillings.\
\
Mercuric sulfide (vermilion) is a high-grade, bright-red paint pigment, but is very toxic so is now only used with great care.",
}

return Mercury
