local Moscovium = {
    Name = "Moscovium",
    Symbol = "Mc",
    AtomicNumber = 115,
    AtomicMass = -290,
    RepresentativeMassNumber = 289,
    Protons = 115,
    Electrons = 115,
    NeutronsApprox = 174,
    Category = "Other",
    Group = "15",
    Period = 7,
    Block = "p",
    StateAt293K = "Solid",
    Density = 13.5,
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made.",
    Uses = {
        "At present, it is only used in research.",
    },
    ElectronConfiguration = "[Rn] 5f146d107s27p3",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        18,
        5,
    },
    CovalentRadius = 1.62,
    IonizationEnergies = {},
    KeyIsotopes = {
        {
            Name = "289Mc",
            HalfLife = {},
            Mass = 289.194,
            MassNumber = 289,
            ModeOfDecay = {},
        },
    },
    Isotopes = {
        {
            Name = "288Mc",
            HalfLife = {
                "~ 0.09 s",
            },
            Mass = 288.193,
            MassNumber = 288,
            ModeOfDecay = {
                "alpha",
            },
        },
        {
            Name = "289Mc",
            HalfLife = {},
            Mass = 289.194,
            MassNumber = 289,
            ModeOfDecay = {},
        },
    },
}

return Moscovium
