local Moscovium = {
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made.",
    AtomicMass = -290,
    AtomicNumber = 115,
    Block = "p",
    Category = "Other",
    CovalentRadius = 1.62,
    ElectronConfiguration = "[Rn] 5f146d107s27p3",
    Density = 13.5,
    Electrons = 115,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        18,
        5,
    },
    Group = "15",
    IonizationEnergies = {},
    Isotopes = {
        {
            HalfLife = {
                "~ 0.09 s",
            },
            Mass = 288.193,
            MassNumber = 288,
            ModeOfDecay = {
                "alpha",
            },
            Name = "288Mc",
        },
        {
            HalfLife = {},
            Mass = 289.194,
            MassNumber = 289,
            ModeOfDecay = {},
            Name = "289Mc",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 289.194,
            MassNumber = 289,
            ModeOfDecay = {},
            Name = "289Mc",
        },
    },
    Name = "Moscovium",
    NeutronsApprox = 174,
    Period = 7,
    Protons = 115,
    RepresentativeMassNumber = 289,
    StateAt293K = "Solid",
    Symbol = "Mc",
    Uses = "At present, it is only used in research.",
}

return Moscovium
