local Neodymium = {
    Appearance = "A silvery-white metal. It rapidly tarnishes in air.",
    AtomicMass = 144.24,
    AtomicNumber = 60,
    AtomicRadius = 2.39,
    Block = "f",
    BoilingPointK = 3347,
    Category = "Lanthanoid",
    CovalentRadius = 1.88,
    ElectronConfiguration = "[Xe] 4f46s2",
    Electronegativity = 1.14,
    Density = 7.01,
    Electrons = 60,
    EnergyLevels = {
        2,
        8,
        18,
        22,
        8,
        2,
    },
    Group = "Lanthanides",
    IonizationEnergies = {
        533.082,
        1034.32,
        2132.3,
        3898,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 141.908,
            MassNumber = 142,
            ModeOfDecay = {},
            Name = "142Nd",
            NaturalAbundance = 27.2,
        },
        {
            HalfLife = {},
            Mass = 142.91,
            MassNumber = 143,
            ModeOfDecay = {},
            Name = "143Nd",
            NaturalAbundance = 12.2,
        },
        {
            HalfLife = {
                "2.1 x 1015 y",
            },
            Mass = 143.91,
            MassNumber = 144,
            ModeOfDecay = {
                "a",
            },
            Name = "144Nd",
            NaturalAbundance = 23.8,
        },
        {
            HalfLife = {},
            Mass = 144.913,
            MassNumber = 145,
            ModeOfDecay = {},
            Name = "145Nd",
            NaturalAbundance = 8.3,
        },
        {
            HalfLife = {},
            Mass = 145.913,
            MassNumber = 146,
            ModeOfDecay = {},
            Name = "146Nd",
            NaturalAbundance = 17.2,
        },
        {
            HalfLife = {},
            Mass = 147.917,
            MassNumber = 148,
            ModeOfDecay = {},
            Name = "148Nd",
            NaturalAbundance = 5.8,
        },
        {
            HalfLife = {
                "1.33 x 1020 y",
            },
            Mass = 149.921,
            MassNumber = 150,
            ModeOfDecay = {
                "beta-beta-",
            },
            Name = "150Nd",
            NaturalAbundance = 5.6,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 141.908,
            MassNumber = 142,
            ModeOfDecay = {},
            Name = "142Nd",
            NaturalAbundance = 27.2,
        },
    },
    MeltingPointK = 1289,
    Name = "Neodymium",
    NeutronsApprox = 82,
    Period = 6,
    Protons = 60,
    RepresentativeMassNumber = 142,
    StateAt293K = "Solid",
    Symbol = "Nd",
    Uses = "The most important use for neodymium is in an alloy with iron and boron to make very strong permanent magnets. This discovery, in 1983, made it possible to miniaturise many electronic devices, including mobile phones, microphones, loudspeakers and electronic musical instruments. These magnets are also used in car windscreen wipers and wind turbines.\
\
Neodymium is a component, along with praseodymium, of didymium glass. This is a special glass for goggles used during glass blowing and welding. The element colours glass delicate shades of violet, wine-red and grey. Neodymium is also used in the glass for tanning booths, since it transmits the tanning UV rays but not the heating infrared rays. \
\
Neodymium glass is used to make lasers. These are used as laser pointers, as well as in eye surgery, cosmetic surgery and for the treatment of skin cancers. \
\
Neodymium oxide and nitrate are used as catalysts in polymerisation reactions.",
}

return Neodymium
