local Neon = {
    Appearance = "A colourless, odourless gas. Neon will not react with any other substance.",
    AtomicMass = 20.18,
    AtomicNumber = 10,
    AtomicRadius = 1.54,
    Block = "p",
    BoilingPointK = 27.104,
    Category = "Noble",
    CovalentRadius = 0.62,
    ElectronConfiguration = "[He] 2s22p6",
    Density = 0.9002,
    Electrons = 10,
    EnergyLevels = {
        2,
        8,
    },
    Group = "18",
    IonizationEnergies = {
        2080.662,
        3952.325,
        6121.99,
        9370.66,
        12177.41,
        15237.93,
        19999.086,
        23069.539,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 19.992,
            MassNumber = 20,
            ModeOfDecay = {},
            Name = "20Ne",
            NaturalAbundance = 90.48,
        },
        {
            HalfLife = {},
            Mass = 20.994,
            MassNumber = 21,
            ModeOfDecay = {},
            Name = "21Ne",
            NaturalAbundance = 0.27,
        },
        {
            HalfLife = {},
            Mass = 21.991,
            MassNumber = 22,
            ModeOfDecay = {},
            Name = "22Ne",
            NaturalAbundance = 9.25,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 19.992,
            MassNumber = 20,
            ModeOfDecay = {},
            Name = "20Ne",
            NaturalAbundance = 90.48,
        },
    },
    MeltingPointK = 24.56,
    Name = "Neon",
    NeutronsApprox = 10,
    Period = 2,
    Protons = 10,
    RepresentativeMassNumber = 20,
    StateAt293K = "Gas",
    Symbol = "Ne",
    Uses = "The largest use of neon is in making the ubiquitous 'neon signs' for advertising. In a vacuum discharge tube neon glows a reddish orange colour. Only the red signs actually contain pure neon. Others contain different gases to give different colours.\
\
Neon is also used to make high-voltage indicators and switching gear, lightning arresters, diving equipment and lasers. \
\
Liquid neon is an important cryogenic refrigerant. It has over 40 times more refrigerating capacity per unit volume than liquid helium, and more than 3 times that of liquid hydrogen.",
}

return Neon
