local Nickel = {
    Appearance = "A silvery metal that resists corrosion even at high temperatures.",
    AtomicMass = 58.693,
    AtomicNumber = 28,
    AtomicRadius = 1.97,
    Block = "d",
    BoilingPointK = 3186,
    Category = "Transition",
    CovalentRadius = 1.17,
    ElectronAffinity = 111.537,
    ElectronConfiguration = "[Ar] 3d84s2",
    Electronegativity = 1.91,
    Density = 8.908,
    Electrons = 28,
    EnergyLevels = {
        2,
        8,
        16,
        2,
    },
    Group = "10",
    IonizationEnergies = {
        737.129,
        1753.027,
        3395.32,
        5297,
        7338.67,
        10420,
        12833,
        15631,
    },
    Isotopes = {
        {
            HalfLife = {
                "> 4 x 1019 y",
            },
            Mass = 57.935,
            MassNumber = 58,
            ModeOfDecay = {
                "EC-EC",
            },
            Name = "58Ni",
            NaturalAbundance = 68.077,
        },
        {
            HalfLife = {},
            Mass = 59.931,
            MassNumber = 60,
            ModeOfDecay = {},
            Name = "60Ni",
            NaturalAbundance = 26.223,
        },
        {
            HalfLife = {},
            Mass = 60.931,
            MassNumber = 61,
            ModeOfDecay = {},
            Name = "61Ni",
            NaturalAbundance = 1.1399,
        },
        {
            HalfLife = {},
            Mass = 61.928,
            MassNumber = 62,
            ModeOfDecay = {},
            Name = "62Ni",
            NaturalAbundance = 3.6346,
        },
        {
            HalfLife = {},
            Mass = 63.928,
            MassNumber = 64,
            ModeOfDecay = {},
            Name = "64Ni",
            NaturalAbundance = 0.9255,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "> 4 x 1019 y",
            },
            Mass = 57.935,
            MassNumber = 58,
            ModeOfDecay = {
                "EC-EC",
            },
            Name = "58Ni",
            NaturalAbundance = 68.077,
        },
    },
    MeltingPointK = 1728,
    Name = "Nickel",
    NeutronsApprox = 30,
    Period = 4,
    Protons = 28,
    RepresentativeMassNumber = 58,
    StateAt293K = "Solid",
    Symbol = "Ni",
    Uses = "Nickel resists corrosion and is used to plate other metals to protect them. It is, however, mainly used in making alloys such as stainless steel. Nichrome is an alloy of nickel and chromium with small amounts of silicon, manganese and iron. It resists corrosion, even when red hot, so is used in toasters and electric ovens. A copper-nickel alloy is commonly used in desalination plants, which convert seawater into fresh water. Nickel steel is used for armour plating. Other alloys of nickel are used in boat propeller shafts and turbine blades.\
\
Nickel is used in batteries, including rechargeable nickel-cadmium batteries and nickel-metal hydride batteries used in hybrid vehicles.\
\
Nickel has a long history of being used in coins. The US five-cent piece (known as a 'nickel') is 25% nickel and 75% copper. \
\
Finely divided nickel is used as a catalyst for hydrogenating vegetable oils. Adding nickel to glass gives it a green colour.",
}

return Nickel
