local Nihonium = {
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made.",
    AtomicMass = -286,
    AtomicNumber = 113,
    Block = "p",
    Category = "Other",
    CovalentRadius = 1.36,
    ElectronConfiguration = "[Rn] 5f146d107s27p1",
    Density = 16,
    Electrons = 113,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        18,
        3,
    },
    Group = "13",
    IonizationEnergies = {},
    Isotopes = {
        {
            HalfLife = {
                "~ 0.48 s",
            },
            Mass = 284.179,
            MassNumber = 284,
            ModeOfDecay = {
                "alpha",
            },
            Name = "284Nh",
        },
        {
            HalfLife = {},
            Mass = 286.182,
            MassNumber = 286,
            ModeOfDecay = {},
            Name = "286Nh",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 286.182,
            MassNumber = 286,
            ModeOfDecay = {},
            Name = "286Nh",
        },
    },
    Name = "Nihonium",
    NeutronsApprox = 173,
    Period = 7,
    Protons = 113,
    RepresentativeMassNumber = 286,
    StateAt293K = "Solid",
    Symbol = "Nh",
    Uses = "At present, it is only used in research.",
}

return Nihonium
