local Nihonium = {
    Name = "Nihonium",
    Symbol = "Nh",
    AtomicNumber = 113,
    AtomicMass = -286,
    RepresentativeMassNumber = 286,
    Protons = 113,
    Electrons = 113,
    NeutronsApprox = 173,
    Category = "Other",
    Group = "13",
    Period = 7,
    Block = "p",
    StateAt293K = "Solid",
    Density = 16,
    Appearance = {
        "A highly radioactive metal, of which only a few atoms have ever been made.",
    },
    Uses = {
        "At present, it is only used in research.",
    },
    ElectronConfiguration = "[Rn] 5f146d107s27p1",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        18,
        3,
    },
    CovalentRadius = 1.36,
    IonizationEnergies = {},
    KeyIsotopes = {
        {
            Name = "286Nh",
            HalfLife = {},
            Mass = 286.182,
            MassNumber = 286,
            ModeOfDecay = {},
        },
    },
    Isotopes = {
        {
            Name = "284Nh",
            HalfLife = {
                "~ 0.48 s",
            },
            Mass = 284.179,
            MassNumber = 284,
            ModeOfDecay = {
                "alpha",
            },
        },
        {
            Name = "286Nh",
            HalfLife = {},
            Mass = 286.182,
            MassNumber = 286,
            ModeOfDecay = {},
        },
    },
}

return Nihonium
