local Niobium = {
    Appearance = "A silvery metal that is very resistant to corrosion due to a layer of oxide on its surface.",
    AtomicMass = 92.906,
    AtomicNumber = 41,
    AtomicRadius = 2.18,
    Block = "d",
    BoilingPointK = 5014,
    Category = "Transition",
    CovalentRadius = 1.56,
    ElectronAffinity = 88.381,
    ElectronConfiguration = "[Kr] 4d45s1",
    Electronegativity = 1.6,
    Density = 8.57,
    Electrons = 41,
    EnergyLevels = {
        2,
        8,
        18,
        12,
        1,
    },
    Group = "5",
    IonizationEnergies = {
        652.13,
        1351,
        2415.99,
        3695.4,
        4877.33,
        9847.004,
        12061,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 92.906,
            MassNumber = 93,
            ModeOfDecay = {},
            Name = "93Nb",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 92.906,
            MassNumber = 93,
            ModeOfDecay = {},
            Name = "93Nb",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 2750,
    Name = "Niobium",
    NeutronsApprox = 52,
    Period = 5,
    Protons = 41,
    RepresentativeMassNumber = 93,
    StateAt293K = "Solid",
    Symbol = "Nb",
    Uses = "Niobium is used in alloys including stainless steel. It improves the strength of the alloys, particularly at low temperatures. Alloys containing niobium are used in jet engines and rockets, beams and girders for buildings and oil rigs, and oil and gas pipelines. \
\
This element also has superconducting properties. It is used in superconducting magnets for particle accelerators, MRI scanners and NMR equipment. \
\
Niobium oxide compounds are added to glass to increase the refractive index, which allows corrective glasses to be made with thinner lenses.",
}

return Niobium
