local Nitrogen = {
    Appearance = "A colourless, odourless gas.",
    AtomicMass = 14.007,
    AtomicNumber = 7,
    AtomicRadius = 1.55,
    Block = "p",
    BoilingPointK = 77.355,
    Category = "Nonmetal",
    CovalentRadius = 0.71,
    ElectronConfiguration = "[He] 2s22p3",
    Electronegativity = 3.04,
    Density = 1.251,
    Electrons = 7,
    EnergyLevels = {
        2,
        5,
    },
    Group = "15",
    IonizationEnergies = {
        1402.328,
        2856.092,
        4578.156,
        7475.057,
        9444.969,
        53266.835,
        64360.16,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 14.003,
            MassNumber = 14,
            ModeOfDecay = {},
            Name = "14N",
            NaturalAbundance = 99.636,
        },
        {
            HalfLife = {},
            Mass = 15,
            MassNumber = 15,
            ModeOfDecay = {},
            Name = "15N",
            NaturalAbundance = 0.364,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 14.003,
            MassNumber = 14,
            ModeOfDecay = {},
            Name = "14N",
            NaturalAbundance = 99.636,
        },
    },
    MeltingPointK = 63.2,
    Name = "Nitrogen",
    NeutronsApprox = 7,
    Period = 2,
    Protons = 7,
    RepresentativeMassNumber = 14,
    StateAt293K = "Gas",
    Symbol = "N",
    Uses = "Nitrogen is important to the chemical industry. It is used to make fertilisers, nitric acid, nylon, dyes and explosives. To make these products, nitrogen must first be reacted with hydrogen to produce ammonia. This is done by the Haber process. 150 million tonnes of ammonia are produced in this way every year.  \
\
Nitrogen gas is also used to provide an unreactive atmosphere. It is used in this way to preserve foods, and in the electronics industry during the production of transistors and diodes. Large quantities of nitrogen are used in annealing stainless steel and other steel mill products. Annealing is a heat treatment that makes steel easier to work.\
\
Liquid nitrogen is often used as a refrigerant. It is used for storing sperm, eggs and other cells for medical research and reproductive technology. It is also used to rapidly freeze foods, helping them to maintain moisture, colour, flavour and texture.",
}

return Nitrogen
