local Nobelium = {
    Appearance = "Nobelium is a radioactive metal. Only a few atoms have ever been made. Its half-life is only 58 minutes.",
    AtomicMass = -259,
    AtomicNumber = 102,
    AtomicRadius = 2.46,
    Block = "f",
    Category = "Actinoid",
    CovalentRadius = 1.76,
    ElectronConfiguration = "[Rn] 5f147s2",
    Density = nil,
    Electrons = 102,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        8,
        2,
    },
    Group = "Actinides",
    IonizationEnergies = {
        641.63,
    },
    Isotopes = {
        {
            HalfLife = {
                "58 m",
            },
            Mass = 259.101,
            MassNumber = 259,
            ModeOfDecay = {
                "alpha",
                "EC",
                "sf",
            },
            Name = "259No",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "58 m",
            },
            Mass = 259.101,
            MassNumber = 259,
            ModeOfDecay = {
                "alpha",
                "EC",
                "sf",
            },
            Name = "259No",
        },
    },
    MeltingPointK = 1100,
    Name = "Nobelium",
    NeutronsApprox = 157,
    Period = 7,
    Protons = 102,
    RepresentativeMassNumber = 259,
    StateAt293K = "Solid",
    Symbol = "No",
    Uses = "Nobelium has no uses outside research.",
}

return Nobelium
