local Oganesson = {
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made.",
    AtomicMass = -294,
    AtomicNumber = 118,
    Block = "p",
    Category = "Other",
    CovalentRadius = 1.57,
    ElectronAffinity = 5.403,
    ElectronConfiguration = "[Rn] 5f146d107s27p6",
    Density = 4.95,
    Electrons = 118,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        18,
        8,
    },
    Group = "18",
    IonizationEnergies = {},
    Isotopes = {
        {
            HalfLife = {
                "0.9 s",
            },
            Mass = 294.214,
            MassNumber = 294,
            ModeOfDecay = {
                "alpha",
            },
            Name = "294Og",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "0.9 s",
            },
            Mass = 294.214,
            MassNumber = 294,
            ModeOfDecay = {
                "alpha",
            },
            Name = "294Og",
        },
    },
    Name = "Oganesson",
    NeutronsApprox = 176,
    Period = 7,
    Protons = 118,
    RepresentativeMassNumber = 294,
    StateAt293K = "Solid",
    Symbol = "Og",
    Uses = "At present, it is only used in research.",
}

return Oganesson
