local Oganesson = {
    Name = "Oganesson",
    Symbol = "Og",
    AtomicNumber = 118,
    AtomicMass = -294,
    RepresentativeMassNumber = 294,
    Protons = 118,
    Electrons = 118,
    NeutronsApprox = 176,
    Category = "Other",
    Group = "18",
    Period = 7,
    Block = "p",
    StateAt293K = "Solid",
    Density = 4.95,
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made.",
    Uses = {
        "At present, it is only used in research.",
    },
    ElectronConfiguration = "[Rn] 5f146d107s27p6",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        18,
        8,
    },
    CovalentRadius = 1.57,
    ElectronAffinity = 5.403,
    IonizationEnergies = {},
    KeyIsotopes = {
        {
            Name = "294Og",
            HalfLife = {
                "0.9 s",
            },
            Mass = 294.214,
            MassNumber = 294,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
    Isotopes = {
        {
            Name = "294Og",
            HalfLife = {
                "0.9 s",
            },
            Mass = 294.214,
            MassNumber = 294,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
}

return Oganesson
