local Platinum = {
    Appearance = "A shiny, silvery-white metal as resistant to corrosion as gold.",
    AtomicMass = 195.08,
    AtomicNumber = 78,
    AtomicRadius = 2.13,
    Block = "d",
    BoilingPointK = 4098,
    Category = "Transition",
    CovalentRadius = 1.3,
    ElectronAffinity = 205.321,
    ElectronConfiguration = "[Xe] 4f145d96s1",
    Electronegativity = 2.2,
    Density = 21.45,
    Electrons = 78,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        17,
        1,
    },
    Group = "10",
    IonizationEnergies = {
        864.393,
        1791.057,
    },
    Isotopes = {
        {
            HalfLife = {
                "4.5 x 1011 y",
            },
            Mass = 189.96,
            MassNumber = 190,
            ModeOfDecay = {
                "alpha",
            },
            Name = "190Pt",
            NaturalAbundance = 0.012,
        },
        {
            HalfLife = {},
            Mass = 191.961,
            MassNumber = 192,
            ModeOfDecay = {},
            Name = "192Pt",
            NaturalAbundance = 0.782,
        },
        {
            HalfLife = {},
            Mass = 193.963,
            MassNumber = 194,
            ModeOfDecay = {},
            Name = "194Pt",
            NaturalAbundance = 32.86,
        },
        {
            HalfLife = {},
            Mass = 194.965,
            MassNumber = 195,
            ModeOfDecay = {},
            Name = "195Pt",
            NaturalAbundance = 33.78,
        },
        {
            HalfLife = {},
            Mass = 195.965,
            MassNumber = 196,
            ModeOfDecay = {},
            Name = "196Pt",
            NaturalAbundance = 25.21,
        },
        {
            HalfLife = {},
            Mass = 197.968,
            MassNumber = 198,
            ModeOfDecay = {},
            Name = "198Pt",
            NaturalAbundance = 7.356,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 194.965,
            MassNumber = 195,
            ModeOfDecay = {},
            Name = "195Pt",
            NaturalAbundance = 33.78,
        },
    },
    MeltingPointK = 2041.4,
    Name = "Platinum",
    NeutronsApprox = 117,
    Period = 6,
    Protons = 78,
    RepresentativeMassNumber = 195,
    StateAt293K = "Solid",
    Symbol = "Pt",
    Uses = "Platinum is used extensively for jewellery. Its main use, however, is in catalytic converters for cars, trucks and buses. This accounts for about 50% of demand each year. Platinum is very effective at converting emissions from the vehicle's engine into less harmful waste products. \
\
Platinum is used in the chemicals industry as a catalyst for the production of nitric acid, silicone and benzene. It is also used as a catalyst to improve the efficiency of fuel cells.\
\
The electronics industry uses platinum for computer hard disks and thermocouples. \
\
Platinum is also used to make optical fibres and LCDs, turbine blades, spark plugs, pacemakers and dental fillings.\
\
Platinum compounds are important chemotherapy drugs used to treat cancers.",
}

return Platinum
