local Plutonium = {
    Name = "Plutonium",
    Symbol = "Pu",
    AtomicNumber = 94,
    AtomicMass = -244,
    RepresentativeMassNumber = 238,
    Protons = 94,
    Electrons = 94,
    NeutronsApprox = 144,
    Category = "Actinoid",
    Group = "Actinides",
    Period = 7,
    Block = "f",
    StateAt293K = "Solid",
    Density = 19.816,
    Appearance = "A radioactive, silvery metal.",
    Uses = {
        "Plutonium was used in several of the first atomic bombs, and is still used in nuclear weapons. The complete detonation of a kilogram of plutonium produces an explosion equivalent to over 10,000 tonnes of chemical explosive.",
        "Plutonium is also a key material in the development of nuclear power. It has been used as a source of energy on space missions, such as the Mars Curiosity Rover and the New Horizons spacecraft on its way to Pluto.",
    },
    ElectronConfiguration = "[Rn] 5f67s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        24,
        8,
        2,
    },
    AtomicRadius = 2.43,
    CovalentRadius = 1.8,
    Electronegativity = 1.3,
    IonizationEnergies = {
        581.421,
        1080.6,
    },
    MeltingPointK = 913,
    BoilingPointK = 3501,
    KeyIsotopes = {
        {
            Name = "238Pu",
            HalfLife = {
                "87.7 y",
                "4.75 x 1010 y",
            },
            Mass = 238.05,
            MassNumber = 238,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
        {
            Name = "239Pu",
            HalfLife = {
                "2.410 x 104 y",
                "8 x 105 y",
            },
            Mass = 239.052,
            MassNumber = 239,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
        {
            Name = "240Pu",
            HalfLife = {
                "6.56 x 103 y",
                "1.14 x 1011 y",
            },
            Mass = 240.054,
            MassNumber = 240,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
    },
    Isotopes = {
        {
            Name = "238Pu",
            HalfLife = {
                "87.7 y",
                "4.75 x 1010 y",
            },
            Mass = 238.05,
            MassNumber = 238,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
        {
            Name = "239Pu",
            HalfLife = {
                "2.410 x 104 y",
                "8 x 105 y",
            },
            Mass = 239.052,
            MassNumber = 239,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
        {
            Name = "240Pu",
            HalfLife = {
                "6.56 x 103 y",
                "1.14 x 1011 y",
            },
            Mass = 240.054,
            MassNumber = 240,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
        {
            Name = "241Pu",
            HalfLife = {
                "14.33 y",
                nil,
                "> 6 x 1016 y",
            },
            Mass = 241.057,
            MassNumber = 241,
            ModeOfDecay = {
                "beta-",
                "alpha",
                "sf",
            },
        },
        {
            Name = "242Pu",
            HalfLife = {
                "3.75 x 105 y",
                "6.77 x 1010 y",
            },
            Mass = 242.059,
            MassNumber = 242,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
        {
            Name = "244Pu",
            HalfLife = {
                "8.12 x 107 y",
                "6.6 x 1010 y",
            },
            Mass = 244.064,
            MassNumber = 244,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
    },
}

return Plutonium
