local Polonium = {
    Appearance = "A silvery-grey, radioactive semi-metal.",
    AtomicMass = -209,
    AtomicNumber = 84,
    AtomicRadius = 1.97,
    Block = "p",
    BoilingPointK = 1235,
    Category = "Poor",
    CovalentRadius = 1.42,
    ElectronAffinity = 183.3,
    ElectronConfiguration = "[Xe] 4f145d106s26p4",
    Electronegativity = 2,
    Density = 9.196,
    Electrons = 84,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        6,
    },
    Group = "16",
    IonizationEnergies = {
        811.828,
    },
    Isotopes = {
        {
            HalfLife = {
                "128 y",
            },
            Mass = 208.982,
            MassNumber = 209,
            ModeOfDecay = {
                "alpha",
            },
            Name = "209Po",
        },
        {
            HalfLife = {
                "138.4 d",
            },
            Mass = 209.983,
            MassNumber = 210,
            ModeOfDecay = {
                "alpha",
            },
            Name = "210Po",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "128 y",
            },
            Mass = 208.982,
            MassNumber = 209,
            ModeOfDecay = {
                "alpha",
            },
            Name = "209Po",
        },
        {
            HalfLife = {
                "138.4 d",
            },
            Mass = 209.983,
            MassNumber = 210,
            ModeOfDecay = {
                "alpha",
            },
            Name = "210Po",
        },
    },
    MeltingPointK = 527,
    Name = "Polonium",
    NeutronsApprox = 125,
    Period = 6,
    Protons = 84,
    RepresentativeMassNumber = 209,
    StateAt293K = "Solid",
    Symbol = "Po",
    Uses = "Polonium is an alpha-emitter, and is used as an alpha-particle source in the form of a thin film on a stainless steel disc. These are used in antistatic devices and for research purposes. \
\
A single gram of polonium will reach a temperature of 500C as a result of the alpha radiation emitted. This makes it useful as a source of heat for space equipment. \
\
It can be mixed or alloyed with beryllium to provide a source of neutrons.",
}

return Polonium
