local Praseodymium = {
    Appearance = "A soft, silvery metal.",
    AtomicMass = 140.91,
    AtomicNumber = 59,
    AtomicRadius = 2.4,
    Block = "f",
    BoilingPointK = 3793,
    Category = "Lanthanoid",
    CovalentRadius = 1.9,
    ElectronAffinity = 92.819,
    ElectronConfiguration = "[Xe] 4f36s2",
    Electronegativity = 1.13,
    Density = 6.77,
    Electrons = 59,
    EnergyLevels = {
        2,
        8,
        18,
        21,
        8,
        2,
    },
    Group = "Lanthanides",
    IonizationEnergies = {
        528.064,
        1017.92,
        2086.399,
        3761,
        5550.8,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 140.908,
            MassNumber = 141,
            ModeOfDecay = {},
            Name = "141Pr",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 140.908,
            MassNumber = 141,
            ModeOfDecay = {},
            Name = "141Pr",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 1204,
    Name = "Praseodymium",
    NeutronsApprox = 82,
    Period = 6,
    Protons = 59,
    RepresentativeMassNumber = 141,
    StateAt293K = "Solid",
    Symbol = "Pr",
    Uses = "Praseodymium is used in a variety of alloys. The high-strength alloy it forms with magnesium is used in aircraft engines. Mischmetal is an alloy containing about 5% praseodymium and is used to make flints for cigarette lighters. Praseodymium is also used in alloys for permanent magnets.\
\
Along with other lanthanide elements, it is used in carbon arc electrodes for studio lighting and projection. \
\
Praseodymium salts are used to colour glasses, enamel and glazes an intense and unusually clean yellow. Praseodymium oxide is a component of didymium glass (along with neodymium). This glass is used in goggles used by welders and glassmakers, because it filters out the yellow light and infrared (heat) radiation.",
}

return Praseodymium
