local Promethium = {
    Name = "Promethium",
    Symbol = "Pm",
    AtomicNumber = 61,
    AtomicMass = -145,
    RepresentativeMassNumber = 145,
    Protons = 61,
    Electrons = 61,
    NeutronsApprox = 84,
    Category = "Lanthanoid",
    Group = "Lanthanides",
    Period = 6,
    Block = "f",
    StateAt293K = "Solid",
    Density = 7.26,
    Appearance = {
        "A radioactive metal.",
    },
    Uses = {
        "Most promethium is used only in research. A little promethium is used in specialised atomic batteries. These are roughly the size of a drawing pin and are used for pacemakers, guided missiles and radios. The radioactive decay of promethium is used to make a phosphor give off light and this light is converted into electricity by a solar cell.",
        "Promethium can also be used as a source of x-rays and radioactivity in measuring instruments.",
    },
    ElectronConfiguration = "[Xe] 4f56s2",
    EnergyLevels = {
        2,
        8,
        18,
        23,
        8,
        2,
    },
    AtomicRadius = 2.38,
    CovalentRadius = 1.86,
    IonizationEnergies = {
        538.581,
        1051.7,
        2151.6,
        3965.5,
    },
    MeltingPointK = 1315,
    BoilingPointK = 3273,
    KeyIsotopes = {
        {
            Name = "145Pm",
            HalfLife = {
                "17.7 y",
            },
            Mass = 144.913,
            MassNumber = 145,
            ModeOfDecay = {
                "EC",
            },
        },
        {
            Name = "147Pm",
            HalfLife = {
                "2.623 y",
            },
            Mass = 146.915,
            MassNumber = 147,
            ModeOfDecay = {
                "beta-",
            },
        },
    },
    Isotopes = {
        {
            Name = "145Pm",
            HalfLife = {
                "17.7 y",
            },
            Mass = 144.913,
            MassNumber = 145,
            ModeOfDecay = {
                "EC",
            },
        },
        {
            Name = "147Pm",
            HalfLife = {
                "2.623 y",
            },
            Mass = 146.915,
            MassNumber = 147,
            ModeOfDecay = {
                "beta-",
            },
        },
    },
}

return Promethium
