local Protactinium = {
    Appearance = "A silvery, radioactive metal.",
    AtomicMass = 231.04,
    AtomicNumber = 91,
    AtomicRadius = 2.43,
    Block = "f",
    BoilingPointK = 4273,
    Category = "Actinoid",
    CovalentRadius = 1.84,
    ElectronConfiguration = "[Rn] 5f26d17s2",
    Electronegativity = 1.5,
    Density = 15.37,
    Electrons = 91,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        20,
        9,
        2,
    },
    Group = "Actinides",
    IonizationEnergies = {
        568.3,
    },
    Isotopes = {
        {
            HalfLife = {
                "3.25 x 104 y",
                "> 2 x 1017 y",
            },
            Mass = 231.036,
            MassNumber = 231,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "231Pa",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "3.25 x 104 y",
                "> 2 x 1017 y",
            },
            Mass = 231.036,
            MassNumber = 231,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "231Pa",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 1845,
    Name = "Protactinium",
    NeutronsApprox = 140,
    Period = 7,
    Protons = 91,
    RepresentativeMassNumber = 231,
    StateAt293K = "Solid",
    Symbol = "Pa",
    Uses = "Protactinium is little used outside of research.",
}

return Protactinium
