local Radium = {
    Appearance = "A soft, shiny and silvery radioactive metal.",
    AtomicMass = -226,
    AtomicNumber = 88,
    AtomicRadius = 2.83,
    Block = "s",
    BoilingPointK = 1773,
    Category = "Alkaline",
    CovalentRadius = 2.11,
    ElectronAffinity = 9.65,
    ElectronConfiguration = "[Rn] 7s2",
    Electronegativity = 0.9,
    Density = 5.5,
    Electrons = 88,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        8,
        2,
    },
    Group = "2",
    IonizationEnergies = {
        509.29,
        979.051,
    },
    Isotopes = {
        {
            HalfLife = {
                "11.43 d",
            },
            Mass = 223.019,
            MassNumber = 223,
            ModeOfDecay = {
                "alpha",
            },
            Name = "223Ra",
        },
        {
            HalfLife = {
                "3.66 d",
            },
            Mass = 224.02,
            MassNumber = 224,
            ModeOfDecay = {
                "alpha",
            },
            Name = "224Ra",
        },
        {
            HalfLife = {
                "1599 y",
                "> 4 x 1018 y",
            },
            Mass = 226.025,
            MassNumber = 226,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "226Ra",
        },
        {
            HalfLife = {
                "5.76 y",
            },
            Mass = 228.031,
            MassNumber = 228,
            ModeOfDecay = {
                "beta-",
                "betaf",
            },
            Name = "228Ra",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "1599 y",
                "> 4 x 1018 y",
            },
            Mass = 226.025,
            MassNumber = 226,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "226Ra",
        },
    },
    MeltingPointK = 969,
    Name = "Radium",
    NeutronsApprox = 138,
    Period = 7,
    Protons = 88,
    RepresentativeMassNumber = 226,
    StateAt293K = "Solid",
    Symbol = "Ra",
    Uses = "Radium now has few uses, because it is so highly radioactive.\
\
Radium-223 is sometimes used to treat prostate cancer that has spread to the bones. Because bones contain calcium and radium is in the same group as calcium, it can be used to target cancerous bone cells. It gives off alpha particles that can kill the cancerous cells. \
\
Radium used to be used in luminous paints, for example in clock and watch dials. Although the alpha rays could not pass through the glass or metal of the watch casing, it is now considered to be too hazardous to be used in this way.",
}

return Radium
