local Radon = {
    Name = "Radon",
    Symbol = "Rn",
    AtomicNumber = 86,
    AtomicMass = -222,
    RepresentativeMassNumber = 211,
    Protons = 86,
    Electrons = 86,
    NeutronsApprox = 125,
    Category = "Noble",
    Group = "18",
    Period = 6,
    Block = "p",
    StateAt293K = "Gas",
    Density = 9.73,
    Appearance = {
        "Radon is a colourless and odourless gas. It is chemically inert, but radioactive.",
    },
    Uses = {
        "Radon decays into radioactive polonium and alpha particles. This emitted radiation made radon useful in cancer therapy. Radon was used in some hospitals to treat tumours by sealing the gas in minute tubes, and implanting these into the tumour, treating the disease in situ. Other, safer treatments are now more commonly used.",
        "In some places, high concentrations of radon can build up indoors, escaping from the ground or from granite buildings. Home testing kits are available which can be sent away for analysis.",
    },
    ElectronConfiguration = "[Xe] 4f145d106s26p6",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        8,
    },
    AtomicRadius = 2.2,
    CovalentRadius = 1.46,
    IonizationEnergies = {
        1037.073,
    },
    MeltingPointK = 202,
    BoilingPointK = 211.5,
    KeyIsotopes = {
        {
            Name = "211Rn",
            HalfLife = {
                "14.6 h",
            },
            Mass = 210.991,
            MassNumber = 211,
            ModeOfDecay = {
                "beta+,EC",
                "alpha",
            },
        },
        {
            Name = "220Rn",
            HalfLife = {
                "55.6 s",
            },
            Mass = 220.011,
            MassNumber = 220,
            ModeOfDecay = {
                "alpha",
            },
        },
        {
            Name = "222Rn",
            HalfLife = {
                "3.823 d",
            },
            Mass = 222.018,
            MassNumber = 222,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
    Isotopes = {
        {
            Name = "211Rn",
            HalfLife = {
                "14.6 h",
            },
            Mass = 210.991,
            MassNumber = 211,
            ModeOfDecay = {
                "beta+,EC",
                "alpha",
            },
        },
        {
            Name = "220Rn",
            HalfLife = {
                "55.6 s",
            },
            Mass = 220.011,
            MassNumber = 220,
            ModeOfDecay = {
                "alpha",
            },
        },
        {
            Name = "222Rn",
            HalfLife = {
                "3.823 d",
            },
            Mass = 222.018,
            MassNumber = 222,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
}

return Radon
