local Rhenium = {
    Name = "Rhenium",
    Symbol = "Re",
    AtomicNumber = 75,
    AtomicMass = 186.21,
    RepresentativeMassNumber = 187,
    Protons = 75,
    Electrons = 75,
    NeutronsApprox = 112,
    Category = "Transition",
    Group = "7",
    Period = 6,
    Block = "d",
    StateAt293K = "Solid",
    Density = 21.02,
    Appearance = {
        "A metal with a very high melting point.  Tungsten is the only metallic element with a higher melting point.",
    },
    Uses = {
        "Rhenium is used as an additive to tungsten- and molybdenum-based alloys to give useful properties. These alloys are used for oven filaments and x-ray machines. It is also used as an electrical contact material as it resists wear and withstands arc corrosion.",
        "Rhenium catalysts are extremely resistant to poisoning (deactivation) and are used for the hydrogenation of fine chemicals. Some rhenium is used in nickel alloys to make single-crystal turbine blades.",
    },
    ElectronConfiguration = "[Xe] 4f145d56s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        13,
        2,
    },
    AtomicRadius = 2.16,
    CovalentRadius = 1.41,
    ElectronAffinity = 14.47,
    Electronegativity = 1.9,
    IonizationEnergies = {
        755.82,
    },
    MeltingPointK = 3458,
    BoilingPointK = 5863,
    KeyIsotopes = {
        {
            Name = "187Re",
            HalfLife = {
                "4.16 x 1010 y",
            },
            Mass = 186.956,
            MassNumber = 187,
            ModeOfDecay = {
                "beta-",
            },
            NaturalAbundance = 62.6,
        },
    },
    Isotopes = {
        {
            Name = "185Re",
            HalfLife = {},
            Mass = 184.953,
            MassNumber = 185,
            ModeOfDecay = {},
            NaturalAbundance = 37.4,
        },
        {
            Name = "187Re",
            HalfLife = {
                "4.16 x 1010 y",
            },
            Mass = 186.956,
            MassNumber = 187,
            ModeOfDecay = {
                "beta-",
            },
            NaturalAbundance = 62.6,
        },
    },
}

return Rhenium
