local Rhenium = {
    Appearance = "A metal with a very high melting point.  Tungsten is the only metallic element with a higher melting point.",
    AtomicMass = 186.21,
    AtomicNumber = 75,
    AtomicRadius = 2.16,
    Block = "d",
    BoilingPointK = 5863,
    Category = "Transition",
    CovalentRadius = 1.41,
    ElectronAffinity = 14.47,
    ElectronConfiguration = "[Xe] 4f145d56s2",
    Electronegativity = 1.9,
    Density = 21.02,
    Electrons = 75,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        13,
        2,
    },
    Group = "7",
    IonizationEnergies = {
        755.82,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 184.953,
            MassNumber = 185,
            ModeOfDecay = {},
            Name = "185Re",
            NaturalAbundance = 37.4,
        },
        {
            HalfLife = {
                "4.16 x 1010 y",
            },
            Mass = 186.956,
            MassNumber = 187,
            ModeOfDecay = {
                "beta-",
            },
            Name = "187Re",
            NaturalAbundance = 62.6,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "4.16 x 1010 y",
            },
            Mass = 186.956,
            MassNumber = 187,
            ModeOfDecay = {
                "beta-",
            },
            Name = "187Re",
            NaturalAbundance = 62.6,
        },
    },
    MeltingPointK = 3458,
    Name = "Rhenium",
    NeutronsApprox = 112,
    Period = 6,
    Protons = 75,
    RepresentativeMassNumber = 187,
    StateAt293K = "Solid",
    Symbol = "Re",
    Uses = "Rhenium is used as an additive to tungsten- and molybdenum-based alloys to give useful properties. These alloys are used for oven filaments and x-ray machines. It is also used as an electrical contact material as it resists wear and withstands arc corrosion. \
\
Rhenium catalysts are extremely resistant to poisoning (deactivation) and are used for the hydrogenation of fine chemicals. Some rhenium is used in nickel alloys to make single-crystal turbine blades.",
}

return Rhenium
