local Rhodium = {
    Appearance = "A hard, shiny, silvery metal.",
    AtomicMass = 102.91,
    AtomicNumber = 45,
    AtomicRadius = 2.1,
    Block = "d",
    BoilingPointK = 3968,
    Category = "Transition",
    CovalentRadius = 1.34,
    ElectronAffinity = 109.704,
    ElectronConfiguration = "[Kr] 4d85s1",
    Electronegativity = 2.28,
    Density = 12.41,
    Electrons = 45,
    EnergyLevels = {
        2,
        8,
        18,
        16,
        1,
    },
    Group = "9",
    IonizationEnergies = {
        719.675,
        1744.45,
        2996.83,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 102.905,
            MassNumber = 103,
            ModeOfDecay = {},
            Name = "103Rh",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 102.905,
            MassNumber = 103,
            ModeOfDecay = {},
            Name = "103Rh",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 2236,
    Name = "Rhodium",
    NeutronsApprox = 58,
    Period = 5,
    Protons = 45,
    RepresentativeMassNumber = 103,
    StateAt293K = "Solid",
    Symbol = "Rh",
    Uses = "The major use of rhodium is in catalytic converters for cars (80%). It reduces nitrogen oxides in exhaust gases. \
\
Rhodium is also used as catalysts in the chemical industry, for making nitric acid, acetic acid and hydrogenation reactions. \
\
It is used to coat optic fibres and optical mirrors, and for crucibles, thermocouple elements and headlight reflectors. It is used as an electrical contact material as it has a low electrical resistance and is highly resistant to corrosion.",
}

return Rhodium
