local Roentgenium = {
    Name = "Roentgenium",
    Symbol = "Rg",
    AtomicNumber = 111,
    AtomicMass = -282,
    RepresentativeMassNumber = 280,
    Protons = 111,
    Electrons = 111,
    NeutronsApprox = 169,
    Category = "Other",
    Group = "11",
    Period = 7,
    Block = "d",
    StateAt293K = "Solid",
    Density = 28.7,
    Appearance = {
        "A highly radioactive metal, of which only a few atoms have ever been made.",
    },
    Uses = {
        "At present, it is only used in research.",
    },
    ElectronConfiguration = "[Rn] 5f146d107s1",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        17,
        2,
    },
    CovalentRadius = 1.21,
    IonizationEnergies = {},
    KeyIsotopes = {
        {
            Name = "280Rg",
            HalfLife = {
                "~ 3.6 s",
            },
            Mass = 280.165,
            MassNumber = 280,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
    Isotopes = {
        {
            Name = "280Rg",
            HalfLife = {
                "~ 3.6 s",
            },
            Mass = 280.165,
            MassNumber = 280,
            ModeOfDecay = {
                "alpha",
            },
        },
    },
}

return Roentgenium
