local Roentgenium = {
    Appearance = "A highly radioactive metal, of which only a few atoms have ever been made.",
    AtomicMass = -282,
    AtomicNumber = 111,
    Block = "d",
    Category = "Other",
    CovalentRadius = 1.21,
    ElectronConfiguration = "[Rn] 5f146d107s1",
    Density = 28.7,
    Electrons = 111,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        17,
        2,
    },
    Group = "11",
    IonizationEnergies = {},
    Isotopes = {
        {
            HalfLife = {
                "~ 3.6 s",
            },
            Mass = 280.165,
            MassNumber = 280,
            ModeOfDecay = {
                "alpha",
            },
            Name = "280Rg",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "~ 3.6 s",
            },
            Mass = 280.165,
            MassNumber = 280,
            ModeOfDecay = {
                "alpha",
            },
            Name = "280Rg",
        },
    },
    Name = "Roentgenium",
    NeutronsApprox = 169,
    Period = 7,
    Protons = 111,
    RepresentativeMassNumber = 280,
    StateAt293K = "Solid",
    Symbol = "Rg",
    Uses = "At present, it is only used in research.",
}

return Roentgenium
