local Rubidium = {
    Appearance = "A soft metal that ignites in the air and reacts violently with water.",
    AtomicMass = 85.468,
    AtomicNumber = 37,
    AtomicRadius = 3.03,
    Block = "s",
    BoilingPointK = 961,
    Category = "Alkali",
    CovalentRadius = 2.15,
    ElectronAffinity = 46.884,
    ElectronConfiguration = "[Kr] 5s1",
    Electronegativity = 0.82,
    Density = 1.532,
    Electrons = 37,
    EnergyLevels = {
        2,
        8,
        18,
        8,
        1,
    },
    Group = "1",
    IonizationEnergies = {
        403.032,
        2633.037,
        3859,
        5075.1,
        6850,
        8143.4,
        9571.3,
        13122,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 84.912,
            MassNumber = 85,
            ModeOfDecay = {},
            Name = "85Rb",
            NaturalAbundance = 72.17,
        },
        {
            HalfLife = {
                "4.88 x 1010 y",
            },
            Mass = 86.909,
            MassNumber = 87,
            ModeOfDecay = {
                "beta-",
            },
            Name = "87Rb",
            NaturalAbundance = 27.83,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 84.912,
            MassNumber = 85,
            ModeOfDecay = {},
            Name = "85Rb",
            NaturalAbundance = 72.17,
        },
        {
            HalfLife = {
                "4.88 x 1010 y",
            },
            Mass = 86.909,
            MassNumber = 87,
            ModeOfDecay = {
                "beta-",
            },
            Name = "87Rb",
            NaturalAbundance = 27.83,
        },
    },
    MeltingPointK = 312.45,
    Name = "Rubidium",
    NeutronsApprox = 48,
    Period = 5,
    Protons = 37,
    RepresentativeMassNumber = 85,
    StateAt293K = "Solid",
    Symbol = "Rb",
    Uses = "Rubidium is little used outside research. It has been used as a component of photocells, to remove traces of oxygen from vacuum tubes and to make special types of glass. \
\
It is easily ionised so was considered for use in ion engines, but was found to be less effective than caesium. It has also been proposed for use as a working fluid for vapour turbines and in thermoelectric generators.\
\
Rubidium nitrate is sometimes used in fireworks to give them a purple colour.",
}

return Rubidium
