local Rutherfordium = {
    Appearance = "A radioactive metal that does not occur naturally. Relatively few atoms have ever been made.",
    AtomicMass = -267,
    AtomicNumber = 104,
    Block = "d",
    Category = "Transition",
    CovalentRadius = 1.57,
    ElectronConfiguration = "[Rn] 5f146d27s2",
    Density = 23.2,
    Electrons = 104,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        10,
        2,
    },
    Group = "4",
    IonizationEnergies = {
        579,
    },
    Isotopes = {
        {
            HalfLife = {
                "~ 2 m",
            },
            Mass = 265.117,
            MassNumber = 265,
            ModeOfDecay = {
                "alpha",
            },
            Name = "265Rf",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "~ 2 m",
            },
            Mass = 265.117,
            MassNumber = 265,
            ModeOfDecay = {
                "alpha",
            },
            Name = "265Rf",
        },
    },
    Name = "Rutherfordium",
    NeutronsApprox = 161,
    Period = 7,
    Protons = 104,
    RepresentativeMassNumber = 265,
    StateAt293K = "Solid",
    Symbol = "Rf",
    Uses = "At present, it is only used in research.",
}

return Rutherfordium
