local Samarium = {
    Appearance = "A silvery-white metal.",
    AtomicMass = 150.36,
    AtomicNumber = 62,
    AtomicRadius = 2.36,
    Block = "f",
    BoilingPointK = 2067,
    Category = "Lanthanoid",
    CovalentRadius = 1.85,
    ElectronConfiguration = "[Xe] 4f66s2",
    Electronegativity = 1.17,
    Density = 7.52,
    Electrons = 62,
    EnergyLevels = {
        2,
        8,
        18,
        24,
        8,
        2,
    },
    Group = "Lanthanides",
    IonizationEnergies = {
        544.534,
        1068.09,
        2257.8,
        3994.5,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 143.912,
            MassNumber = 144,
            ModeOfDecay = {},
            Name = "144Sm",
            NaturalAbundance = 3.07,
        },
        {
            HalfLife = {
                "1.06 x 1011 y",
            },
            Mass = 146.915,
            MassNumber = 147,
            ModeOfDecay = {
                "a",
            },
            Name = "147Sm",
            NaturalAbundance = 14.99,
        },
        {
            HalfLife = {
                "7 x 1015 y",
            },
            Mass = 147.915,
            MassNumber = 148,
            ModeOfDecay = {
                "a",
            },
            Name = "148Sm",
            NaturalAbundance = 11.24,
        },
        {
            HalfLife = {
                "1016 y",
            },
            Mass = 148.917,
            MassNumber = 149,
            ModeOfDecay = {
                "a",
            },
            Name = "149Sm",
            NaturalAbundance = 13.82,
        },
        {
            HalfLife = {},
            Mass = 149.917,
            MassNumber = 150,
            ModeOfDecay = {},
            Name = "150Sm",
            NaturalAbundance = 7.38,
        },
        {
            HalfLife = {},
            Mass = 151.92,
            MassNumber = 152,
            ModeOfDecay = {},
            Name = "152Sm",
            NaturalAbundance = 26.75,
        },
        {
            HalfLife = {},
            Mass = 153.922,
            MassNumber = 154,
            ModeOfDecay = {},
            Name = "154Sm",
            NaturalAbundance = 22.75,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 151.92,
            MassNumber = 152,
            ModeOfDecay = {},
            Name = "152Sm",
            NaturalAbundance = 26.75,
        },
    },
    MeltingPointK = 1345,
    Name = "Samarium",
    NeutronsApprox = 90,
    Period = 6,
    Protons = 62,
    RepresentativeMassNumber = 152,
    StateAt293K = "Solid",
    Symbol = "Sm",
    Uses = "Samarium-cobalt magnets are much more powerful than iron magnets. They remain magnetic at high temperatures and so are used in microwave applications. They enabled the miniaturisation of electronic devices like headphones, and the development of personal stereos. However, neodymium magnets are now more commonly used instead.\
\
Samarium is used to dope calcium chloride crystals for use in optical lasers. It is also used in infrared absorbing glass and as a neutron absorber in nuclear reactors. Samarium oxide finds specialised use in glass and ceramics. In common with other lanthanides, samarium is used in carbon arc lighting for studio lighting and projection.",
}

return Samarium
