local Scandium = {
    Appearance = "A silvery metal that tarnishes in air, burns easily and reacts with water.",
    AtomicMass = 44.956,
    AtomicNumber = 21,
    AtomicRadius = 2.15,
    Block = "d",
    BoilingPointK = 3109,
    Category = "Transition",
    CovalentRadius = 1.59,
    ElectronAffinity = 18.139,
    ElectronConfiguration = "[Ar] 3d14s2",
    Electronegativity = 1.36,
    Density = 2.985,
    Electrons = 21,
    EnergyLevels = {
        2,
        8,
        9,
        2,
    },
    Group = "3",
    IonizationEnergies = {
        633.088,
        1234.99,
        2388.655,
        7090.65,
        8842.88,
        10679,
        13315,
        15254.3,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 44.956,
            MassNumber = 45,
            ModeOfDecay = {},
            Name = "45Sc",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 44.956,
            MassNumber = 45,
            ModeOfDecay = {},
            Name = "45Sc",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 1814,
    Name = "Scandium",
    NeutronsApprox = 24,
    Period = 4,
    Protons = 21,
    RepresentativeMassNumber = 45,
    StateAt293K = "Solid",
    Symbol = "Sc",
    Uses = "Scandium is mainly used for research purposes. It has, however, great potential because it has almost as low a density as aluminium and a much higher melting point. An aluminium-scandium alloy has been used in Russian MIG fighter planes, high-end bicycle frames and baseball bats. \
\
Scandium iodide is added to mercury vapour lamps to produce a highly efficient light source resembling sunlight. These lamps help television cameras to reproduce colour well when filming indoors or at night-time. \
\
The radioactive isotope scandium-46 is used as a tracer in oil refining to monitor the movement of various fractions. It can also be used in underground pipes to detect leaks.",
}

return Scandium
