local Seaborgium = {
    Appearance = "A radioactive metal that does not occur naturally. Only a few atoms have ever been made.",
    AtomicMass = -269,
    AtomicNumber = 106,
    Block = "d",
    Category = "Transition",
    CovalentRadius = 1.43,
    ElectronConfiguration = "[Rn] 5f146d47s2",
    Density = 35,
    Electrons = 106,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        12,
        2,
    },
    Group = "6",
    IonizationEnergies = {},
    Isotopes = {
        {
            HalfLife = {
                "2 m",
            },
            Mass = 271.134,
            MassNumber = 271,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "271Sg",
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "2 m",
            },
            Mass = 271.134,
            MassNumber = 271,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "271Sg",
        },
    },
    Name = "Seaborgium",
    NeutronsApprox = 165,
    Period = 7,
    Protons = 106,
    RepresentativeMassNumber = 271,
    StateAt293K = "Solid",
    Symbol = "Sg",
    Uses = "At present, it is only used in research.",
}

return Seaborgium
