local Selenium = {
    Appearance = "A semi-metal that can exist in two forms: as a silvery metal or as a red powder.",
    AtomicMass = 78.971,
    AtomicNumber = 34,
    AtomicRadius = 1.9,
    Block = "p",
    BoilingPointK = 958,
    Category = "Nonmetal",
    CovalentRadius = 1.18,
    ElectronAffinity = 194.965,
    ElectronConfiguration = "[Ar] 3d104s24p4",
    Electronegativity = 2.55,
    Density = 4.81,
    Electrons = 34,
    EnergyLevels = {
        2,
        8,
        18,
        6,
    },
    Group = "16",
    IonizationEnergies = {
        940.963,
        2044.52,
        2973.717,
        4143.563,
        6589.9,
        7882.9,
        14993.8,
    },
    Isotopes = {
        {
            HalfLife = {
                "> 5.5 x 1018 y",
            },
            Mass = 73.922,
            MassNumber = 74,
            ModeOfDecay = {
                "EC-EC",
            },
            Name = "74Se",
            NaturalAbundance = 0.89,
        },
        {
            HalfLife = {},
            Mass = 75.919,
            MassNumber = 76,
            ModeOfDecay = {},
            Name = "76Se",
            NaturalAbundance = 9.37,
        },
        {
            HalfLife = {},
            Mass = 76.92,
            MassNumber = 77,
            ModeOfDecay = {},
            Name = "77Se",
            NaturalAbundance = 7.63,
        },
        {
            HalfLife = {},
            Mass = 77.917,
            MassNumber = 78,
            ModeOfDecay = {},
            Name = "78Se",
            NaturalAbundance = 23.77,
        },
        {
            HalfLife = {},
            Mass = 79.917,
            MassNumber = 80,
            ModeOfDecay = {},
            Name = "80Se",
            NaturalAbundance = 49.61,
        },
        {
            HalfLife = {
                "> 9.5 x 1019 y",
            },
            Mass = 81.917,
            MassNumber = 82,
            ModeOfDecay = {
                "beta-beta-",
            },
            Name = "82Se",
            NaturalAbundance = 8.73,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 79.917,
            MassNumber = 80,
            ModeOfDecay = {},
            Name = "80Se",
            NaturalAbundance = 49.61,
        },
    },
    MeltingPointK = 494,
    Name = "Selenium",
    NeutronsApprox = 46,
    Period = 4,
    Protons = 34,
    RepresentativeMassNumber = 80,
    StateAt293K = "Solid",
    Symbol = "Se",
    Uses = "The biggest use of selenium is as an additive to glass. Some selenium compounds decolourise glass, while others give a deep red colour. Selenium can also be used to reduce the transmission of sunlight in architectural glass, giving it a bronze tint. Selenium is used to make pigments for ceramics, paint and plastics.\
\
Selenium has both a photovoltaic action (converts light to electricity) and a photoconductive action (electrical resistance decreases with increased illumination). It is therefore useful in photocells, solar cells and photocopiers. It can also convert AC electricity to DC electricity, so is extensively used in rectifiers. \
\
Selenium is toxic to the scalp fungus that causes dandruff so it is used in some anti-dandruff shampoos. Selenium is also used as an additive to make stainless steel.",
}

return Selenium
