local Silicon = {
    Appearance = "The element, when ultrapure, is a solid with a blue-grey metallic sheen.",
    AtomicMass = 28.085,
    AtomicNumber = 14,
    AtomicRadius = 2.1,
    Block = "p",
    BoilingPointK = 3538,
    Category = "Metalloid",
    CovalentRadius = 1.14,
    ElectronAffinity = 134.068,
    ElectronConfiguration = "[Ne] 3s23p2",
    Electronegativity = 1.9,
    Density = 2.329,
    Electrons = 14,
    EnergyLevels = {
        2,
        8,
        4,
    },
    Group = "14",
    IonizationEnergies = {
        786.518,
        1577.134,
        3231.585,
        4355.523,
        16090.571,
        19805.55,
        23783.6,
        29287.16,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 27.977,
            MassNumber = 28,
            ModeOfDecay = {},
            Name = "28Si",
            NaturalAbundance = 92.223,
        },
        {
            HalfLife = {},
            Mass = 28.976,
            MassNumber = 29,
            ModeOfDecay = {},
            Name = "29Si",
            NaturalAbundance = 4.685,
        },
        {
            HalfLife = {},
            Mass = 29.974,
            MassNumber = 30,
            ModeOfDecay = {},
            Name = "30Si",
            NaturalAbundance = 3.092,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 27.977,
            MassNumber = 28,
            ModeOfDecay = {},
            Name = "28Si",
            NaturalAbundance = 92.223,
        },
        {
            HalfLife = {},
            Mass = 29.974,
            MassNumber = 30,
            ModeOfDecay = {},
            Name = "30Si",
            NaturalAbundance = 3.092,
        },
    },
    MeltingPointK = 1687,
    Name = "Silicon",
    NeutronsApprox = 14,
    Period = 3,
    Protons = 14,
    RepresentativeMassNumber = 28,
    StateAt293K = "Solid",
    Symbol = "Si",
    Uses = "Silicon is one of the most useful elements to mankind. Most is used to make alloys including aluminium-silicon and ferro-silicon (iron-silicon). These are used to make dynamo and transformer plates, engine blocks, cylinder heads and machine tools and to deoxidise steel.\
\
Silicon is also used to make silicones. These are silicon-oxygen polymers with methyl groups attached. Silicone oil is a lubricant and is added to some cosmetics and hair conditioners. Silicone rubber is used as a waterproof sealant in bathrooms and around windows, pipes and roofs. \
\
The element silicon is used extensively as a semiconductor in solid-state devices in the computer and microelectronics industries. For this, hyperpure silicon is needed. The silicon is selectively doped with tiny amounts of boron, gallium, phosphorus or arsenic to control its electrical properties. \
\
Granite and most other rocks are complex silicates, and these are used for civil engineering projects. Sand (silicon dioxide or silica) and clay (aluminium silicate) are used to make concrete and cement. Sand is also the principal ingredient of glass, which has thousands of uses. Silicon, as silicate, is present in pottery, enamels and high-temperature ceramics.\
\
Silicon carbides are important abrasives and are also used in lasers.",
}

return Silicon
