local Silver = {
    Appearance = "Silver is a relatively soft, shiny metal. It tarnishes slowly in air as sulfur compounds react with the surface forming black silver sulfide.",
    AtomicMass = 107.87,
    AtomicNumber = 47,
    AtomicRadius = 2.11,
    Block = "d",
    BoilingPointK = 2435,
    Category = "Transition",
    CovalentRadius = 1.36,
    ElectronAffinity = 125.624,
    ElectronConfiguration = "[Kr] 4d105s1",
    Electronegativity = 1.93,
    Density = 10.49,
    Electrons = 47,
    EnergyLevels = {
        2,
        8,
        18,
        18,
        1,
    },
    Group = "11",
    IonizationEnergies = {
        730.995,
        2072.26,
        3360.58,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 106.905,
            MassNumber = 107,
            ModeOfDecay = {},
            Name = "107Ag",
            NaturalAbundance = 51.839,
        },
        {
            HalfLife = {},
            Mass = 108.905,
            MassNumber = 109,
            ModeOfDecay = {},
            Name = "109Ag",
            NaturalAbundance = 48.161,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 106.905,
            MassNumber = 107,
            ModeOfDecay = {},
            Name = "107Ag",
            NaturalAbundance = 51.839,
        },
    },
    MeltingPointK = 1234.93,
    Name = "Silver",
    NeutronsApprox = 60,
    Period = 5,
    Protons = 47,
    RepresentativeMassNumber = 107,
    StateAt293K = "Solid",
    Symbol = "Ag",
    Uses = "Sterling silver contains 92.5% silver. The rest is copper or some other metal. It is used for jewellery and silver tableware, where appearance is important. \
\
Silver is used to make mirrors, as it is the best reflector of visible light known, although it does tarnish with time. It is also used in dental alloys, solder and brazing alloys, electrical contacts and batteries. Silver paints are used for making printed circuits. \
\
Silver bromide and iodide were important in the history of photography, because of their sensitivity to light. Even with the rise of digital photography, silver salts are still important in producing high-quality images and protecting against illegal copying. Light-sensitive glass (such as photochromic lenses) works on similar principles. It darkens in bright sunlight and becomes transparent in low sunlight.\
\
Silver has antibacterial properties and silver nanoparticles are used in clothing to prevent bacteria from digesting sweat and forming unpleasant odours. Silver threads are woven into the fingertips of gloves so that they can be used with touchscreen phones.",
}

return Silver
