local Sodium = {
    Appearance = "Sodium is a soft metal that tarnishes within seconds of being exposed to the air. It also reacts vigorously with water.",
    AtomicMass = 22.99,
    AtomicNumber = 11,
    AtomicRadius = 2.27,
    Block = "s",
    BoilingPointK = 1156.09,
    Category = "Alkali",
    CovalentRadius = 1.6,
    ElectronAffinity = 52.867,
    ElectronConfiguration = "[Ne] 3s1",
    Electronegativity = 0.93,
    Density = 0.968,
    Electrons = 11,
    EnergyLevels = {
        2,
        8,
        1,
    },
    Group = "1",
    IonizationEnergies = {
        495.845,
        4562.444,
        6910.28,
        9543.36,
        13353.6,
        16612.85,
        20117.2,
        25496.25,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 22.99,
            MassNumber = 23,
            ModeOfDecay = {},
            Name = "23Na",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 22.99,
            MassNumber = 23,
            ModeOfDecay = {},
            Name = "23Na",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 370.944,
    Name = "Sodium",
    NeutronsApprox = 12,
    Period = 3,
    Protons = 11,
    RepresentativeMassNumber = 23,
    StateAt293K = "Solid",
    Symbol = "Na",
    Uses = "Sodium is used as a heat exchanger in some nuclear reactors, and as a reagent in the chemicals industry. But sodium salts have more uses than the metal itself.\
\
The most common compound of sodium is sodium chloride (common salt). It is added to food and used to de-ice roads in winter. It is also used as a feedstock for the chemical industry.\
\
Sodium carbonate (washing soda) is also a useful sodium salt. It is used as a water softener.",
}

return Sodium
