local Tantalum = {
    Appearance = "A shiny, silvery metal that is very resistant to corrosion.",
    AtomicMass = 180.95,
    AtomicNumber = 73,
    AtomicRadius = 2.22,
    Block = "d",
    BoilingPointK = 5728,
    Category = "Transition",
    CovalentRadius = 1.58,
    ElectronAffinity = 31.068,
    ElectronConfiguration = "[Xe] 4f145d36s2",
    Electronegativity = 1.5,
    Density = 16.69,
    Electrons = 73,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        11,
        2,
    },
    Group = "5",
    IonizationEnergies = {
        728.423,
    },
    Isotopes = {
        {
            HalfLife = {
                "3.65 x 1016 y",
                "4.5 x 1016 y",
                "> 2.0 x 1016 y",
            },
            Mass = 179.947,
            MassNumber = 180,
            ModeOfDecay = {
                nil,
                "beta-",
                "EC",
            },
            Name = "180Ta",
            NaturalAbundance = 0.012,
        },
        {
            HalfLife = {},
            Mass = 180.948,
            MassNumber = 181,
            ModeOfDecay = {},
            Name = "181Ta",
            NaturalAbundance = 99.988,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "3.65 x 1016 y",
                "4.5 x 1016 y",
                "> 2.0 x 1016 y",
            },
            Mass = 179.947,
            MassNumber = 180,
            ModeOfDecay = {
                nil,
                "beta-",
                "EC",
            },
            Name = "180Ta",
            NaturalAbundance = 0.012,
        },
        {
            HalfLife = {},
            Mass = 180.948,
            MassNumber = 181,
            ModeOfDecay = {},
            Name = "181Ta",
            NaturalAbundance = 99.988,
        },
    },
    MeltingPointK = 3290,
    Name = "Tantalum",
    NeutronsApprox = 107,
    Period = 6,
    Protons = 73,
    RepresentativeMassNumber = 180,
    StateAt293K = "Solid",
    Symbol = "Ta",
    Uses = "One of the main uses of tantalum is in the production of electronic components. An oxide layer which forms on the surface of tantalum can act as an insulating (dielectric) layer. Because tantalum can be used to coat other metals with a very thin layer, a high capacitance can be achieved in a small volume. This makes tantalum capacitors attractive for portable electronics such as mobile phones.\
\
Tantalum causes no immune response in mammals, so has found wide use in the making of surgical implants. It can replace bone, for example in skull plates; as foil or wire it connects torn nerves; and as woven gauze it binds abdominal muscle. \
\
It is very resistant to corrosion and so is used in equipment for handling corrosive materials. It has also found uses as electrodes for neon lights, AC/DC rectifiers and in glass for special lenses.\
\
Tantalum alloys can be extremely strong and have been used for turbine blades, rocket nozzles and nose caps for supersonic aircraft.",
}

return Tantalum
