local Technetium = {
    Appearance = "A radioactive, silvery metal that does not occur naturally.",
    AtomicMass = -98,
    AtomicNumber = 43,
    AtomicRadius = 2.16,
    Block = "d",
    BoilingPointK = 4535,
    Category = "Transition",
    CovalentRadius = 1.38,
    ElectronAffinity = 53.07,
    ElectronConfiguration = "[Kr] 4d55s2",
    Electronegativity = 2.1,
    Density = 11,
    Electrons = 43,
    EnergyLevels = {
        2,
        8,
        18,
        13,
        2,
    },
    Group = "7",
    IonizationEnergies = {
        702.41,
        1472.37,
        2850.18,
    },
    Isotopes = {
        {
            HalfLife = {
                "4.2 x 106 y",
            },
            Mass = 96.906,
            MassNumber = 97,
            ModeOfDecay = {
                "EC",
            },
            Name = "97Tc",
        },
        {
            HalfLife = {
                "6.6 x 106 y",
            },
            Mass = 97.907,
            MassNumber = 98,
            ModeOfDecay = {
                "beta-",
                "EC",
            },
            Name = "98Tc",
        },
        {
            HalfLife = {
                "2.13 x 105 y",
            },
            Mass = 98.906,
            MassNumber = 99,
            ModeOfDecay = {
                "beta-",
            },
            Name = "99Tc",
        },
    },
    KeyIsotopes = {},
    MeltingPointK = 2430,
    Name = "Technetium",
    NeutronsApprox = 54,
    Period = 5,
    Protons = 43,
    RepresentativeMassNumber = 97,
    StateAt293K = "Solid",
    Symbol = "Tc",
    Uses = "The gamma-ray emitting technetium-99m (metastable) is widely used for medical diagnostic studies. Several chemical forms are used to image different parts of the body. \
\
Technetium is a remarkable corrosion inhibitor for steel, and adding very small amounts can provide excellent protection. This use is limited to closed systems as technetium is radioactive.",
}

return Technetium
