local Tellurium = {
    Appearance = "A semi-metal usually obtained as a grey powder.",
    AtomicMass = 127.6,
    AtomicNumber = 52,
    AtomicRadius = 2.06,
    Block = "p",
    BoilingPointK = 1261,
    Category = "Metalloid",
    CovalentRadius = 1.37,
    ElectronAffinity = 190.161,
    ElectronConfiguration = "[Kr] 4d105s25p4",
    Electronegativity = 2.1,
    Density = 6.24,
    Electrons = 52,
    EnergyLevels = {
        2,
        8,
        18,
        18,
        6,
    },
    Group = "16",
    IonizationEnergies = {
        869.294,
        1794.6,
        2697.73,
        3609.52,
        5668.51,
        6821.5,
        13218,
    },
    Isotopes = {
        {
            HalfLife = {
                "1.9 x 1017 y",
            },
            Mass = 119.904,
            MassNumber = 120,
            ModeOfDecay = {
                "beta+EC",
            },
            Name = "120Te",
            NaturalAbundance = 0.09,
        },
        {
            HalfLife = {},
            Mass = 121.903,
            MassNumber = 122,
            ModeOfDecay = {},
            Name = "122Te",
            NaturalAbundance = 2.55,
        },
        {
            HalfLife = {
                "> 9.2 x 1016 y",
            },
            Mass = 122.904,
            MassNumber = 123,
            ModeOfDecay = {
                "EC",
            },
            Name = "123Te",
            NaturalAbundance = 0.89,
        },
        {
            HalfLife = {},
            Mass = 123.903,
            MassNumber = 124,
            ModeOfDecay = {},
            Name = "124Te",
            NaturalAbundance = 4.74,
        },
        {
            HalfLife = {},
            Mass = 124.904,
            MassNumber = 125,
            ModeOfDecay = {},
            Name = "125Te",
            NaturalAbundance = 7.07,
        },
        {
            HalfLife = {},
            Mass = 125.903,
            MassNumber = 126,
            ModeOfDecay = {},
            Name = "126Te",
            NaturalAbundance = 18.84,
        },
        {
            HalfLife = {
                "2.2 x 1024 y",
            },
            Mass = 127.904,
            MassNumber = 128,
            ModeOfDecay = {
                "beta-beta-",
            },
            Name = "128Te",
            NaturalAbundance = 31.74,
        },
        {
            HalfLife = {
                "8 x 1020 y",
            },
            Mass = 129.906,
            MassNumber = 130,
            ModeOfDecay = {
                "beta-beta-",
            },
            Name = "130Te",
            NaturalAbundance = 34.08,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "8 x 1020 y",
            },
            Mass = 129.906,
            MassNumber = 130,
            ModeOfDecay = {
                "beta-beta-",
            },
            Name = "130Te",
            NaturalAbundance = 34.08,
        },
    },
    MeltingPointK = 722.66,
    Name = "Tellurium",
    NeutronsApprox = 78,
    Period = 5,
    Protons = 52,
    RepresentativeMassNumber = 130,
    StateAt293K = "Solid",
    Symbol = "Te",
    Uses = "Tellurium is used in alloys, mostly with copper and stainless steel, to improve their machinability. When added to lead it makes it more resistant to acids and improves its strength and hardness. \
\
Tellurium has been used to vulcanise rubber, to tint glass and ceramics, in solar cells, in rewritable CDs and DVDs and as a catalyst in oil refining. It can be doped with silver, gold, copper or tin in semiconductor applications.",
}

return Tellurium
