local Terbium = {
    Name = "Terbium",
    Symbol = "Tb",
    AtomicNumber = 65,
    AtomicMass = 158.93,
    RepresentativeMassNumber = 159,
    Protons = 65,
    Electrons = 65,
    NeutronsApprox = 94,
    Category = "Lanthanoid",
    Group = "Lanthanides",
    Period = 6,
    Block = "f",
    StateAt293K = "Solid",
    Density = 8.23,
    Appearance = {
        "A soft, silvery metal.",
    },
    Uses = {
        "Terbium is used to dope calcium fluoride, calcium tungstate and strontium molybdate, all used in solid-state devices. It is also used in low-energy lightbulbs and mercury lamps. It has been used to improve the safety of medical x-rays by allowing the same quality image to be produced with a much shorter exposure time. Terbium salts are used in laser devices.",
        "An alloy of terbium, dysprosium and iron lengthens and shortens in a magnetic field. This effect forms the basis of loudspeakers that sit on a flat surface, such as a window pane, which then acts as the speaker.",
    },
    ElectronConfiguration = "[Xe] 4f96s2",
    EnergyLevels = {
        2,
        8,
        18,
        27,
        8,
        2,
    },
    AtomicRadius = 2.33,
    CovalentRadius = 1.81,
    IonizationEnergies = {
        565.771,
        1111.51,
        2113.99,
        3839.15,
    },
    MeltingPointK = 1632,
    BoilingPointK = 3503,
    KeyIsotopes = {
        {
            Name = "159Tb",
            HalfLife = {},
            Mass = 158.925,
            MassNumber = 159,
            ModeOfDecay = {},
            NaturalAbundance = 100,
        },
    },
    Isotopes = {
        {
            Name = "159Tb",
            HalfLife = {},
            Mass = 158.925,
            MassNumber = 159,
            ModeOfDecay = {},
            NaturalAbundance = 100,
        },
    },
}

return Terbium
