local Thallium = {
    Appearance = "A soft, silvery-white metal that tarnishes easily.",
    AtomicMass = 204.38,
    AtomicNumber = 81,
    AtomicRadius = 1.96,
    Block = "p",
    BoilingPointK = 1746,
    Category = "Poor",
    CovalentRadius = 1.44,
    ElectronAffinity = 36.375,
    ElectronConfiguration = "[Xe] 4f145d106s26p1",
    Electronegativity = 1.8,
    Density = 11.85,
    Electrons = 81,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        3,
    },
    Group = "13",
    IonizationEnergies = {
        589.351,
        1971.032,
        2878.16,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 202.972,
            MassNumber = 203,
            ModeOfDecay = {},
            Name = "203Tl",
            NaturalAbundance = 29.52,
        },
        {
            HalfLife = {},
            Mass = 204.974,
            MassNumber = 205,
            ModeOfDecay = {},
            Name = "205Tl",
            NaturalAbundance = 70.48,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 204.974,
            MassNumber = 205,
            ModeOfDecay = {},
            Name = "205Tl",
            NaturalAbundance = 70.48,
        },
    },
    MeltingPointK = 577,
    Name = "Thallium",
    NeutronsApprox = 124,
    Period = 6,
    Protons = 81,
    RepresentativeMassNumber = 205,
    StateAt293K = "Solid",
    Symbol = "Tl",
    Uses = "The use of thallium is limited as it is a toxic element. Thallium sulfate was employed as a rodent killer - it is odourless and tasteless - but household use of this poison has been prohibited in most developed countries. \
\
Most thallium is used by the electronics industry in photoelectric cells. Thallium oxide is used to produce special glass with a high index of refraction, and also low melting glass that becomes fluid at about 125K.\
\
An alloy of mercury containing 8% thallium has a melting point 20C lower than mercury alone. This can be used in low temperature thermometers and switches.",
}

return Thallium
