local Thorium = {
    Appearance = "A weakly radioactive, silvery metal.",
    AtomicMass = 232.04,
    AtomicNumber = 90,
    AtomicRadius = 2.45,
    Block = "f",
    BoilingPointK = 5058,
    Category = "Actinoid",
    CovalentRadius = 1.9,
    ElectronConfiguration = "[Rn] 6d27s2",
    Electronegativity = 1.3,
    Density = 11.724,
    Electrons = 90,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        10,
        2,
    },
    Group = "Actinides",
    IonizationEnergies = {
        608.504,
        1148.2,
        1930,
        2778.8,
    },
    Isotopes = {
        {
            HalfLife = {
                "7.56 x 104 y",
                "> 2 x 1018 y",
            },
            Mass = 230.033,
            MassNumber = 230,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "230Th",
        },
        {
            HalfLife = {
                "1.4 x 1010 y",
                "1.2 x 1021 y",
            },
            Mass = 232.038,
            MassNumber = 232,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "232Th",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "7.56 x 104 y",
                "> 2 x 1018 y",
            },
            Mass = 230.033,
            MassNumber = 230,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "230Th",
        },
        {
            HalfLife = {
                "1.4 x 1010 y",
                "1.2 x 1021 y",
            },
            Mass = 232.038,
            MassNumber = 232,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
            Name = "232Th",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 2023,
    Name = "Thorium",
    NeutronsApprox = 140,
    Period = 7,
    Protons = 90,
    RepresentativeMassNumber = 230,
    StateAt293K = "Solid",
    Symbol = "Th",
    Uses = "Thorium is an important alloying agent in magnesium, as it imparts greater strength and creep resistance at high temperatures. Thorium oxide is used as an industrial catalyst.\
\
Thorium can be used as a source of nuclear power. It is about three times as abundant as uranium and about as abundant as lead, and there is probably more energy available from thorium than from both uranium and fossil fuels. India and China are in the process of developing nuclear power plants with thorium reactors, but this is still a very new technology. \
\
Thorium dioxide was formerly added to glass during manufacture to increase the refractive index, producing thoriated glass for use in high-quality camera lenses.",
}

return Thorium
