local Titanium = {
    Appearance = "A hard, shiny and strong metal.",
    AtomicMass = 47.867,
    AtomicNumber = 22,
    AtomicRadius = 2.11,
    Block = "d",
    BoilingPointK = 3560,
    Category = "Transition",
    CovalentRadius = 1.48,
    ElectronAffinity = 7.622,
    ElectronConfiguration = "[Ar] 3d24s2",
    Electronegativity = 1.54,
    Density = 4.506,
    Electrons = 22,
    EnergyLevels = {
        2,
        8,
        10,
        2,
    },
    Group = "4",
    IonizationEnergies = {
        658.813,
        1309.837,
        2652.546,
        4174.651,
        9581,
        11532.89,
        13585.1,
        16441.1,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 45.953,
            MassNumber = 46,
            ModeOfDecay = {},
            Name = "46Ti",
            NaturalAbundance = 8.25,
        },
        {
            HalfLife = {},
            Mass = 46.952,
            MassNumber = 47,
            ModeOfDecay = {},
            Name = "47Ti",
            NaturalAbundance = 7.44,
        },
        {
            HalfLife = {},
            Mass = 47.948,
            MassNumber = 48,
            ModeOfDecay = {},
            Name = "48Ti",
            NaturalAbundance = 73.72,
        },
        {
            HalfLife = {},
            Mass = 48.948,
            MassNumber = 49,
            ModeOfDecay = {},
            Name = "49Ti",
            NaturalAbundance = 5.41,
        },
        {
            HalfLife = {},
            Mass = 49.945,
            MassNumber = 50,
            ModeOfDecay = {},
            Name = "50Ti",
            NaturalAbundance = 5.18,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 47.948,
            MassNumber = 48,
            ModeOfDecay = {},
            Name = "48Ti",
            NaturalAbundance = 73.72,
        },
    },
    MeltingPointK = 1943,
    Name = "Titanium",
    NeutronsApprox = 26,
    Period = 4,
    Protons = 22,
    RepresentativeMassNumber = 48,
    StateAt293K = "Solid",
    Symbol = "Ti",
    Uses = "Titanium is as strong as steel but much less dense. It is therefore important as an alloying agent with many metals including aluminium, molybdenum and iron. These alloys are mainly used in aircraft, spacecraft and missiles because of their low density and ability to withstand extremes of temperature. They are also used in golf clubs, laptops, bicycles and crutches. \
\
Power plant condensers use titanium pipes because of their resistance to corrosion. Because titanium has excellent resistance to corrosion in seawater, it is used in desalination plants and to protect the hulls of ships, submarines and other structures exposed to seawater. \
\
Titanium metal connects well with bone, so it has found surgical applications such as in joint replacements (especially hip joints) and tooth implants.  \
\
The largest use of titanium is in the form of titanium(IV) oxide. It is extensively used as a pigment in house paint, artists' paint, plastics, enamels and paper. It is a bright white pigment with excellent covering power. It is also a good reflector of infrared radiation and so is used in solar observatories where heat causes poor visibility. \
\
Titanium(IV) oxide is used in sunscreens because it prevents UV light from reaching the skin. Nanoparticles of titanium(IV) oxide appear invisible when applied to the skin.",
}

return Titanium
