local Tungsten = {
    Appearance = "A shiny, silvery-white metal.",
    AtomicMass = 183.84,
    AtomicNumber = 74,
    AtomicRadius = 2.18,
    Block = "d",
    BoilingPointK = 5828,
    Category = "Transition",
    CovalentRadius = 1.5,
    ElectronAffinity = 78.757,
    ElectronConfiguration = "[Xe] 4f145d46s2",
    Electronegativity = 1.7,
    Density = 19.25,
    Electrons = 74,
    EnergyLevels = {
        2,
        8,
        18,
        32,
        12,
        2,
    },
    Group = "6",
    IonizationEnergies = {
        758.764,
        1553.4,
    },
    Isotopes = {
        {
            HalfLife = {
                "1.8 x 1018 y",
            },
            Mass = 179.947,
            MassNumber = 180,
            ModeOfDecay = {
                "alpha",
            },
            Name = "180W",
            NaturalAbundance = 0.12,
        },
        {
            HalfLife = {
                "> 7.7 x 1021 y",
            },
            Mass = 181.948,
            MassNumber = 182,
            ModeOfDecay = {
                "alpha",
            },
            Name = "182W",
            NaturalAbundance = 26.5,
        },
        {
            HalfLife = {
                "> 4.1 x 1021 y",
            },
            Mass = 182.95,
            MassNumber = 183,
            ModeOfDecay = {
                "alpha",
            },
            Name = "183W",
            NaturalAbundance = 14.31,
        },
        {
            HalfLife = {
                "> 8.9 x 1021 y",
            },
            Mass = 183.951,
            MassNumber = 184,
            ModeOfDecay = {
                "alpha",
            },
            Name = "184W",
            NaturalAbundance = 30.64,
        },
        {
            HalfLife = {
                "> 8.2 x 1021 y",
            },
            Mass = 185.954,
            MassNumber = 186,
            ModeOfDecay = {
                "alpha",
            },
            Name = "186W",
            NaturalAbundance = 28.43,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "> 7.7 x 1021 y",
            },
            Mass = 181.948,
            MassNumber = 182,
            ModeOfDecay = {
                "alpha",
            },
            Name = "182W",
            NaturalAbundance = 26.5,
        },
        {
            HalfLife = {
                "> 8.9 x 1021 y",
            },
            Mass = 183.951,
            MassNumber = 184,
            ModeOfDecay = {
                "alpha",
            },
            Name = "184W",
            NaturalAbundance = 30.64,
        },
        {
            HalfLife = {
                "> 8.2 x 1021 y",
            },
            Mass = 185.954,
            MassNumber = 186,
            ModeOfDecay = {
                "alpha",
            },
            Name = "186W",
            NaturalAbundance = 28.43,
        },
    },
    MeltingPointK = 3687,
    Name = "Tungsten",
    NeutronsApprox = 108,
    Period = 6,
    Protons = 74,
    RepresentativeMassNumber = 182,
    StateAt293K = "Solid",
    Symbol = "W",
    Uses = "Tungsten was used extensively for the filaments of old-style incandescent light bulbs, but these have been phased out in many countries. This is because they are not very energy efficient; they produce much more heat than light.\
\
Tungsten has the highest melting point of all metals and is alloyed with other metals to strengthen them. Tungsten and its alloys are used in many high-temperature applications, such as arc-welding electrodes and heating elements in high-temperature furnaces. \
\
Tungsten carbide is immensely hard and is very important to the metal-working, mining and petroleum industries. It is made by mixing tungsten powder and carbon powder and heating to 2200C. It makes excellent cutting and drilling tools, including a new 'painless' dental drill which spins at ultra-high speeds. \
\
Calcium and magnesium tungstates are widely used in fluorescent lighting.",
}

return Tungsten
