local Vanadium = {
    Appearance = "A silvery metal that resists corrosion.",
    AtomicMass = 50.942,
    AtomicNumber = 23,
    AtomicRadius = 2.07,
    Block = "d",
    BoilingPointK = 3680,
    Category = "Transition",
    CovalentRadius = 1.44,
    ElectronAffinity = 50.655,
    ElectronConfiguration = "[Ar] 3d34s2",
    Electronegativity = 1.63,
    Density = 6,
    Electrons = 23,
    EnergyLevels = {
        2,
        8,
        11,
        2,
    },
    Group = "5",
    IonizationEnergies = {
        650.908,
        1410.423,
        2828.082,
        4506.734,
        6298.727,
        12362.67,
        14530.7,
        16730.6,
    },
    Isotopes = {
        {
            HalfLife = {
                "1.4 x 1017 y",
            },
            Mass = 49.947,
            MassNumber = 50,
            ModeOfDecay = {
                "EC",
            },
            Name = "50V",
            NaturalAbundance = 0.25,
        },
        {
            HalfLife = {},
            Mass = 50.944,
            MassNumber = 51,
            ModeOfDecay = {},
            Name = "51V",
            NaturalAbundance = 99.75,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 50.944,
            MassNumber = 51,
            ModeOfDecay = {},
            Name = "51V",
            NaturalAbundance = 99.75,
        },
    },
    MeltingPointK = 2183,
    Name = "Vanadium",
    NeutronsApprox = 28,
    Period = 4,
    Protons = 23,
    RepresentativeMassNumber = 51,
    StateAt293K = "Solid",
    Symbol = "V",
    Uses = "About 80% of the vanadium produced is used as a steel additive. Vanadium-steel alloys are very tough and are used for armour plate, axles, tools, piston rods and crankshafts. Less than 1% of vanadium, and as little chromium, makes steel shock resistant and vibration resistant. Vanadium alloys are used in nuclear reactors because of vanadium's low neutron-absorbing properties. \
\
Vanadium(V) oxide is used as a pigment for ceramics and glass, as a catalyst and in producing superconducting magnets.",
}

return Vanadium
