local Xenon = {
    Appearance = "A colourless, odourless gas. It is very unreactive.",
    AtomicMass = 131.29,
    AtomicNumber = 54,
    AtomicRadius = 2.16,
    Block = "p",
    BoilingPointK = 165.051,
    Category = "Noble",
    CovalentRadius = 1.36,
    ElectronConfiguration = "[Kr] 4d105s25p6",
    Electronegativity = 2.6,
    Density = 5.894,
    Electrons = 54,
    EnergyLevels = {
        2,
        8,
        18,
        18,
        8,
    },
    Group = "18",
    IonizationEnergies = {
        1170.352,
        2023.78,
        3099.399,
    },
    Isotopes = {
        {
            HalfLife = {
                "> 1017 y",
            },
            Mass = 123.906,
            MassNumber = 124,
            ModeOfDecay = {
                "beta-beta-",
            },
            Name = "124Xe",
            NaturalAbundance = 0.0952,
        },
        {
            HalfLife = {},
            Mass = 125.904,
            MassNumber = 126,
            ModeOfDecay = {},
            Name = "126Xe",
            NaturalAbundance = 0.089,
        },
        {
            HalfLife = {},
            Mass = 127.904,
            MassNumber = 128,
            ModeOfDecay = {},
            Name = "128Xe",
            NaturalAbundance = 1.9102,
        },
        {
            HalfLife = {},
            Mass = 128.905,
            MassNumber = 129,
            ModeOfDecay = {},
            Name = "129Xe",
            NaturalAbundance = 26.4006,
        },
        {
            HalfLife = {},
            Mass = 129.904,
            MassNumber = 130,
            ModeOfDecay = {},
            Name = "130Xe",
            NaturalAbundance = 4.071,
        },
        {
            HalfLife = {},
            Mass = 130.905,
            MassNumber = 131,
            ModeOfDecay = {},
            Name = "131Xe",
            NaturalAbundance = 21.2324,
        },
        {
            HalfLife = {},
            Mass = 131.904,
            MassNumber = 132,
            ModeOfDecay = {},
            Name = "132Xe",
            NaturalAbundance = 26.9086,
        },
        {
            HalfLife = {
                "> 1.1 x 1016 y",
            },
            Mass = 133.905,
            MassNumber = 134,
            ModeOfDecay = {
                "beta-beta-",
            },
            Name = "134Xe",
            NaturalAbundance = 10.4357,
        },
        {
            HalfLife = {
                "> 8.5 x 1021 y",
            },
            Mass = 135.907,
            MassNumber = 136,
            ModeOfDecay = {
                "beta-beta-",
            },
            Name = "136Xe",
            NaturalAbundance = 8.8573,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 131.904,
            MassNumber = 132,
            ModeOfDecay = {},
            Name = "132Xe",
            NaturalAbundance = 26.9086,
        },
    },
    MeltingPointK = 161.4,
    Name = "Xenon",
    NeutronsApprox = 78,
    Period = 5,
    Protons = 54,
    RepresentativeMassNumber = 132,
    StateAt293K = "Gas",
    Symbol = "Xe",
    Uses = "Xenon is used in certain specialised light sources. It produces a beautiful blue glow when excited by an electrical discharge. Xenon lamps have applications as high-speed electronic flash bulbs used by photographers, sunbed lamps and bactericidal lamps used in food preparation and processing. Xenon lamps are also used in ruby lasers.\
\
Xenon ion propulsion systems are used by several satellites to keep them in orbit, and in some other spacecraft.\
\
Xenon difluoride is used to etch silicon microprocessors. It is also used in the manufacture of 5-fluorouracil, a drug used to treat certain types of cancer.",
}

return Xenon
