local Yttrium = {
    Appearance = "A soft, silvery metal.",
    AtomicMass = 88.906,
    AtomicNumber = 39,
    AtomicRadius = 2.32,
    Block = "d",
    BoilingPointK = 3618,
    Category = "Transition",
    CovalentRadius = 1.76,
    ElectronAffinity = 29.621,
    ElectronConfiguration = "[Kr] 4d15s2",
    Electronegativity = 1.22,
    Density = 4.472,
    Electrons = 39,
    EnergyLevels = {
        2,
        8,
        18,
        9,
        2,
    },
    Group = "3",
    IonizationEnergies = {
        599.878,
        1179.437,
        1979.88,
        5846.722,
        7429,
        8973,
        11192,
        12447,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 88.906,
            MassNumber = 89,
            ModeOfDecay = {},
            Name = "89Y",
            NaturalAbundance = 100,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 88.906,
            MassNumber = 89,
            ModeOfDecay = {},
            Name = "89Y",
            NaturalAbundance = 100,
        },
    },
    MeltingPointK = 1795,
    Name = "Yttrium",
    NeutronsApprox = 50,
    Period = 5,
    Protons = 39,
    RepresentativeMassNumber = 89,
    StateAt293K = "Solid",
    Symbol = "Y",
    Uses = "Yttrium is often used as an additive in alloys. It increases the strength of aluminium and magnesium alloys. It is also used in the making of microwave filters for radar and has been used as a catalyst in ethene polymerisation.\
\
Yttrium-aluminium garnet (YAG) is used in lasers that can cut through metals. It is also used in white LED lights.\
\
Yttrium oxide is added to the glass used to make camera lenses to make them heat and shock resistant. It is also used to make superconductors. Yttrium oxysulfide used to be widely used to produce red phosphors for old-style colour television tubes. \
\
The radioactive isotope yttrium-90 has medical uses. It can be used to treat some cancers, such as liver cancer.",
}

return Yttrium
