local Zinc = {
    Appearance = "A silvery-white metal with a blue tinge. It tarnishes in air.",
    AtomicMass = 65.38,
    AtomicNumber = 30,
    AtomicRadius = 2.01,
    Block = "d",
    BoilingPointK = 1180,
    Category = "Transition",
    CovalentRadius = 1.2,
    ElectronConfiguration = "[Ar] 3d104s2",
    Electronegativity = 1.65,
    Density = 7.14,
    Electrons = 30,
    EnergyLevels = {
        2,
        8,
        18,
        2,
    },
    Group = "12",
    IonizationEnergies = {
        906.402,
        1733.3,
        3832.687,
        5731.2,
        7969.7,
        10420,
        12929,
        16788,
    },
    Isotopes = {
        {
            HalfLife = {
                "> 7 x 1020 y",
            },
            Mass = 63.929,
            MassNumber = 64,
            ModeOfDecay = {
                "EC-beta+",
            },
            Name = "64Zn",
            NaturalAbundance = 49.17,
        },
        {
            HalfLife = {},
            Mass = 65.926,
            MassNumber = 66,
            ModeOfDecay = {},
            Name = "66Zn",
            NaturalAbundance = 27.73,
        },
        {
            HalfLife = {},
            Mass = 66.927,
            MassNumber = 67,
            ModeOfDecay = {},
            Name = "67Zn",
            NaturalAbundance = 4.04,
        },
        {
            HalfLife = {},
            Mass = 67.925,
            MassNumber = 68,
            ModeOfDecay = {},
            Name = "68Zn",
            NaturalAbundance = 18.45,
        },
        {
            HalfLife = {
                "> 2.3 x 1016 y",
            },
            Mass = 69.925,
            MassNumber = 70,
            ModeOfDecay = {
                "beta-beta-",
            },
            Name = "70Zn",
            NaturalAbundance = 0.61,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {
                "> 7 x 1020 y",
            },
            Mass = 63.929,
            MassNumber = 64,
            ModeOfDecay = {
                "EC-beta+",
            },
            Name = "64Zn",
            NaturalAbundance = 49.17,
        },
    },
    MeltingPointK = 692.677,
    Name = "Zinc",
    NeutronsApprox = 34,
    Period = 4,
    Protons = 30,
    RepresentativeMassNumber = 64,
    StateAt293K = "Solid",
    Symbol = "Zn",
    Uses = "Most zinc is used to galvanise other metals, such as iron, to prevent rusting. Galvanised steel is used for car bodies, street lamp posts, safety barriers and suspension bridges. \
\
Large quantities of zinc are used to produce die-castings, which are important in the automobile, electrical and hardware industries. Zinc is also used in alloys such as brass, nickel silver and aluminium solder. \
\
Zinc oxide is widely used in the manufacture of very many products such as paints, rubber, cosmetics, pharmaceuticals, plastics, inks, soaps, batteries, textiles and electrical equipment. Zinc sulfide is used in making luminous paints, fluorescent lights and x-ray screens.",
}

return Zinc
