local Zirconium = {
    Appearance = "A hard, silvery metal that is very resistant to corrosion.",
    AtomicMass = 91.224,
    AtomicNumber = 40,
    AtomicRadius = 2.23,
    Block = "d",
    BoilingPointK = 4679,
    Category = "Transition",
    CovalentRadius = 1.64,
    ElectronAffinity = 41.103,
    ElectronConfiguration = "[Kr] 4d25s2",
    Electronegativity = 1.33,
    Density = 6.52,
    Electrons = 40,
    EnergyLevels = {
        2,
        8,
        18,
        10,
        2,
    },
    Group = "4",
    IonizationEnergies = {
        640.074,
        1264,
        2218.2,
        3313.31,
        7752.404,
    },
    Isotopes = {
        {
            HalfLife = {},
            Mass = 89.905,
            MassNumber = 90,
            ModeOfDecay = {},
            Name = "90Zr",
            NaturalAbundance = 51.45,
        },
        {
            HalfLife = {},
            Mass = 90.906,
            MassNumber = 91,
            ModeOfDecay = {},
            Name = "91Zr",
            NaturalAbundance = 11.22,
        },
        {
            HalfLife = {},
            Mass = 91.905,
            MassNumber = 92,
            ModeOfDecay = {},
            Name = "92Zr",
            NaturalAbundance = 17.15,
        },
        {
            HalfLife = {
                "> 1017 y",
            },
            Mass = 93.906,
            MassNumber = 94,
            ModeOfDecay = {
                "beta-beta-",
            },
            Name = "94Zr",
            NaturalAbundance = 17.38,
        },
        {
            HalfLife = {
                "2.3 x 1019 y",
                "> 1.7 x18 y",
            },
            Mass = 95.908,
            MassNumber = 96,
            ModeOfDecay = {
                "beta-beta-",
                "beta-",
            },
            Name = "96Zr",
            NaturalAbundance = 2.8,
        },
    },
    KeyIsotopes = {
        {
            HalfLife = {},
            Mass = 89.905,
            MassNumber = 90,
            ModeOfDecay = {},
            Name = "90Zr",
            NaturalAbundance = 51.45,
        },
        {
            HalfLife = {},
            Mass = 91.905,
            MassNumber = 92,
            ModeOfDecay = {},
            Name = "92Zr",
            NaturalAbundance = 17.15,
        },
        {
            HalfLife = {
                "> 1017 y",
            },
            Mass = 93.906,
            MassNumber = 94,
            ModeOfDecay = {
                "beta-beta-",
            },
            Name = "94Zr",
            NaturalAbundance = 17.38,
        },
    },
    MeltingPointK = 2127,
    Name = "Zirconium",
    NeutronsApprox = 50,
    Period = 5,
    Protons = 40,
    RepresentativeMassNumber = 90,
    StateAt293K = "Solid",
    Symbol = "Zr",
    Uses = "Zirconium does not absorb neutrons, making it an ideal material for use in nuclear power stations. More than 90% of zirconium is used in this way. Nuclear reactors can have more than 100,000 metres of zirconium alloy tubing. With niobium, zirconium is superconductive at low temperatures and is used to make superconducting magnets. \
\
Zirconium metal is protected by a thin oxide layer making it exceptionally resistant to corrosion by acids, alkalis and seawater. For this reason it is extensively used by the chemical industry. \
\
Zirconium(IV) oxide is used in ultra-strong ceramics. It is used to make crucibles that will withstand heat-shock, furnace linings, foundry bricks, abrasives and by the glass and ceramics industries. It is so strong that even scissors and knives can be made from it. It is also used in cosmetics, antiperspirants, food packaging and to make microwave filters. \
\
Zircon is a natural semi-precious gemstone found in a variety of colours. The most desirable have a golden hue. The element was first discovered in this form, resulting in its name. Cubic zirconia (zirconium oxide) is a synthetic gemstone. The colourless stones, when cut, resemble diamonds.\
\
Zircon mixed with vanadium or praseodymium makes blue and yellow pigments for glazing pottery.",
}

return Zirconium
