local ThemeData = {}

ThemeData.Default = {
	Surface = {
		Background = Color3.fromRGB(13, 19, 33),
		Panel = Color3.fromRGB(29, 45, 68),
		SubPanel = Color3.fromRGB(21, 33, 49),
	},
	Text = {
		Primary = Color3.fromRGB(240, 235, 216),
		Background = Color3.fromRGB(50, 50, 50),
	},
	Stroke = Color3.fromRGB(62, 92, 118),

	Button = {
		Background = Color3.fromRGB(13, 19, 33),
	},
}

ThemeData.Custom = {}

return ThemeData
