local UIRules = {
	Normal = {
		TextBackgroundColor = Color3.fromRGB(50, 50, 50),
		TextColor = Color3.fromRGB(240, 235, 216),
		StrokeColor = Color3.fromRGB(62, 92, 118),
		BackgroundColor = Color3.fromRGB(13, 19, 33),
		PanelColor = Color3.fromRGB(29, 45, 68),
		SubPanelColor = Color3.fromRGB(21, 33, 49),
		ButtonBackgroundColor = Color3.fromRGB(21, 33, 49),
	},
	Click = {},
	Hover = {},
}

return UIRules
