local Actinium = {
    Name = "Actinium",
    Symbol = "Ac",
    AtomicNumber = 89,
    AtomicMass = -227,
    RepresentativeMassNumber = 227,
    Protons = 89,
    Electrons = 89,
    NeutronsApprox = 138,
    Category = "Actinoid",
    Group = "Actinides",
    Period = 7,
    Block = "d",
    StateAt293K = "Solid",
    Density = 10,
    Appearance = {
        "Actinium is a soft, silvery-white radioactive metal. It glows blue in the dark because its intense radioactivity excites the air around it.",
    },
    Uses = {
        "Actinium is a very powerful source of alpha rays, but is rarely used outside research.",
    },
    ElectronConfiguration = "[Rn] 6d17s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        18,
        9,
        2,
    },
    AtomicRadius = 2.47,
    CovalentRadius = 2.01,
    ElectronAffinity = 33.77,
    Electronegativity = 1.1,
    IonizationEnergies = {
        498.83,
        1133.7,
    },
    MeltingPointK = 1323,
    BoilingPointK = 3473,
    KeyIsotopes = {
        {
            Name = "227Ac",
            HalfLife = {
                "21.77 y",
            },
            Mass = 227.028,
            MassNumber = 227,
            ModeOfDecay = {
                "beta-",
                "alpha",
            },
        },
    },
    Isotopes = {
        {
            Name = "227Ac",
            HalfLife = {
                "21.77 y",
            },
            Mass = 227.028,
            MassNumber = 227,
            ModeOfDecay = {
                "beta-",
                "alpha",
            },
        },
    },
}

return Actinium
