local Berkelium = {
    Name = "Berkelium",
    Symbol = "Bk",
    AtomicNumber = 97,
    AtomicMass = -247,
    RepresentativeMassNumber = 247,
    Protons = 97,
    Electrons = 97,
    NeutronsApprox = 150,
    Category = "Actinoid",
    Group = "Actinides",
    Period = 7,
    Block = "f",
    StateAt293K = "Solid",
    Density = 14.78,
    Appearance = {
        "Berkelium is a radioactive, silvery metal.",
    },
    Uses = {
        "Because it is so rare, berkelium has no commercial or technological use at present.",
    },
    ElectronConfiguration = "[Rn] 5f97s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        27,
        8,
        2,
    },
    AtomicRadius = 2.44,
    CovalentRadius = 1.68,
    IonizationEnergies = {
        598.007,
    },
    MeltingPointK = 1259,
    KeyIsotopes = {
        {
            Name = "247Bk",
            HalfLife = {
                "1.43 x 103 y",
            },
            Mass = 247.07,
            MassNumber = 247,
            ModeOfDecay = {
                "alpha",
            },
        },
        {
            Name = "249Bk",
            HalfLife = {
                "320 d",
                nil,
                "1.8 x 109 y",
            },
            Mass = 249.075,
            MassNumber = 249,
            ModeOfDecay = {
                "beta",
                "alpha",
                "sf",
            },
        },
    },
    Isotopes = {
        {
            Name = "247Bk",
            HalfLife = {
                "1.43 x 103 y",
            },
            Mass = 247.07,
            MassNumber = 247,
            ModeOfDecay = {
                "alpha",
            },
        },
        {
            Name = "249Bk",
            HalfLife = {
                "320 d",
                nil,
                "1.8 x 109 y",
            },
            Mass = 249.075,
            MassNumber = 249,
            ModeOfDecay = {
                "beta",
                "alpha",
                "sf",
            },
        },
    },
}

return Berkelium
