local Cerium = {
    Name = "Cerium",
    Symbol = "Ce",
    AtomicNumber = 58,
    AtomicMass = 140.12,
    RepresentativeMassNumber = 140,
    Protons = 58,
    Electrons = 58,
    NeutronsApprox = 82,
    Category = "Lanthanoid",
    Group = "Lanthanides",
    Period = 6,
    Block = "f",
    StateAt293K = "Solid",
    Density = 6.77,
    Appearance = {
        "Cerium is a grey metal. It is little used because it tarnishes easily, reacts with water and burns when heated.",
    },
    Uses = {
        "Cerium is the major component of mischmetal alloy (just under 50%). The best-known use for this alloy is in 'flints' for cigarette lighters. This is because cerium will make sparks when struck. The only other element that does this is iron.",
        "Cerium(Ill) oxide has uses as a catalyst. It is used in the inside walls of self-cleaning ovens to prevent the build-up of cooking residues. It is also used in catalytic converters. Cerium(III) oxide nanoparticles are being studied as an additive for diesel fuel to help it burn more completely and reduce exhaust emissions.",
        "Cerium sulfide is a non-toxic compound that is a rich red colour. It is used as a pigment.",
        "Cerium is also used in flat-screen TVs, low-energy light bulbs and floodlights.",
    },
    ElectronConfiguration = "[Xe] 4f15d16s2",
    EnergyLevels = {
        2,
        8,
        18,
        19,
        9,
        2,
    },
    AtomicRadius = 2.42,
    CovalentRadius = 1.84,
    ElectronAffinity = 62.72,
    Electronegativity = 1.12,
    IonizationEnergies = {
        534.403,
        1046.87,
        1948.811,
        3546.608,
        6324.61,
        7487.3,
    },
    MeltingPointK = 1072,
    BoilingPointK = 3716,
    KeyIsotopes = {
        {
            Name = "140Ce",
            HalfLife = {},
            Mass = 139.905,
            MassNumber = 140,
            ModeOfDecay = {},
            NaturalAbundance = 88.45,
        },
    },
    Isotopes = {
        {
            Name = "136Ce",
            HalfLife = {
                "> 0.7 x 1014 y",
                "> 4.2 x 1015 y",
            },
            Mass = 135.907,
            MassNumber = 136,
            ModeOfDecay = {
                "EC EC",
                "beta- beta-",
            },
            NaturalAbundance = 0.185,
        },
        {
            Name = "138Ce",
            HalfLife = {
                ">3.7 x 1014 y",
            },
            Mass = 137.906,
            MassNumber = 138,
            ModeOfDecay = {
                "EC EC",
            },
            NaturalAbundance = 0.251,
        },
        {
            Name = "140Ce",
            HalfLife = {},
            Mass = 139.905,
            MassNumber = 140,
            ModeOfDecay = {},
            NaturalAbundance = 88.45,
        },
        {
            Name = "142Ce",
            HalfLife = {
                "> 1.6 x 1017 y",
            },
            Mass = 141.909,
            MassNumber = 142,
            ModeOfDecay = {
                "beta-beta-",
            },
            NaturalAbundance = 11.114,
        },
    },
}

return Cerium
