local Holmium = {
    Name = "Holmium",
    Symbol = "Ho",
    AtomicNumber = 67,
    AtomicMass = 164.93,
    RepresentativeMassNumber = 165,
    Protons = 67,
    Electrons = 67,
    NeutronsApprox = 98,
    Category = "Lanthanoid",
    Group = "Lanthanides",
    Period = 6,
    Block = "f",
    StateAt293K = "Solid",
    Density = 8.79,
    Appearance = {
        "A bright, silvery metal.",
    },
    Uses = {
        "Holmium can absorb neutrons, so it is used in nuclear reactors to keep a chain reaction under control. Its alloys are used in some magnets.",
    },
    ElectronConfiguration = "[Xe] 4f116s2",
    EnergyLevels = {
        2,
        8,
        18,
        29,
        8,
        2,
    },
    AtomicRadius = 2.3,
    CovalentRadius = 1.79,
    Electronegativity = 1.23,
    IonizationEnergies = {
        580.987,
        1138.5,
        2203.73,
        4100.6,
    },
    MeltingPointK = 1745,
    BoilingPointK = 2973,
    KeyIsotopes = {
        {
            Name = "165Ho",
            HalfLife = {},
            Mass = 164.93,
            MassNumber = 165,
            ModeOfDecay = {},
            NaturalAbundance = 100,
        },
    },
    Isotopes = {
        {
            Name = "165Ho",
            HalfLife = {},
            Mass = 164.93,
            MassNumber = 165,
            ModeOfDecay = {},
            NaturalAbundance = 100,
        },
    },
}

return Holmium
