local Lawrencium = {
    Name = "Lawrencium",
    Symbol = "Lr",
    AtomicNumber = 103,
    AtomicMass = -266,
    RepresentativeMassNumber = 262,
    Protons = 103,
    Electrons = 103,
    NeutronsApprox = 159,
    Category = "Actinoid",
    Group = "Actinides",
    Period = 7,
    Block = "f",
    StateAt293K = "Solid",
    Appearance = {
        "A radioactive metal of which only a few atoms have ever been created.",
    },
    Uses = {
        "Lawrencium has no uses outside research.",
    },
    ElectronConfiguration = "[Rn] 5f147s27p1",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        8,
        3,
    },
    AtomicRadius = 2.46,
    CovalentRadius = 1.61,
    IonizationEnergies = {
        472.8,
    },
    MeltingPointK = 1900,
    KeyIsotopes = {
        {
            Name = "262Lr",
            HalfLife = {
                "3.6 h",
            },
            Mass = 262.11,
            MassNumber = 262,
            ModeOfDecay = {
                "EC",
                "sf",
            },
        },
    },
    Isotopes = {
        {
            Name = "262Lr",
            HalfLife = {
                "3.6 h",
            },
            Mass = 262.11,
            MassNumber = 262,
            ModeOfDecay = {
                "EC",
                "sf",
            },
        },
    },
}

return Lawrencium
