local Mendelevium = {
    Name = "Mendelevium",
    Symbol = "Md",
    AtomicNumber = 101,
    AtomicMass = -258,
    RepresentativeMassNumber = 258,
    Protons = 101,
    Electrons = 101,
    NeutronsApprox = 157,
    Category = "Actinoid",
    Group = "Actinides",
    Period = 7,
    Block = "f",
    StateAt293K = "Solid",
    Appearance = {
        "A radioactive metal, of which only a few atoms have ever been created.",
    },
    Uses = {
        "Mendelevium is used only for research.",
    },
    ElectronConfiguration = "[Rn] 5f137s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        31,
        8,
        2,
    },
    AtomicRadius = 2.46,
    CovalentRadius = 1.73,
    IonizationEnergies = {
        634.87,
    },
    MeltingPointK = 1100,
    KeyIsotopes = {
        {
            Name = "258Md",
            HalfLife = {
                "51.5 d",
            },
            Mass = 258.098,
            MassNumber = 258,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
        {
            Name = "260Md",
            HalfLife = {
                "~ 27.8 d",
            },
            Mass = 260.104,
            MassNumber = 260,
            ModeOfDecay = {
                "sf",
            },
        },
    },
    Isotopes = {
        {
            Name = "258Md",
            HalfLife = {
                "51.5 d",
            },
            Mass = 258.098,
            MassNumber = 258,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
        {
            Name = "260Md",
            HalfLife = {
                "~ 27.8 d",
            },
            Mass = 260.104,
            MassNumber = 260,
            ModeOfDecay = {
                "sf",
            },
        },
    },
}

return Mendelevium
