local Neptunium = {
    Name = "Neptunium",
    Symbol = "Np",
    AtomicNumber = 93,
    AtomicMass = -237,
    RepresentativeMassNumber = 237,
    Protons = 93,
    Electrons = 93,
    NeutronsApprox = 144,
    Category = "Actinoid",
    Group = "Actinides",
    Period = 7,
    Block = "f",
    StateAt293K = "Solid",
    Density = 20.45,
    Appearance = {
        "A radioactive metal.",
    },
    Uses = {
        "Neptunium is little used outside research. The isotope neptunium-237 has been used in neutron detectors.",
    },
    ElectronConfiguration = "[Rn] 5f46d17s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        22,
        9,
        2,
    },
    AtomicRadius = 2.39,
    CovalentRadius = 1.8,
    Electronegativity = 1.3,
    IonizationEnergies = {
        604.548,
    },
    MeltingPointK = 917,
    BoilingPointK = 4175,
    KeyIsotopes = {
        {
            Name = "237Np",
            HalfLife = {
                "2.14 x 106 y",
                "1 x 1018 y",
            },
            Mass = 237.048,
            MassNumber = 237,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
    },
    Isotopes = {
        {
            Name = "236Np",
            HalfLife = {
                "1.55 x 105 y",
            },
            Mass = 236.047,
            MassNumber = 236,
            ModeOfDecay = {
                "EC",
                "beta-",
            },
        },
        {
            Name = "237Np",
            HalfLife = {
                "2.14 x 106 y",
                "1 x 1018 y",
            },
            Mass = 237.048,
            MassNumber = 237,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
    },
}

return Neptunium
