local Nobelium = {
    Name = "Nobelium",
    Symbol = "No",
    AtomicNumber = 102,
    AtomicMass = -259,
    RepresentativeMassNumber = 259,
    Protons = 102,
    Electrons = 102,
    NeutronsApprox = 157,
    Category = "Actinoid",
    Group = "Actinides",
    Period = 7,
    Block = "f",
    StateAt293K = "Solid",
    Appearance = {
        "Nobelium is a radioactive metal. Only a few atoms have ever been made. Its half-life is only 58 minutes.",
    },
    Uses = {
        "Nobelium has no uses outside research.",
    },
    ElectronConfiguration = "[Rn] 5f147s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        8,
        2,
    },
    AtomicRadius = 2.46,
    CovalentRadius = 1.76,
    IonizationEnergies = {
        641.63,
    },
    MeltingPointK = 1100,
    KeyIsotopes = {
        {
            Name = "259No",
            HalfLife = {
                "58 m",
            },
            Mass = 259.101,
            MassNumber = 259,
            ModeOfDecay = {
                "alpha",
                "EC",
                "sf",
            },
        },
    },
    Isotopes = {
        {
            Name = "259No",
            HalfLife = {
                "58 m",
            },
            Mass = 259.101,
            MassNumber = 259,
            ModeOfDecay = {
                "alpha",
                "EC",
                "sf",
            },
        },
    },
}

return Nobelium
