local Seaborgium = {
    Name = "Seaborgium",
    Symbol = "Sg",
    AtomicNumber = 106,
    AtomicMass = -269,
    RepresentativeMassNumber = 271,
    Protons = 106,
    Electrons = 106,
    NeutronsApprox = 165,
    Category = "Transition",
    Group = "6",
    Period = 7,
    Block = "d",
    StateAt293K = "Solid",
    Density = 35,
    Appearance = {
        "A radioactive metal that does not occur naturally. Only a few atoms have ever been made.",
    },
    Uses = {
        "At present, it is only used in research.",
    },
    ElectronConfiguration = "[Rn] 5f146d47s2",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        12,
        2,
    },
    CovalentRadius = 1.43,
    IonizationEnergies = {},
    KeyIsotopes = {
        {
            Name = "271Sg",
            HalfLife = {
                "2 m",
            },
            Mass = 271.134,
            MassNumber = 271,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
    },
    Isotopes = {
        {
            Name = "271Sg",
            HalfLife = {
                "2 m",
            },
            Mass = 271.134,
            MassNumber = 271,
            ModeOfDecay = {
                "alpha",
                "sf",
            },
        },
    },
}

return Seaborgium
