local Tennessine = {
    Name = "Tennessine",
    Symbol = "Ts",
    AtomicNumber = 117,
    AtomicMass = -294,
    RepresentativeMassNumber = 294,
    Protons = 117,
    Electrons = 117,
    NeutronsApprox = 177,
    Category = "Other",
    Group = "17",
    Period = 7,
    Block = "p",
    StateAt293K = "Solid",
    Density = 7.17,
    Appearance = {
        "A highly radioactive metal, of which only a few atoms have ever been made.",
    },
    Uses = {
        "At present, it is only used in research.",
    },
    ElectronConfiguration = "[Rn] 5f146d107s27p5",
    EnergyLevels = {
        2,
        8,
        18,
        32,
        32,
        18,
        7,
    },
    CovalentRadius = 1.65,
    IonizationEnergies = {},
    KeyIsotopes = {
        {
            Name = "294Ts",
            HalfLife = {},
            Mass = 294.21,
            MassNumber = 294,
            ModeOfDecay = {},
        },
    },
    Isotopes = {
        {
            Name = "292Ts",
            HalfLife = {},
            Mass = 292.207,
            MassNumber = 292,
            ModeOfDecay = {},
        },
        {
            Name = "294Ts",
            HalfLife = {},
            Mass = 294.21,
            MassNumber = 294,
            ModeOfDecay = {},
        },
    },
}

return Tennessine
