local GreetingDialogueData = {}
GreetingDialogueData["Greeting1"] = {
	Speaker = "Zombie",
	Lines = {
		{
			Text = "Hello mister , Are you nice?"
		},
	},
}

GreetingDialogueData["Greeting2"] = {
	Speaker = "Zombie",
	Lines = {
		{
			Text = 	"Hello mister , eat nuts."
		},
	},
}

GreetingDialogueData["Greeting3"] = {
	Speaker = "Zombie",
	Lines = {
		{
			Text = "Hello mister , am deeply in love with you."
		},
	},
}

return GreetingDialogueData
